(() => {
  const RR = {};
  RR.safeText = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[char]);
  RR.money = (value) => new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(value||0));
  RR.number = (value,fallback=0) => { const parsed=Number(value); return Number.isFinite(parsed)?parsed:fallback; };
  RR.roleCanViewFinancials = (role) => ["owner","admin","account","accounts"].includes(String(role||"").trim().toLowerCase());
  RR.roleCanOperateMasters = (role) => ["owner","admin"].includes(String(role||"").trim().toLowerCase());
  RR.requireRoles = async (allowedRoles=["owner","admin"]) => { const allowed=new Set((allowedRoles||[]).map(role=>String(role||"").trim().toLowerCase())); const {data,error}=await supabaseClient.auth.getSession(); if(error||!data.session){window.location.replace("real-login.html");throw new Error("Login required.");} const user=data.session.user; const {data:profile,error:profileError}=await supabaseClient.from("rr_user_profiles").select("id, full_name, role_code, is_active").eq("auth_user_id",user.id).single(); const role=String(profile?.role_code||"").trim().toLowerCase(); if(profileError||!profile?.is_active||!allowed.has(role)) throw new Error(`Required permission: ${[...allowed].join(" / ")}.`); return {session:data.session,user,profile:{...profile,role_code:role}}; };
  RR.requireOwner = async () => { const {data,error}=await supabaseClient.auth.getSession(); if(error||!data.session){window.location.replace("real-login.html");throw new Error("Login required.");} const user=data.session.user; const {data:profile,error:profileError}=await supabaseClient.from("rr_user_profiles").select("id, full_name, role_code, is_active").eq("auth_user_id",user.id).single(); if(profileError||!profile?.is_active||!["owner","admin"].includes(profile.role_code)){await supabaseClient.auth.signOut();window.location.replace("real-login.html");throw new Error("Owner/Admin access required.");} return {session:data.session,user,profile}; };
  RR.getTableColumns = async (table) => { const knownColumns={rr_art_master:["id","art_no","item_name","product_name","description","default_margin","is_active","created_at"],rr_art_costs:["id","art_id","cutting_rate","printing_rate","sticker_rate","kr_rate","ov_rate","fld_rate","thread_cut_rate","press_rate","packing_rate","other_rate","created_at"],rr_media:["id","entity_type","entity_id","media_category","file_url","storage_path","file_name","mime_type","caption","source_type","visibility_scope","is_cover","sort_order","created_at"]}; return new Set(knownColumns[table]||[]); };
  RR.pickColumn=(columns,aliases)=>aliases.find(name=>columns.has(name))||null; RR.filterPayload=(payload,columns)=>Object.fromEntries(Object.entries(payload).filter(([key,value])=>columns.has(key)&&value!==undefined)); RR.safeFileName=(name)=>String(name||"file").toLowerCase().replace(/[^a-z0-9._-]/g,"_");
  RR.inferMimeType=(file)=>{const declared=String(file?.type||"").trim().toLowerCase();if(declared&&declared!=="application/octet-stream")return declared;const extension=String(file?.name||"").split(".").pop().toLowerCase();return ({jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",webp:"image/webp",gif:"image/gif",heic:"image/heic",heif:"image/heif",mp4:"video/mp4",mov:"video/quicktime",webm:"video/webm","3gp":"video/3gpp"})[extension]||"";};
  RR.uploadMedia=async({file,entityType,entityId,mediaCategory="reference",sourceType="gallery",visibilityScope="factory",caption=""})=>{if(!file)return null;const mimeType=RR.inferMimeType(file);const path=[entityType,String(entityId),`${Date.now()}-${crypto.randomUUID()}-${RR.safeFileName(file.name)}`].join("/");const {error:uploadError}=await supabaseClient.storage.from("redzed-media").upload(path,file,{cacheControl:"3600",contentType:mimeType||undefined,upsert:false});if(uploadError)throw uploadError;const {data:publicData}=supabaseClient.storage.from("redzed-media").getPublicUrl(path);const columns=await RR.getTableColumns("rr_media");const payload=RR.filterPayload({entity_type:entityType,entity_id:String(entityId),media_category:mediaCategory,file_url:publicData.publicUrl,storage_path:path,file_name:file.name,mime_type:mimeType||null,caption,source_type:sourceType,visibility_scope:visibilityScope,is_cover:false,sort_order:0},columns);const {data,error}=await supabaseClient.from("rr_media").insert(payload).select().single();if(error)throw error;return data;};
  RR.getMediaMap=async(entityType,category)=>{let query=supabaseClient.from("rr_media").select("*").eq("entity_type",entityType).order("sort_order",{ascending:true}).order("created_at",{ascending:true});if(category)query=query.eq("media_category",category);const {data,error}=await query;if(error)throw error;return(data||[]).reduce((map,item)=>{const key=String(item.entity_id);if(!map[key])map[key]=[];map[key].push(item);return map;},{});};
  RR.installHassleFreeNumberInputs=()=>{if(document.documentElement.dataset.rrNumberInputsReady==="1")return;document.documentElement.dataset.rrNumberInputsReady="1";document.addEventListener("focusin",event=>{const input=event.target;if(!(input instanceof HTMLInputElement)||input.type!=="number"||input.readOnly||input.disabled||input.dataset.keepNumberFormat==="1")return;const raw=String(input.value||"").trim();if(/^[+-]?0+(?:\.0+)?$/.test(raw)){input.value="";return;}if(raw)requestAnimationFrame(()=>{try{input.select();}catch(_){}});});document.addEventListener("focusout",event=>{const input=event.target;if(!(input instanceof HTMLInputElement)||input.type!=="number"||input.readOnly||input.disabled||input.dataset.keepNumberFormat==="1")return;const raw=String(input.value||"").trim();if(!raw)return;const number=Number(raw);if(Number.isFinite(number))input.value=String(number);});};
  RR.installHassleFreeNumberInputs(); window.RR=RR;
})();

/* TEST62 FINAL: always request fresh global UI assets even when this bootstrap is loaded through an old ?v= page reference. */
(()=>{
  if(window.__REAL_FACTORY_GLOBAL_UI_LOADER_V775__)return;
  window.__REAL_FACTORY_GLOBAL_UI_LOADER_V775__=true;
  const current=document.currentScript?.src||location.href;
  const base=new URL('.',current);
  const stamp='test62-final-20260902-1258';
  const load=(file,id)=>new Promise((resolve,reject)=>{const old=document.getElementById(id);if(old)old.remove();const script=document.createElement('script');script.id=id;script.src=new URL(file,base).href+((file.includes('?'))?'&':'?')+'v='+encodeURIComponent(stamp);script.async=false;script.onload=resolve;script.onerror=()=>reject(new Error(`REAL FACTORY global utility failed to load: ${file}`));document.head.appendChild(script);});
  const dataModeLoader=load('real-data-mode-controller-v786-1-1.js','rr-data-mode-controller-v786-1-1');
  window.RRDataModeLoaderPromise=dataModeLoader;
  dataModeLoader.then(()=>load('real-mobile-compat-v775.js','rr-mobile-compat-v775')).then(()=>load('real-google-sheet-table-v775.js','rr-google-sheet-table-v775')).catch(error=>console.error(error));
})();
