-- REAL FACTORY V787 — PACKING TO SALES RETURN (TEST DEFAULT)
-- Additive migration. Existing production/payroll objects are not altered.
create extension if not exists pgcrypto;

create table if not exists public.rr_fg_sequences_v787(kind text not null, data_mode text not null check(data_mode in('TEST','REAL')), last_no bigint not null default 0, primary key(kind,data_mode));
create table if not exists public.rr_fg_products_v787(lot_no text primary key, full_item_name text, short_item_name text not null, size_text text, sale_rate numeric(12,2) not null default 0 check(sale_rate>=0), image_url text, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.rr_fg_pack_plans_v787(id uuid primary key default gen_random_uuid(),lot_no text not null,status text not null default 'DRAFT' check(status in('DRAFT','SUBMITTED','CANCELLED')),source_matrix jsonb not null,total_qty int not null check(total_qty>0),data_mode text not null default 'TEST' check(data_mode in('TEST','REAL')),created_by uuid not null default auth.uid(),created_at timestamptz not null default now(),submitted_by uuid,submitted_at timestamptz);
create unique index if not exists rr_fg_one_draft_pack_v787 on public.rr_fg_pack_plans_v787(lot_no,data_mode) where status='DRAFT';
create table if not exists public.rr_fg_boxes_v787(id uuid primary key default gen_random_uuid(),plan_id uuid not null references public.rr_fg_pack_plans_v787(id),box_code text not null,lot_no text not null,box_type text not null check(box_type in('REGULAR','ASST')),qty int not null check(qty>0),composition jsonb not null,status text not null default 'PACK_DRAFT' check(status in('PACK_DRAFT','READY_DESPATCH','IN_TRANSIT','STORE_AVAILABLE','SOLD','RETURN_HOLD')),location_code text check(location_code is null or location_code in('G1','G2','G3','G4')),data_mode text not null check(data_mode in('TEST','REAL')),created_at timestamptz not null default now(),unique(box_code,data_mode));
create table if not exists public.rr_fg_despatch_v787(id uuid primary key default gen_random_uuid(),challan_no text not null,destination text not null check(destination in('G1','G2','G3','G4')),status text not null default 'IN_TRANSIT' check(status in('IN_TRANSIT','PART_RECEIVED','RECEIVED','REVERSED')),remarks text,data_mode text not null check(data_mode in('TEST','REAL')),sent_by uuid not null default auth.uid(),sent_at timestamptz not null default now(),received_by uuid,received_at timestamptz,receive_remarks text,unique(challan_no,data_mode));
create table if not exists public.rr_fg_despatch_boxes_v787(despatch_id uuid references public.rr_fg_despatch_v787(id),box_id uuid references public.rr_fg_boxes_v787(id),accepted boolean,primary key(despatch_id,box_id));
create table if not exists public.rr_fg_stock_ledger_v787(id uuid primary key default gen_random_uuid(),txn_type text not null,ref_type text not null,ref_id uuid,lot_no text not null,stock_type text not null check(stock_type in('REGULAR','ASST','ALTER_DAMAGE')),location_code text,qty_delta int not null check(qty_delta<>0),rate numeric(12,2),data_mode text not null check(data_mode in('TEST','REAL')),created_by uuid not null default auth.uid(),created_at timestamptz not null default now(),meta jsonb not null default '{}'::jsonb);
create unique index if not exists rr_fg_ledger_idempotent_v787 on public.rr_fg_stock_ledger_v787(txn_type,ref_type,ref_id,lot_no,stock_type,coalesce(location_code,''));
create table if not exists public.rr_buyers_v787(id uuid primary key default gen_random_uuid(),buyer_name text not null unique,contact_no text,address text,gst_no text,dispatch_details text,discount_type text check(discount_type in('FLAT','PERCENT')),discount_value numeric(12,2) not null default 0 check(discount_value>=0),active boolean not null default true);
create table if not exists public.rr_fg_pi_v787(id uuid primary key default gen_random_uuid(),pi_no text not null,cpi_no text,buyer_id uuid references public.rr_buyers_v787(id),buyer_snapshot jsonb not null,status text not null default 'DRAFT' check(status in('DRAFT','CPI_FINAL','CANCELLED')),value_added_pct numeric(9,4) not null default 0,packing_other numeric(12,2) not null default 0 check(packing_other>=0),sub_total numeric(14,2) not null default 0,round_off numeric(12,2) not null default 0,grand_total numeric(14,2) not null default 0,version_no int not null default 1,dispatch_details text,data_mode text not null check(data_mode in('TEST','REAL')),created_by uuid not null default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),finalized_by uuid,finalized_at timestamptz,qty_verified boolean not null default false,qty_verified_by uuid,qty_verified_at timestamptz,qty_verification_snapshot jsonb,qty_verification_remarks text,unique(pi_no,data_mode),unique(cpi_no,data_mode));
create table if not exists public.rr_fg_pi_lines_v787(id uuid primary key default gen_random_uuid(),pi_id uuid not null references public.rr_fg_pi_v787(id) on delete cascade,lot_no text not null,short_item_name text not null,stock_type text not null check(stock_type in('REGULAR','ASST')),qty int not null check(qty>0),original_rate numeric(12,2) not null check(original_rate>=0),discount_amount numeric(12,2) not null default 0,final_rate numeric(12,2) not null check(final_rate>=0),amount numeric(14,2) not null check(amount>=0),returned_qty int not null default 0 check(returned_qty>=0 and returned_qty<=qty));
create table if not exists public.rr_fg_pi_versions_v787(id uuid primary key default gen_random_uuid(),pi_id uuid not null references public.rr_fg_pi_v787(id),version_no int not null,snapshot jsonb not null,saved_by uuid not null default auth.uid(),saved_at timestamptz not null default now(),unique(pi_id,version_no));
create table if not exists public.rr_fg_returns_v787(id uuid primary key default gen_random_uuid(),return_no text not null,mode text not null check(mode in('KNOWN','ANONYMOUS')),cpi_line_id uuid references public.rr_fg_pi_lines_v787(id),condition text check(condition is null or condition in('FRESH','ASST_MIX_FRESH','ALTER_DAMAGE')),lot_no text not null,stock_type text not null check(stock_type in('REGULAR','ASST','ALTER_DAMAGE')),qty int not null check(qty>0),rate numeric(12,2) not null check(rate>=0),amount numeric(14,2) not null,remarks text,data_mode text not null check(data_mode in('TEST','REAL')),received_by uuid not null default auth.uid(),received_at timestamptz not null default now(),unique(return_no,data_mode));

create or replace function public.rr_fg_next_no_v787(p_kind text,p_mode text,p_prefix text) returns text language plpgsql security definer set search_path=public as $$declare n bigint;begin if p_mode not in('TEST','REAL') then raise exception 'Invalid data mode';end if;insert into rr_fg_sequences_v787(kind,data_mode,last_no) values(p_kind,p_mode,1) on conflict(kind,data_mode) do update set last_no=rr_fg_sequences_v787.last_no+1 returning last_no into n;return p_prefix||n::text;end$$;
create or replace function public.rr_fg_assert_user_v787() returns void language plpgsql security definer set search_path=public as $$begin if auth.uid() is null then raise exception 'Login required';end if;if not exists(select 1 from rr_user_profiles where auth_user_id=auth.uid() and coalesce(is_active,false)) then raise exception 'Active user profile required';end if;end$$;

create or replace view public.rr_fg_stock_balance_v787 as select l.lot_no,coalesce(p.short_item_name,l.lot_no) short_item_name,l.stock_type,string_agg(distinct l.location_code,', ' order by l.location_code) location_code,sum(l.qty_delta)::int available_qty,coalesce(p.sale_rate,0) sale_rate,l.data_mode from rr_fg_stock_ledger_v787 l left join rr_fg_products_v787 p using(lot_no) group by l.lot_no,p.short_item_name,l.stock_type,p.sale_rate,l.data_mode having sum(l.qty_delta)<>0;
create or replace view public.rr_fg_ready_box_v787 as select id box_id,box_code,lot_no,box_type,qty,data_mode from rr_fg_boxes_v787 where status='READY_DESPATCH' and data_mode='TEST';
create or replace view public.rr_fg_receive_pending_v787 as select d.id despatch_id,d.challan_no,d.destination,sum(b.qty)::int total_qty,jsonb_agg(jsonb_build_object('box_id',b.id,'box_code',b.box_code,'qty',b.qty,'type',b.box_type) order by b.box_code) boxes from rr_fg_despatch_v787 d join rr_fg_despatch_boxes_v787 x on x.despatch_id=d.id join rr_fg_boxes_v787 b on b.id=x.box_id where d.status in('IN_TRANSIT','PART_RECEIVED') and x.accepted is null and d.data_mode='TEST' group by d.id;
create or replace view public.rr_fg_final_cpi_v787 as select p.id cpi_id,p.cpi_no,p.buyer_snapshot->>'buyer_name' buyer_name,sum(l.qty)::int total_qty,p.grand_total,p.qty_verified,p.finalized_at,p.data_mode from rr_fg_pi_v787 p join rr_fg_pi_lines_v787 l on l.pi_id=p.id where p.status='CPI_FINAL' and p.data_mode='TEST' group by p.id;

create or replace function public.rr_fg_packable_matrix_v787(p_lot_no text,p_data_mode text default 'TEST') returns jsonb language plpgsql security definer set search_path=public as $$declare r jsonb;begin perform rr_fg_assert_user_v787();if to_regclass('public.rr_lot_process_actuals') is not null then execute 'select coalesce(jsonb_agg(jsonb_build_object(''colour_code'',coalesce(colour_name,colour_id::text,''UNKNOWN''),''size_code'',coalesce(size_code,''ALL''),''qty'',greatest(0,floor(coalesce(out_pcs,in_pcs,0)))::int)),''[]''::jsonb) from rr_lot_process_actuals where lot_no=$1 and upper(process_code) in(''PRESS'',''PACKING'')' into r using p_lot_no;else r:='[]'::jsonb;end if;return r;end$$;

create or replace function public.rr_fg_generate_pack_v787(p_lot_no text,p_matrix jsonb,p_data_mode text default 'TEST') returns jsonb language plpgsql security definer set search_path=public as $$declare pid uuid;total int;regular_boxes int;remainder int;i int;need int;take_qty int;boxqty int;boxcode text;cells jsonb;rec record;begin perform rr_fg_assert_user_v787();if nullif(trim(p_lot_no),'') is null or jsonb_typeof(p_matrix)<>'array' then raise exception 'Lot and matrix required';end if;create temporary table tmp_fg_pack(colour_code text,size_code text,qty int,primary key(colour_code,size_code))on commit drop;insert into tmp_fg_pack select trim(x->>'colour_code'),trim(x->>'size_code'),sum((x->>'qty')::int) from jsonb_array_elements(p_matrix)x where (x->>'qty')::int>=0 group by 1,2;select coalesce(sum(qty),0) into total from tmp_fg_pack;if total<=0 then raise exception 'Packable quantity must be positive';end if;regular_boxes:=total/18;remainder:=total%18;delete from rr_fg_pack_plans_v787 where lot_no=trim(p_lot_no) and data_mode=p_data_mode and status='DRAFT';insert into rr_fg_pack_plans_v787(lot_no,source_matrix,total_qty,data_mode)values(trim(p_lot_no),p_matrix,total,p_data_mode)returning id into pid;
  for i in 1..(regular_boxes+case when remainder>0 then 1 else 0 end) loop need:=case when i<=regular_boxes then 18 else remainder end;boxqty:=need;cells:='[]'::jsonb;
    -- Size-first, then highest colour balance: gives the closest possible alternate composition while preserving exact cells.
    while need>0 loop select colour_code,size_code,qty into rec from tmp_fg_pack where qty>0 order by qty desc,size_code,colour_code limit 1;if not found then raise exception 'Packing algorithm balance failure';end if;take_qty:=least(rec.qty,need);cells:=cells||jsonb_build_array(jsonb_build_object('colour_code',rec.colour_code,'size_code',rec.size_code,'qty',take_qty));update tmp_fg_pack set qty=qty-take_qty where colour_code=rec.colour_code and size_code=rec.size_code;need:=need-take_qty;end loop;
    boxcode:=rr_fg_next_no_v787('BOX',p_data_mode,case when p_data_mode='TEST' then 'TBOX' else 'BOX' end);insert into rr_fg_boxes_v787(plan_id,box_code,lot_no,box_type,qty,composition,data_mode)values(pid,boxcode,trim(p_lot_no),case when boxqty=18 then 'REGULAR' else 'ASST' end,boxqty,cells,p_data_mode);
  end loop;if exists(select 1 from tmp_fg_pack where qty<>0) then raise exception 'Unpacked balance remains';end if;return jsonb_build_object('plan_id',pid,'total_qty',total,'regular_boxes',regular_boxes,'asst_qty',remainder);end$$;
create or replace function public.rr_fg_pack_plan_detail_v787(p_plan_id uuid) returns jsonb language sql security definer set search_path=public as $$select jsonb_build_object('total_qty',p.total_qty,'boxes',coalesce((select jsonb_agg(jsonb_build_object('box_id',b.id,'box_code',b.box_code,'box_type',b.box_type,'qty',b.qty,'cells',b.composition) order by b.created_at) from rr_fg_boxes_v787 b where b.plan_id=p.id),'[]'::jsonb)) from rr_fg_pack_plans_v787 p where p.id=p_plan_id$$;
create or replace function public.rr_fg_submit_pack_v787(p_plan_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare p rr_fg_pack_plans_v787%rowtype;q int;c int;begin perform rr_fg_assert_user_v787();select * into p from rr_fg_pack_plans_v787 where id=p_plan_id for update;if not found or p.status<>'DRAFT' then raise exception 'Open packing plan not found';end if;select coalesce(sum(qty),0),count(*) into q,c from rr_fg_boxes_v787 where plan_id=p.id;if q<>p.total_qty then raise exception 'Packed quantity mismatch';end if;update rr_fg_pack_plans_v787 set status='SUBMITTED',submitted_by=auth.uid(),submitted_at=now() where id=p.id;update rr_fg_boxes_v787 set status='READY_DESPATCH' where plan_id=p.id;return jsonb_build_object('total_boxes',c,'total_qty',q);end$$;

create or replace function public.rr_fg_create_despatch_v787(p_box_ids uuid[],p_destination text,p_remarks text default null,p_data_mode text default 'TEST') returns jsonb language plpgsql security definer set search_path=public as $$declare did uuid;cn text;c int;q int;begin perform rr_fg_assert_user_v787();if cardinality(p_box_ids)<1 or p_destination not in('G1','G2','G3','G4') then raise exception 'Boxes and destination required';end if;perform 1 from rr_fg_boxes_v787 where id=any(p_box_ids) and status='READY_DESPATCH' and data_mode=p_data_mode for update;if (select count(*) from rr_fg_boxes_v787 where id=any(p_box_ids) and status='READY_DESPATCH' and data_mode=p_data_mode)<>cardinality(p_box_ids) then raise exception 'One or more boxes unavailable';end if;cn:=rr_fg_next_no_v787('CHALLAN',p_data_mode,case when p_data_mode='TEST' then 'TDC' else 'DC' end);insert into rr_fg_despatch_v787(challan_no,destination,remarks,data_mode)values(cn,p_destination,p_remarks,p_data_mode)returning id into did;insert into rr_fg_despatch_boxes_v787 select did,unnest(p_box_ids),null;update rr_fg_boxes_v787 set status='IN_TRANSIT' where id=any(p_box_ids);select count(*),sum(qty) into c,q from rr_fg_boxes_v787 where id=any(p_box_ids);return jsonb_build_object('despatch_id',did,'challan_no',cn,'total_boxes',c,'total_qty',q);end$$;
create or replace function public.rr_fg_receive_despatch_v787(p_despatch_id uuid,p_accepted_box_ids uuid[],p_remarks text default null) returns jsonb language plpgsql security definer set search_path=public as $$declare d rr_fg_despatch_v787%rowtype;q int;pending int;begin perform rr_fg_assert_user_v787();select * into d from rr_fg_despatch_v787 where id=p_despatch_id for update;if not found or d.status not in('IN_TRANSIT','PART_RECEIVED') then raise exception 'Pending challan not found';end if;if exists(select 1 from unnest(p_accepted_box_ids)x where not exists(select 1 from rr_fg_despatch_boxes_v787 db where db.despatch_id=d.id and db.box_id=x and db.accepted is null)) then raise exception 'Invalid or already received box';end if;update rr_fg_despatch_boxes_v787 set accepted=true where despatch_id=d.id and box_id=any(p_accepted_box_ids);update rr_fg_boxes_v787 set status='STORE_AVAILABLE',location_code=d.destination where id=any(p_accepted_box_ids);insert into rr_fg_stock_ledger_v787(txn_type,ref_type,ref_id,lot_no,stock_type,location_code,qty_delta,data_mode,meta) select 'STORE_RECEIVE','DESPATCH_BOX',b.id,b.lot_no,b.box_type,d.destination,b.qty,b.data_mode,jsonb_build_object('challan_no',d.challan_no) from rr_fg_boxes_v787 b where b.id=any(p_accepted_box_ids) on conflict do nothing;select coalesce(sum(qty),0) into q from rr_fg_boxes_v787 where id=any(p_accepted_box_ids);select count(*) into pending from rr_fg_despatch_boxes_v787 where despatch_id=d.id and accepted is null;update rr_fg_despatch_v787 set status=case when pending=0 then 'RECEIVED' else 'PART_RECEIVED' end,received_by=auth.uid(),received_at=now(),receive_remarks=p_remarks where id=d.id;return jsonb_build_object('accepted_qty',q,'pending_boxes',pending);end$$;

create or replace function public.rr_fg_save_pi_v787(p_pi_id uuid,p_buyer_name text,p_dispatch_details text,p_lines jsonb,p_value_added_pct numeric default 0,p_packing_other numeric default 0,p_finalize boolean default false,p_data_mode text default 'TEST') returns jsonb language plpgsql security definer set search_path=public as $$declare pid uuid;bid uuid;pi text;cpi text;ver int;sub numeric;raw numeric;grand numeric;ln jsonb;avail int;begin perform rr_fg_assert_user_v787();if p_packing_other<0 or jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0 then raise exception 'Valid PI lines and non-negative Packing & Other required';end if;select id into bid from rr_buyers_v787 where lower(buyer_name)=lower(trim(p_buyer_name));if bid is null then insert into rr_buyers_v787(buyer_name)values(trim(p_buyer_name))returning id into bid;end if;if p_pi_id is null then pi:=rr_fg_next_no_v787('PI',p_data_mode,case when p_data_mode='TEST' then 'TPI' else 'PI' end);insert into rr_fg_pi_v787(pi_no,buyer_id,buyer_snapshot,dispatch_details,data_mode)select pi,b.id,jsonb_build_object('buyer_name',b.buyer_name,'contact_no',b.contact_no,'address',b.address,'gst_no',b.gst_no),p_dispatch_details,p_data_mode from rr_buyers_v787 b where b.id=bid returning id into pid;else select id,version_no into pid,ver from rr_fg_pi_v787 where id=p_pi_id and status='DRAFT' and data_mode=p_data_mode for update;if pid is null then raise exception 'Editable PI not found';end if;update rr_fg_pi_v787 set version_no=version_no+1,buyer_id=bid,dispatch_details=p_dispatch_details,updated_at=now() where id=pid;delete from rr_fg_pi_lines_v787 where pi_id=pid;end if;
for ln in select * from jsonb_array_elements(p_lines) loop if (ln->>'stock_type') not in('REGULAR','ASST') or (ln->>'qty')::int<=0 or (ln->>'rate')::numeric<0 then raise exception 'Invalid PI line';end if;select coalesce(sum(available_qty),0) into avail from rr_fg_stock_balance_v787 where lot_no=ln->>'lot_no' and stock_type=ln->>'stock_type' and data_mode=p_data_mode;if p_finalize and avail<(ln->>'qty')::int then raise exception 'Insufficient % stock for Lot %',ln->>'stock_type',ln->>'lot_no';end if;insert into rr_fg_pi_lines_v787(pi_id,lot_no,short_item_name,stock_type,qty,original_rate,final_rate,amount)values(pid,ln->>'lot_no',coalesce(nullif(ln->>'short_item_name',''),ln->>'lot_no'),ln->>'stock_type',(ln->>'qty')::int,(ln->>'rate')::numeric,(ln->>'rate')::numeric,(ln->>'qty')::int*(ln->>'rate')::numeric);end loop;select coalesce(sum(amount),0) into sub from rr_fg_pi_lines_v787 where pi_id=pid;raw:=sub+(sub*p_value_added_pct/100)+p_packing_other;grand:=round(raw/10)*10;update rr_fg_pi_v787 set value_added_pct=p_value_added_pct,packing_other=p_packing_other,sub_total=sub,round_off=grand-raw,grand_total=grand,updated_at=now() where id=pid;select version_no into ver from rr_fg_pi_v787 where id=pid;insert into rr_fg_pi_versions_v787(pi_id,version_no,snapshot)select pid,ver,jsonb_build_object('header',to_jsonb(p),'lines',(select jsonb_agg(to_jsonb(l)) from rr_fg_pi_lines_v787 l where l.pi_id=pid)) from rr_fg_pi_v787 p where p.id=pid on conflict do nothing;
if p_finalize then cpi:=rr_fg_next_no_v787('CPI',p_data_mode,case when p_data_mode='TEST' then 'TCPI' else 'CPI' end);for ln in select to_jsonb(l) from rr_fg_pi_lines_v787 l where l.pi_id=pid loop insert into rr_fg_stock_ledger_v787(txn_type,ref_type,ref_id,lot_no,stock_type,location_code,qty_delta,rate,data_mode,meta) values('CPI_SALE','CPI_LINE',(ln->>'id')::uuid,ln->>'lot_no',ln->>'stock_type',null,-(ln->>'qty')::int,(ln->>'final_rate')::numeric,p_data_mode,jsonb_build_object('pi_id',pid)) ;end loop;update rr_fg_pi_v787 set status='CPI_FINAL',cpi_no=cpi,finalized_by=auth.uid(),finalized_at=now() where id=pid;end if;select pi_no into pi from rr_fg_pi_v787 where id=pid;return jsonb_build_object('pi_id',pid,'pi_no',pi,'cpi_no',cpi,'grand_total',grand);end$$;
create or replace function public.rr_fg_verify_cpi_qty_v787(p_cpi_id uuid,p_remarks text default null) returns jsonb language plpgsql security definer set search_path=public as $$declare n text;s jsonb;begin perform rr_fg_assert_user_v787();select cpi_no,jsonb_build_object('cpi_no',cpi_no,'version',version_no,'lines',(select jsonb_agg(to_jsonb(l)) from rr_fg_pi_lines_v787 l where l.pi_id=p.id)) into n,s from rr_fg_pi_v787 p where id=p_cpi_id and status='CPI_FINAL' for update;if n is null then raise exception 'Final CPI not found';end if;update rr_fg_pi_v787 set qty_verified=true,qty_verified_by=auth.uid(),qty_verified_at=now(),qty_verification_snapshot=s,qty_verification_remarks=p_remarks where id=p_cpi_id;return jsonb_build_object('cpi_no',n,'verified',true);end$$;
create or replace function public.rr_fg_returnable_lines_v787(p_cpi_id uuid) returns table(line_id uuid,lot_no text,stock_type text,final_rate numeric,returnable_qty int) language sql security definer set search_path=public as $$select l.id,l.lot_no,l.stock_type,l.final_rate,l.qty-l.returned_qty from rr_fg_pi_lines_v787 l join rr_fg_pi_v787 p on p.id=l.pi_id where p.id=p_cpi_id and p.status='CPI_FINAL' and l.qty>l.returned_qty$$;
create or replace function public.rr_fg_post_return_v787(p_mode text,p_cpi_line_id uuid,p_condition text,p_new_lot_no text,p_qty int,p_remarks text,p_data_mode text default 'TEST') returns jsonb language plpgsql security definer set search_path=public as $$declare rn text;lot text;stype text;r numeric;line rr_fg_pi_lines_v787%rowtype;rid uuid;begin perform rr_fg_assert_user_v787();if p_qty<=0 or p_mode not in('KNOWN','ANONYMOUS') then raise exception 'Valid mode and quantity required';end if;if p_mode='KNOWN' then select * into line from rr_fg_pi_lines_v787 where id=p_cpi_line_id for update;if not found or p_qty>line.qty-line.returned_qty then raise exception 'Return exceeds sold balance';end if;lot:=line.lot_no;stype:=line.stock_type;r:=line.final_rate;update rr_fg_pi_lines_v787 set returned_qty=returned_qty+p_qty where id=line.id;else r:=100;if p_condition='FRESH' then if nullif(trim(p_new_lot_no),'') is null then raise exception 'Fresh Anonymous GR requires New Lot No';end if;lot:=trim(p_new_lot_no);stype:='REGULAR';elsif p_condition='ASST_MIX_FRESH' then lot:='ASST-MIX-FIXED';stype:='ASST';elsif p_condition='ALTER_DAMAGE' then lot:=coalesce(nullif(trim(p_new_lot_no),''),'ALTER-DAMAGE');stype:='ALTER_DAMAGE';else raise exception 'Anonymous condition required';end if;end if;rn:=rr_fg_next_no_v787('RETURN',p_data_mode,case when p_data_mode='TEST' then 'TGR' else 'GR' end);insert into rr_fg_returns_v787(return_no,mode,cpi_line_id,condition,lot_no,stock_type,qty,rate,amount,remarks,data_mode)values(rn,p_mode,p_cpi_line_id,p_condition,lot,stype,p_qty,r,p_qty*r,p_remarks,p_data_mode)returning id into rid;insert into rr_fg_stock_ledger_v787(txn_type,ref_type,ref_id,lot_no,stock_type,qty_delta,rate,data_mode,meta)values('SALES_RETURN','RETURN',rid,lot,stype,p_qty,r,p_data_mode,jsonb_build_object('mode',p_mode,'condition',p_condition));return jsonb_build_object('return_no',rn,'qty',p_qty,'rate',r,'lot_no',lot,'stock_type',stype);end$$;

alter table public.rr_fg_sequences_v787 enable row level security;alter table public.rr_fg_products_v787 enable row level security;alter table public.rr_fg_pack_plans_v787 enable row level security;alter table public.rr_fg_boxes_v787 enable row level security;alter table public.rr_fg_despatch_v787 enable row level security;alter table public.rr_fg_despatch_boxes_v787 enable row level security;alter table public.rr_fg_stock_ledger_v787 enable row level security;alter table public.rr_buyers_v787 enable row level security;alter table public.rr_fg_pi_v787 enable row level security;alter table public.rr_fg_pi_lines_v787 enable row level security;alter table public.rr_fg_pi_versions_v787 enable row level security;alter table public.rr_fg_returns_v787 enable row level security;
do $$declare t text;begin foreach t in array array['rr_fg_products_v787','rr_fg_pack_plans_v787','rr_fg_boxes_v787','rr_fg_despatch_v787','rr_fg_despatch_boxes_v787','rr_fg_stock_ledger_v787','rr_buyers_v787','rr_fg_pi_v787','rr_fg_pi_lines_v787','rr_fg_pi_versions_v787','rr_fg_returns_v787'] loop execute format('drop policy if exists %I on public.%I',t||'_active',t);execute format('create policy %I on public.%I for select to authenticated using (exists(select 1 from public.rr_user_profiles u where u.auth_user_id=auth.uid() and coalesce(u.is_active,false)))',t||'_active',t);end loop;end$$;
grant select on public.rr_fg_stock_balance_v787,public.rr_fg_ready_box_v787,public.rr_fg_receive_pending_v787,public.rr_fg_final_cpi_v787,public.rr_buyers_v787 to authenticated;
grant execute on function public.rr_fg_packable_matrix_v787(text,text),public.rr_fg_generate_pack_v787(text,jsonb,text),public.rr_fg_pack_plan_detail_v787(uuid),public.rr_fg_submit_pack_v787(uuid),public.rr_fg_create_despatch_v787(uuid[],text,text,text),public.rr_fg_receive_despatch_v787(uuid,uuid[],text),public.rr_fg_save_pi_v787(uuid,text,text,jsonb,numeric,numeric,boolean,text),public.rr_fg_verify_cpi_qty_v787(uuid,text),public.rr_fg_returnable_lines_v787(uuid),public.rr_fg_post_return_v787(text,uuid,text,text,int,text,text) to authenticated;
