-- REDZED Universal Production V769
-- Worker Claim reason + 2-warning gate + 24-hour Alter-to-Damage control
--
-- Existing responsibility, Alter journey and rr_upm_save_damage_v731 remain unchanged.
-- This file only installs a persistent warning ledger and gate RPC.

begin;

create table if not exists public.rr_upm_worker_claim_warning_v769 (
  id bigint generated by default as identity primary key,
  canonical_lot_id text not null,
  department_code text not null,
  colour_code text not null,
  size_code text not null,
  worker_id text,
  reason_code text not null,
  qty numeric(14,3) not null default 0 check (qty >= 0),
  warning_no smallint not null check (warning_no between 1 and 3),
  warning_message text not null,
  warning_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  conversion_authorized boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists rr_upm_worker_claim_warning_v769_key_uq
on public.rr_upm_worker_claim_warning_v769 (
  canonical_lot_id,
  department_code,
  colour_code,
  size_code,
  coalesce(worker_id,''),
  reason_code,
  warning_no
);

create index if not exists rr_upm_worker_claim_warning_v769_lookup_idx
on public.rr_upm_worker_claim_warning_v769 (
  canonical_lot_id,
  department_code,
  colour_code,
  size_code,
  reason_code,
  warning_at
);

alter table public.rr_upm_worker_claim_warning_v769 enable row level security;
revoke all on table public.rr_upm_worker_claim_warning_v769 from public, anon, authenticated;

create or replace function public.rr_upm_worker_claim_warning_gate_v769(
  p_canonical_lot_id text,
  p_department_code text,
  p_colour_code text,
  p_size_code text,
  p_worker_id text default null,
  p_reason_code text default null,
  p_qty numeric default 0,
  p_require_24_hours boolean default true,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_lot text := nullif(trim(coalesce(p_canonical_lot_id,'')),'');
  v_department text := upper(nullif(trim(coalesce(p_department_code,'')),''));
  v_colour text := upper(nullif(trim(coalesce(p_colour_code,'')),''));
  v_size text := upper(nullif(trim(coalesce(p_size_code,'')),''));
  v_worker text := nullif(trim(coalesce(p_worker_id,'')),'');
  v_reason text := upper(nullif(trim(coalesce(p_reason_code,'')),''));
  v_warning_count integer := 0;
  v_first_warning_at timestamptz;
  v_elapsed_hours numeric := 0;
  v_remaining_hours numeric := 0;
  v_warning_no smallint;
  v_message text;
  v_lock_key text;
begin
  if auth.uid() is null then
    raise exception 'Login required.';
  end if;

  if v_lot is null then raise exception 'Canonical Lot ID is required.'; end if;
  if v_department is null then raise exception 'Department is required.'; end if;
  if v_colour is null then raise exception 'Colour is required.'; end if;
  if v_size is null then raise exception 'Size is required.'; end if;
  if v_reason is null then raise exception 'Worker Claim reason is required.'; end if;
  if coalesce(p_qty,0) <= 0 then raise exception 'Damage quantity must be greater than zero.'; end if;

  v_lock_key := concat_ws('|',v_lot,v_department,v_colour,v_size,coalesce(v_worker,''),v_reason);
  perform pg_advisory_xact_lock(hashtextextended(v_lock_key,0));

  select count(*), min(warning_at)
    into v_warning_count, v_first_warning_at
  from public.rr_upm_worker_claim_warning_v769
  where canonical_lot_id = v_lot
    and department_code = v_department
    and colour_code = v_colour
    and size_code = v_size
    and coalesce(worker_id,'') = coalesce(v_worker,'')
    and reason_code = v_reason
    and warning_no in (1,2);

  if v_warning_count < 2 then
    v_warning_no := (v_warning_count + 1)::smallint;
    v_message := case v_warning_no
      when 1 then 'पहली warning: Alter/Remake holder को तुरंत pending work complete करने को कहा गया.'
      else 'दूसरी और अंतिम warning: अगली eligible attempt पर pending hold Worker Claim Damage बनेगा.'
    end;

    insert into public.rr_upm_worker_claim_warning_v769 (
      canonical_lot_id,department_code,colour_code,size_code,worker_id,
      reason_code,qty,warning_no,warning_message,conversion_authorized,metadata
    ) values (
      v_lot,v_department,v_colour,v_size,v_worker,
      v_reason,coalesce(p_qty,0),v_warning_no,v_message,false,coalesce(p_metadata,'{}'::jsonb)
    )
    on conflict do nothing;

    return jsonb_build_object(
      'allowed',false,
      'action',case when v_warning_no=1 then 'WARNING_1' else 'WARNING_2' end,
      'warning_no',v_warning_no,
      'warning_count',v_warning_no,
      'first_warning_at',coalesce(v_first_warning_at,now()),
      'message',v_message
    );
  end if;

  v_elapsed_hours := extract(epoch from (now() - v_first_warning_at)) / 3600.0;
  v_remaining_hours := greatest(0,24 - v_elapsed_hours);

  if coalesce(p_require_24_hours,true) and v_elapsed_hours < 24 then
    return jsonb_build_object(
      'allowed',false,
      'action','WAIT_24H',
      'warning_no',2,
      'warning_count',2,
      'first_warning_at',v_first_warning_at,
      'elapsed_hours',round(v_elapsed_hours,2),
      'remaining_hours',round(v_remaining_hours,2),
      'message','2 warnings दर्ज हैं, लेकिन first warning से 24 घंटे पूरे नहीं हुए.'
    );
  end if;

  v_message := case
    when coalesce(p_require_24_hours,true)
      then 'Final alert: 24 घंटे में response/complete नहीं हुआ. Selected hold को Worker Claim Damage में convert करने की अनुमति.'
    else 'Final alert: 2 warnings के बाद selected hold को Worker Claim Damage में convert करने की अनुमति.'
  end;

  insert into public.rr_upm_worker_claim_warning_v769 (
    canonical_lot_id,department_code,colour_code,size_code,worker_id,
    reason_code,qty,warning_no,warning_message,conversion_authorized,metadata
  ) values (
    v_lot,v_department,v_colour,v_size,v_worker,
    v_reason,coalesce(p_qty,0),3,v_message,true,coalesce(p_metadata,'{}'::jsonb)
  )
  on conflict do nothing;

  update public.rr_upm_worker_claim_warning_v769
  set qty = coalesce(p_qty,0),
      warning_message = v_message,
      conversion_authorized = true,
      metadata = coalesce(metadata,'{}'::jsonb) || coalesce(p_metadata,'{}'::jsonb)
  where canonical_lot_id = v_lot
    and department_code = v_department
    and colour_code = v_colour
    and size_code = v_size
    and coalesce(worker_id,'') = coalesce(v_worker,'')
    and reason_code = v_reason
    and warning_no = 3;

  return jsonb_build_object(
    'allowed',true,
    'action','ALLOW_DAMAGE',
    'warning_no',3,
    'warning_count',3,
    'first_warning_at',v_first_warning_at,
    'elapsed_hours',round(v_elapsed_hours,2),
    'remaining_hours',0,
    'message',v_message
  );
end
$function$;

revoke all on function public.rr_upm_worker_claim_warning_gate_v769(
  text,text,text,text,text,text,numeric,boolean,jsonb
) from public;

grant execute on function public.rr_upm_worker_claim_warning_gate_v769(
  text,text,text,text,text,text,numeric,boolean,jsonb
) to authenticated;

commit;

-- Verification:
-- select to_regprocedure(
--   'public.rr_upm_worker_claim_warning_gate_v769(text,text,text,text,text,text,numeric,boolean,jsonb)'
-- ) as installed_rpc;
