"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs");
const html=fs.readFileSync("test70-cb-purchase-real-chat-pilot.html","utf8");
const js=fs.readFileSync("test70-real-chat-live-v70.js","utf8");
const sql=fs.readFileSync("supabase/migrations/20260911150000_test70_real_chat_work_mapping.sql","utf8");
const directorySql=fs.readFileSync("supabase/migrations/20260911201000_test70_real_chat_directory.sql","utf8");
const bridgeSql=fs.readFileSync("supabase/migrations/20260911214000_test70_real_chat_message_bridge.sql","utf8");
const membershipSql=fs.readFileSync("supabase/migrations/20260911223500_test70_department_membership_matrix.sql","utf8");
const reconcileSql=fs.readFileSync("supabase/migrations/20260912040633_test70_reconcile_department_membership.sql","utf8");
const actionsSql=fs.readFileSync("supabase/migrations/20260912090000_test70_real_chat_canonical_work_actions_v71.sql","utf8");
const historySql=fs.readFileSync("supabase/migrations/20260912093000_test70_real_chat_full_history_sync_v71.sql","utf8");
const e2eSql=fs.readFileSync("supabase/migrations/20260912094500_test70_real_chat_end_to_end_events_v71.sql","utf8");
const archiveSql=fs.readFileSync("supabase/migrations/20260912101500_test70_real_chat_sellable_archive_v71.sql","utf8");
const truthfulSql=fs.readFileSync("supabase/migrations/20260912060848_test70_real_chat_truthful_mapping_v72.sql","utf8");
const behalfSql=fs.readFileSync("supabase/migrations/20260912062417_test70_real_chat_on_behalf_mapping_v73.sql","utf8");
const twoWaySql=fs.readFileSync("supabase/migrations/20260912124500_test70_real_chat_global_two_way_participants_v74.sql","utf8");
for(const text of ["Real Chat","OPEN","WORKING","CLOSE","TEST · LIVE","Lot Number, Category ya Worker Name","PERSONAL CHAT","test70-real-chat-live-v70.js"])assert.ok(html.includes(text),`Missing UI contract: ${text}`);
for(const text of ["rr_real_chat_work_inbox_v70","UPM_ASSIGNMENT:","rr_upm_work_assignments_v8","rr_upm_current_worker_id_v9112","read_only_mirror","revoke all","grant execute"])assert.ok(sql.includes(text),`Missing backend contract: ${text}`);
for(const text of ["rr_real_chat_work_inbox_v71","rr_real_chat_message_bridge_v70","rr_real_chat_mark_receipt_v70","LIVE_TEST_MAPPING","RECEIPTS_ONLY_ACTIONS_USE_EXISTING_FORMS","Art","Print","Sticker","Metal ID"])assert.ok(js.includes(text),`Missing live adapter contract: ${text}`);
for(const text of ["rr_real_chat_directory_v71","ALL DEPARTMENTS","PERSONAL CHAT","departments","people"])assert.ok(js.includes(text),`Missing canonical directory contract: ${text}`);
for(const text of ["CUTTING","STITCHING","TEAK_TANKI","DISPATCH","badsha","sanju","kartik","NOT_CONFIGURED","home_department_code"])assert.ok(directorySql.includes(text),`Missing directory mapping: ${text}`);
assert.ok(directorySql.includes("lower(b.worker_name) in ('badsha','sanju','kartik')"),"Dual-mapped staff must remain visible in their home department worker list");
assert.ok(!js.includes("S.db.rpc('rr_upm_")&&!js.includes(".insert(")&&!js.includes(".update("),"Real Chat adapter must not directly write workflow data");
assert.ok(sql.includes("v_state='OPEN' and false"),"V70 historical RPC must remain unchanged while V71 replaces it for TEST70");
assert.ok(!html.includes("Accept karein")&&!html.includes("Wapas karein"),"Prototype-only action labels must be removed");
for(const text of ["rr_real_chat_message_bridge_v70","rr_real_chat_receipts_v70","rr_real_chat_notification_links_v70","rr_real_chat_action_registry_v70","RECEIVER_MISMATCH","data_mode = 'TEST'"])assert.ok(bridgeSql.includes(text),`Missing bridge contract: ${text}`);
for(const text of ["rr_real_chat_directory_v71","rr_real_chat_department_membership_v70","KAAJ_BUTTON","HOME_DEPARTMENT","UNIVERSAL_REDZED_STAFF","NAMED_CROSS_DEPARTMENT_STAFF"])assert.ok(membershipSql.includes(text),`Missing department membership contract: ${text}`);
for(const text of ["ALL DEPARTMENTS","WORKER SIDE","REDZED STAFF SIDE","rr_real_chat_directory_v71"])assert.ok(js.includes(text),`Missing department drill-down: ${text}`);
for(const text of ["history.replaceState({view:'inbox'}","view:'department'","view:'chat'","restoreView(e.state)","parentDepartment"])assert.ok(js.includes(text),`Missing nested history restoration: ${text}`);
for(const text of ["set is_active=false","HOME_DEPARTMENT","UNIVERSAL_REDZED_STAFF","NAMED_CROSS_DEPARTMENT_STAFF","upper(coalesce(d.access_status,'ACTIVE'))='ACTIVE'","TEST70_REAL_CHAT_DIRECTORY_V71_RECONCILED"])assert.ok(reconcileSql.includes(text),`Missing reconciled membership rule: ${text}`);
for(const text of ["rr_real_chat_work_inbox_v71","rr_upm_department_colour_due_card_v9109","rr_upm_colour_queue_v741","rr_upm_ready_to_assign_v9107","rr_upm_submit_colours_v741","rr_upm_alter_stage_v740","rr_upm_open_rectification_v9110","rr_upm_set_department_rate_v760","FINAL_SALE_RATE_RRQ","v_role='MANAGER'","v_role='ADMIN'","stage not like 'CLOSED%'"])assert.ok(actionsSql.includes(text),`Missing V71 canonical action contract: ${text}`);
for(const text of ["actionButtons","data-action","department_counts","pageshow","visibilitychange"])assert.ok(js.includes(text),`Missing action lifecycle refresh contract: ${text}`);
assert.ok(actionsSql.includes("coalesce(v_assignment.actual_rate,0)<=0 and v_role='MANAGER'"),"Only Manager gets the departmental rate action");
assert.ok(actionsSql.includes("v_dept in ('PACKING','DISPATCH') and v_role='ADMIN'"),"Only Admin gets Final Sale Rate / RRQ action");
for(const text of ["Product Master","Universal Product Master","Sales","Accounts","Salary & Wages","Real Chat Directory","data-workflow","view:'workflow'"])assert.ok(js.includes(text)||html.includes(text),`Missing full-app menu contract: ${text}`);
for(const text of ["rr_upm_dynamic_submit_history_v741","rr_upm_actions_v726","rr_upm_alter_events_v740","rr_upm_rectification_cases_v9101","rr_real_chat_auto_sync_v71"])assert.ok(historySql.includes(text),`Missing UPM history source: ${text}`);
for(const text of ["rr_cb_art_assignments","rr_cb_print_assignments","rr_cb_sticker_assignments","rr_cb_metal_id_assignments_v801","rr_fg_pi_v787","rr_fg_returns_v787","rr_rci_v9740","rr_rci_accounts_link_v9754","rr_salary_payment_batch_lines_v785","rr_pcs_payment_batch_lines_v784","rr_attendance_day_v778","rr_worker_payroll_profile_events_v777_2"])assert.ok(e2eSql.includes(text),`Missing full backbone source: ${text}`);
assert.ok(e2eSql.includes("source_module in ('ACCOUNTS','MONTHLY_PAYROLL','SALARY_PAYMENT','PCS_PAYROLL','WORKER_PAYROLL','RCI_ACCOUNTS','RRQ')"),"Financial chat sources need a restricted RLS gate");
assert.ok(e2eSql.includes("on conflict(canonical_key) do update"),"Backfill must be idempotent");
for(const text of ["archived_at","SALES_DESPATCH_RECEIVED","ALL_UNIT_LOTS_DESPATCHED","ALL_CB_LOTS_DESPATCHED","rr_fg_despatch_custody_v9361","upper(d.status)='RECEIVED'"])assert.ok(archiveSql.includes(text),`Missing dispatch archive contract: ${text}`);
assert.ok(js.includes(".is('archived_at',null)"),"Archived workflow messages must not render in active chats");
for(const text of ["rr_real_chat_truthful_bridge_v72","new.receiver_user_id:=null","GLOBAL_OWNER_STAFF","HOME_DEPARTMENT_STAFF","NAMED_CROSS_DEPARTMENT_STAFF"])assert.ok(truthfulSql.includes(text),`Missing truthful mapping correction: ${text}`);
assert.ok(!truthfulSql.includes("UNIVERSAL_REDZED_STAFF"),"V72 must not rebuild universal staff fan-out");
assert.ok(js.includes(".range(from,from+pageSize-1)"),"Bridge history must page beyond the Supabase 1000-row response cap");
for(const state of ["REJECTED","VERIFIED","APPROVED","FINALIZED","RECEIVED"])assert.ok(js.includes(state),`Terminal history status missing: ${state}`);
for(const text of ["bindFactoryEdgeSwipe","startX<=24","setFactoryMenu(true)","setFactoryMenu(false)"])assert.ok(js.includes(text),`Missing edge swipe navigation: ${text}`);
for(const text of ["html body.rrSliceReserved{padding-top:0!important}","position:fixed;inset:0;width:100vw","#rrSliceRail{top:44%","width:5px!important","#rrSliceRailTitle{display:none!important}"])assert.ok(html.includes(text),`Missing fullscreen edge-line contract: ${text}`);
for(const text of ["enforceFactoryEdgeLine","setProperty('padding-top','0','important')","btn.textContent=''","Swipe for Main Menu"])assert.ok(js.includes(text),`Missing late global-menu override: ${text}`);
for(const text of ["messageSide(c,kind,participantName,participantId)","message_side:messageSide(c,kind,name,id)","data-side=\"'+side+'\"","work-card.outgoing","work-card.incoming:before","work-card.outgoing:before"])assert.ok(js.includes(text)||html.includes(text),`Missing directional chat bubble contract: ${text}`);
for(const text of ["chatRows(kind,id,participantName)","sameName(p.sender_name,participantName)","sameName(p.receiver_name,participantName)","sender_worker_id","friendlyStatus","की ओर से किया"])assert.ok(js.includes(text),`Missing compact two-way personal chat contract: ${text}`);
for(const text of ["rr_real_chat_two_way_participants_v74","sender_worker_id:=v_sender_worker","receiver_worker_id:=v_receiver_worker","sender_department_code","receiver_department_code","Legacy reconciliation","rr_rc_bridge_select_v70","archived rows stay archived"])assert.ok(twoWaySql.includes(text),`Missing global two-way bridge contract: ${text}`);
assert.ok(!js.includes("Canonical: "),"Technical canonical source must stay hidden from chat cards");
for(const text of ["performed_by_name","on_behalf_of_name","REMAKE_ISSUE","v_sender:=v_lm;v_receiver:=v_cm","DELIVER_TO_KARIGAR","KARIGAR_SUBMIT_GOOD"])assert.ok(behalfSql.includes(text),`Missing on-behalf mapping: ${text}`);
for(const text of ["receiver_name:p.receiver_name","test70-real-chat-live-v70.js?v=83"])assert.ok(js.includes(text)||html.includes(text),`Missing on-behalf UI contract: ${text}`);
console.log("PASS: TEST70 uses canonical OPEN and existing role/state workflow actions.");
