const fs=require('fs'),assert=require('assert');
const legacy=fs.readFileSync('real-chat-active-collection-row-v9779.js','utf8');
const staff=fs.readFileSync('real-chat-active-requirement-row-v9780.js','utf8');
const customer=fs.readFileSync('real-customer-active-collection-row-v9780.js','utf8');
const market=fs.readFileSync('real-web-window-chat-share-v9507.js','utf8');
const page=fs.readFileSync('real-sales-live-chat-v9434.html','utf8');
const customerPage=fs.readFileSync('real-market-share-v9420.html','utf8');
const marketPage=fs.readFileSync('real-web-window-v9329.html','utf8');
const sql=fs.readFileSync('supabase/migrations/20260911133000_test69_active_collection_sticky_v9779.sql','utf8');
for(const token of ['rr_direct_collection_active_v9779','sent_lots','updates','chat_message_id','last_updated_at',"not in('CLOSED','CLOSED_NO_RESPONSE','CANCELLED')",'from public,anon','to authenticated,service_role'])assert.ok(sql.includes(token),`missing backend ${token}`);
for(const token of ['height:46px','compose.before','rrActiveCollectionHidden9779','scrollIntoView','UPDATE ${Number','last_updated_at','chat_message_id'])assert.ok(legacy.includes(token),`missing legacy sticky row ${token}`);
for(const token of ['rrActiveReq9780','height:46px','position:fixed','bottom:66px','rr_chat_requirement_detail_v9508','rrReqCard9508','RZ REQUIREMENT'])assert.ok(staff.includes(token),`missing RedZ Requirement row ${token}`);
for(const token of ['rrCustomerActiveRowCss9780','fsCollectionCard','position:fixed','bottom:66px','RZ COLLECTION','UPDATE $2'])assert.ok(customer.includes(token),`missing customer Collection row ${token}`);
for(const token of ['rr_direct_collection_active_v9779','already in active Collection hidden','rrActiveSent9779','focus_collection','focus_message'])assert.ok(market.includes(token),`missing Market Window rule ${token}`);
assert.ok(market.includes("observe(cards,{childList:true})"),'Market Window must observe only cards');
assert.ok(!market.includes("observe(document.documentElement,{childList:true,subtree:true})"),'Market Window recursive observer freeze must stay removed');
assert.ok(page.includes('real-chat-active-requirement-row-v9780.js?v=9780'),'RedZ chat must load Requirement row');
assert.ok(!page.includes('real-chat-active-collection-row-v9779.js?v=9779'),'RedZ chat must not show customer Collection row');
assert.ok(customerPage.includes('real-customer-active-collection-row-v9780.js?v=9780'),'customer chat must load Collection row');
assert.ok(marketPage.includes('real-web-window-chat-share-v9507.js?v=9780'),'Market Window must cache-bust freeze repair');
console.log('V9780 RedZ Requirement row, customer Collection row and Market Window freeze repair: PASS');
