const fs=require('fs'),assert=require('assert');
const chat=fs.readFileSync('real-chat-active-collection-row-v9779.js','utf8');
const market=fs.readFileSync('real-web-window-chat-share-v9507.js','utf8');
const page=fs.readFileSync('real-sales-live-chat-v9434.html','utf8');
const sql=fs.readFileSync('supabase/migrations/20260911133000_test69_active_collection_sticky_v9779.sql','utf8');
for(const token of ['rr_direct_collection_active_v9779','sent_lots','updates','chat_message_id','last_updated_at',"not in('CLOSED','CLOSED_NO_RESPONSE','CANCELLED')",'from public,anon','to authenticated,service_role'])assert.ok(sql.includes(token),`missing backend ${token}`);
for(const token of ['height:46px','compose.before','rrActiveCollectionHidden9779','scrollIntoView','UPDATE ${Number','last_updated_at','chat_message_id'])assert.ok(chat.includes(token),`missing sticky row ${token}`);
for(const token of ['rr_direct_collection_active_v9779','already in active Collection hidden','rrActiveSent9779','focus_collection','focus_message'])assert.ok(market.includes(token),`missing Market Window rule ${token}`);
assert.ok(page.includes('real-chat-active-collection-row-v9779.js?v=9779'),'staff chat must load compact sticky row');
console.log('V9779 active Collection compact row, exact update focus and sent-lot hiding: PASS');
