"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs");
const html=fs.readFileSync("test70-cb-purchase-real-chat-pilot.html","utf8");
const js=fs.readFileSync("test70-real-chat-live-v70.js","utf8");
const sql=fs.readFileSync("supabase/migrations/20260911150000_test70_real_chat_work_mapping.sql","utf8");
for(const text of ["Real Chat","OPEN","WORKING","CLOSE","TEST · LIVE","Lot Number, Category ya Worker Name","PERSONAL CHAT","test70-real-chat-live-v70.js"])assert.ok(html.includes(text),`Missing UI contract: ${text}`);
for(const text of ["rr_real_chat_work_inbox_v70","UPM_ASSIGNMENT:","rr_upm_work_assignments_v8","rr_upm_current_worker_id_v9112","read_only_mirror","revoke all","grant execute"])assert.ok(sql.includes(text),`Missing backend contract: ${text}`);
for(const text of ["rr_real_chat_work_inbox_v70","LIVE_TEST_MAPPING","databaseWrites:false","Art","Print","Sticker","Metal ID"])assert.ok(js.includes(text),`Missing live adapter contract: ${text}`);
assert.ok(!js.includes("rr_upm_assign_colours")&&!js.includes("rr_upm_submit_colours")&&!js.includes(".insert(")&&!js.includes(".update("),"Read-only slice must not write workflow data");
assert.ok(sql.includes("v_state='OPEN' and false"),"OPEN must fail closed until its exact source is approved");
assert.ok(!html.includes("Accept karein")&&!html.includes("Wapas karein"),"Prototype-only action labels must be removed");
console.log("PASS: TEST70 live canonical UPM mirror is scoped, read-only and fail-closed.");
