const assert=require('assert'),fs=require('fs');
const sql=fs.readFileSync('supabase/migrations/20260909133000_canonical_rci_settlement_v9740.sql','utf8');
const page=fs.readFileSync('real-rci-v9740.html','utf8');
const ui=fs.readFileSync('real-rci-v9740.js','utf8');
const pi=fs.readFileSync('real-pi-specimen-v9514-replace-test.html','utf8');
const addon=fs.readFileSync('real-pi-rci-addon-v9740.js','utf8');
const jpeg=fs.readFileSync('real-ci-rci-settlement-jpeg-v9740.js','utf8');
const inlineSql=fs.readFileSync('supabase/migrations/20260909190000_inline_pi_ci_rci_v9741.sql','utf8');
const searchSql=fs.readFileSync('supabase/migrations/20260909194500_searchable_rci_selectors_v9742.sql','utf8');
const mapSql=fs.readFileSync('supabase/migrations/20260909210000_canonical_customer_sales_lot_map_v9745.sql','utf8');
const triggerSql=fs.readFileSync('supabase/migrations/20260909210050_canonical_customer_sales_map_triggers_v9745.sql','utf8');
const partySearchSql=fs.readFileSync('supabase/migrations/20260909210100_canonical_rci_party_search_v9745.sql','utf8');
assert.match(sql,/rr_rci_category_lots_v9740/);
for(const lot of ['DS-001','FP-001','HD-001','NSB-001','PL-001','PW-001','RN-001','SC-001'])assert.match(sql,new RegExp(lot));
assert.match(sql,/return_type in\('KNOWN','ANONYMOUS','ALTER'\)/);
assert.match(sql,/SOURCE_CI_LINE/);
assert.match(sql,/PARTY_ALL_TIME_AVERAGE/);
assert.match(sql,/after update of status on public\.rr_fg_pi_v787/);
assert.match(sql,/new\.status='CI_FINAL'/);
assert.match(sql,/RCI_REVERSAL/);
assert.doesNotMatch(page,/GOODS RETURN|\bGR\b/i);
assert.doesNotMatch(ui,/GOODS RETURN|\bGR\b/i);
assert.match(page,/GENERATE RCI JPEG/);
assert.match(ui,/\.jpeg/);
assert.match(pi,/real-pi-rci-addon-v9740\.js/);
assert.match(pi,/real-ci-rci-settlement-jpeg-v9740\.js/);
assert.match(addon,/ADD RCI/);
assert.match(addon,/SAME PI \/ CI SETTLEMENT/);
assert.match(addon,/Sales Grand Total/);
assert.match(addon,/Less: RCI Grand Total/);
assert.match(addon,/SAVE & POST LINKED RCI/);
assert.doesNotMatch(addon,/<iframe|real-rci-v9740\.html/);
assert.doesNotMatch(page,/SAVE COMBINED RCI DRAFT/);
assert.doesNotMatch(ui,/RR\.getClient/);
assert.match(inlineSql,/rr_rci_post_linked_final_v9741/);
assert.match(inlineSql,/rr_fg_assert_user_v787/);
assert.match(searchSql,/rr_rci_ci_search_v9742/);
assert.match(page,/id="ciSearch"/);
assert.match(page,/id="sourceSearch"/);
assert.match(page,/id="categorySearch"/);
assert.match(page,/Select customer and invoice/);
assert.match(page,/Add RCI item/);
assert.match(page,/RCI ITEM GRID/);
assert.match(page,/action-card/);
assert.match(page,/@media\(max-width:760px\)/);
assert.match(page,/\.grid>\*\{grid-column:1!important\}/);
assert.match(page,/id="returnableNow"/);
assert.match(page,/id="returnHint"/);
assert.match(ui,/Total Sold:/);
assert.match(ui,/Previous RCI:/);
assert.match(ui,/Returnable now:/);
assert.match(ui,/qty\.max/);
assert.match(mapSql,/rr_customer_sales_map_v9745/);
assert.match(triggerSql,/REDZED_CUSTOMER/);
assert.match(triggerSql,/DISTRIBUTOR_CUSTOMER/);
assert.match(partySearchSql,/rr_rci_ci_search_v9745/);
assert.match(partySearchSql,/left join public\.rr_fg_pi_v787/);
assert.match(ui,/rr_rci_ci_search_v9745/);
assert.match(ui,/NO FINAL CI \/ NO RETURNABLE SALE/);
assert.match(addon,/rrPiWaBox/);
assert.match(addon,/insertBefore\(b,stack\)/);
assert.match(addon,/id="rrRciToggle9741"[^>]+disabled/);
assert.match(addon,/rrRciSourceSearch9741/);
assert.match(addon,/rrRciCategorySearch9741/);
assert.match(addon,/rrRciReturnable9744/);
assert.match(addon,/rrRciHint9744/);
assert.match(addon,/Maximum \$\{left\} PCS/);
assert.match(jpeg,/RCI GRAND TOTAL/);
assert.match(jpeg,/NET SETTLEMENT/);
console.log('PASS canonical RCI V9742: searchable selectors, visible post-save RCI activation, inline PI/CI settlement and standalone RCI.');
