const assert=require('assert'),fs=require('fs');
const sql=fs.readFileSync('supabase/migrations/20260909133000_canonical_rci_settlement_v9740.sql','utf8');
const page=fs.readFileSync('real-rci-v9740.html','utf8');
const ui=fs.readFileSync('real-rci-v9740.js','utf8');
const pi=fs.readFileSync('real-pi-specimen-v9514-replace-test.html','utf8');
const addon=fs.readFileSync('real-pi-rci-addon-v9740.js','utf8');
const jpeg=fs.readFileSync('real-ci-rci-settlement-jpeg-v9740.js','utf8');
assert.match(sql,/rr_rci_category_lots_v9740/);
for(const lot of ['DS-001','FP-001','HD-001','NSB-001','PL-001','PW-001','RN-001','SC-001'])assert.match(sql,new RegExp(lot));
assert.match(sql,/return_type in\('KNOWN','ANONYMOUS','ALTER'\)/);
assert.match(sql,/SOURCE_CI_LINE/);
assert.match(sql,/PARTY_ALL_TIME_AVERAGE/);
assert.match(sql,/after update of status on public\.rr_fg_pi_v787/);
assert.match(sql,/new\.status='CI_FINAL'/);
assert.match(sql,/RCI_REVERSAL/);
assert.doesNotMatch(page,/GOODS RETURN|\bGR\b/i);
assert.doesNotMatch(ui,/GOODS RETURN|\bGR\b/i);
assert.match(page,/GENERATE RCI JPEG/);
assert.match(ui,/\.jpeg/);
assert.match(pi,/real-pi-rci-addon-v9740\.js/);
assert.match(pi,/real-ci-rci-settlement-jpeg-v9740\.js/);
assert.match(addon,/ADD RCI/);
assert.match(jpeg,/RCI GRAND TOTAL/);
assert.match(jpeg,/NET SETTLEMENT/);
console.log('PASS canonical RCI V9740: fixed lots, combined CI+RCI, standalone RCI, reversal, JPEG and terminology.');
