const {test}=require('node:test');const assert=require('node:assert/strict');const {JSDOM}=require('jsdom');const fs=require('node:fs');const tick=()=>new Promise(r=>setTimeout(r,10));
function env(handler){const d=new JSDOM('<body><button id="callBtn">CALL</button></body>',{url:'https://example.test/chat',runScripts:'outside-only',pretendToBeVisual:true}),w=d.window,requests=[],tracks=[];let interval;
w.setInterval=(fn,ms)=>{if(ms===1000)interval=fn;return 1};w.clearInterval=()=>{};w.HTMLMediaElement.prototype.pause=()=>{};w.HTMLMediaElement.prototype.play=async()=>{};
w.RF853={rpc:async(n,a)=>{requests.push(a);return handler(a)}};w.RRActiveSalesChat71=()=> 'chat-a';
w.RTCPeerConnection=class{constructor(){this.remoteDescription=null;}addTrack(){}async createOffer(){return {type:'offer',sdp:'offer'}}async createAnswer(){return {type:'answer',sdp:'answer'}}async setLocalDescription(x){this.localDescription={...x,toJSON:()=>x}}async setRemoteDescription(x){this.remoteDescription=x}async addIceCandidate(x){assert.ok(this.remoteDescription,'ICE waits for SDP')}close(){}};
Object.defineProperty(w.navigator,'mediaDevices',{value:{getUserMedia:async()=>{const t={stop:()=>t.stopped=true};tracks.push(t);return {getTracks:()=>[t],getAudioTracks:()=>[t]}}}});
w.eval(fs.readFileSync('test71-sim-internet-call.js','utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));return {d,w,requests,tracks,poll:()=>interval?.()};}
test('SIM option opens tel link and never starts WebRTC or microphone',async()=>{const e=env(a=>a.p_action==='CONTACTS'?[{name:'Member',profile_id:'p'}]:a.p_action==='DIAL'?{mobile:'9876543210'}:[]);try{await e.w.RRCalls71.contacts();e.w.document.querySelector('[data-sim]').click();await tick();assert.equal(e.w.document.querySelector('a').getAttribute('href'),'tel:+919876543210');assert.equal(e.tracks.length,0);assert.ok(!e.requests.some(a=>a.p_action==='START'));}finally{e.d.window.close()}});
test('offer and early ICE wait for Answer; double Answer creates one microphone',async()=>{let delivered=false;const e=env(a=>{if(a.p_action==='INCOMING')return [{call_id:'call-a',caller_name:'Member'}];if(a.p_action==='POLL'){if(delivered)return [];delivered=true;return [{id:1,type:'ICE',payload:{candidate:'early'}},{id:2,type:'OFFER',payload:{type:'offer',sdp:'offer'}}]};return {ok:true}});try{await tick();assert.equal(e.tracks.length,0);assert.ok(!e.requests.some(a=>a.p_signal_type==='ANSWER'));const b=e.w.document.getElementById('rrCallAnswer71');b.click();b.click();await tick();assert.equal(e.tracks.length,1);assert.equal(e.requests.filter(a=>a.p_signal_type==='ANSWER').length,1);await e.w.RRCalls71.end(true);await tick();assert.equal(e.tracks[0].stopped,true);assert.equal(e.requests.filter(a=>a.p_signal_type==='HANGUP').length,1);}finally{e.d.window.close()}});
test('double outgoing tap makes one call and cleanup stops audio',async()=>{const e=env(a=>a.p_action==='CONTACTS'?[{name:'Member',profile_id:'p'}]:a.p_action==='START'?{call_id:'call-a'}:[]);try{await e.w.RRCalls71.contacts();const b=e.w.document.querySelector('[data-net]');b.click();b.click();await tick();assert.equal(e.requests.filter(a=>a.p_action==='START').length,1);await e.w.RRCalls71.end(true);assert.equal(e.tracks[0].stopped,true);}finally{e.d.window.close()}});
test('closing during microphone permission prevents late call start',async()=>{const e=env(a=>a.p_action==='CONTACTS'?[{name:'Member',profile_id:'p'}]:[]);let resolve;let stopped=false;e.w.navigator.mediaDevices.getUserMedia=()=>new Promise(r=>resolve=r);try{await e.w.RRCalls71.contacts();e.w.document.querySelector('[data-net]').click();await e.w.RRCalls71.end(true);resolve({getTracks:()=>[{stop:()=>stopped=true}]});await tick();assert.equal(stopped,true);assert.ok(!e.requests.some(a=>a.p_action==='START'));}finally{e.d.window.close()}});
