const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const source=fs.readFileSync('real-customer-chat-collection-card-v9605.js','utf8'),state=fs.readFileSync('real-customer-requirement-state-v9641.js','utf8');
const handlers={};const api=new Function('document',source.slice(source.indexOf('function stockLimit('),source.indexOf('function card('))+'bindQuantity();return {stockLimit,clampQuantity};')({addEventListener:(name,fn)=>handlers[name]=fn});
function input(value,max=18){return{value,dataset:max==null?{}:{fcMax:String(max)},matches:()=>true,select(){this.selected=true}}}
test('zero clears on focus and a positive quantity can be typed',()=>{const el=input('0');handlers.focusin({target:el});assert.equal(el.value,'');el.value='12';handlers.input({target:el});assert.equal(el.value,'12');assert.equal(el.dataset.rrQtyDirty71,'1')});
test('typing or pasting above available pieces clamps to stock',()=>{const el=input('999');handlers.input({target:el});assert.equal(el.value,'18');el.value='0';assert.equal(api.clampQuantity(el),0);el.dataset.fcMax='0';el.value='12';assert.equal(api.clampQuantity(el),0)});
test('saved quantities select for replacement and an empty blur returns zero',()=>{const el=input('12');handlers.focusin({target:el});assert.equal(el.selected,true);el.value='';handlers.input({target:el});assert.equal(el.value,'');handlers.focusout({target:el});assert.equal(el.value,'0')});
test('late prefill does not overwrite a customer edit or focused zero',()=>{const fn=new Function('document','saved','paintCards','let draftReady=false,panelOpening=true;'+state.slice(state.indexOf('function prefillOnce('),state.indexOf('async function openPrefilled('))+'return prefillOnce;');const el=input('12');el.dataset.fcq='LOT';el.dataset.rrQtyDirty71='1';fn({querySelectorAll:()=>[el]},new Map([['LOT',0]]),()=>{})();assert.equal(el.value,'12')});
test('stock limits come from available pieces; submission clamps again',()=>{assert.equal(api.stockLimit({available_qty:18.5}),18);assert.equal(api.stockLimit({available_qty:0}),0);assert.equal(api.stockLimit({}),null);assert.ok(source.includes('let q=el?clampQuantity(el):0'))});
