const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const src=fs.readFileSync('real-customer-fullscreen-secure-chat-v9648.js','utf8');
const factory=new Function('s',"const $=id=>s.nodes[id],document=s.document,paint=a=>s.paints.push(a),ctx=async()=>({t:'secure',d:'device',relation:'DIRECT_CUSTOMER'}),rpc=(n,args)=>new Promise((resolve,reject)=>s.requests.push({n,args,resolve,reject})),setTimeout=fn=>(s.timers.push(fn),s.timers.length),clearTimeout=()=>{};let ch='GROUP',loadSeq=0,loadJob=null,receiptSession=null,prefetch={GROUP:null,SUPERADMIN_PRIVATE:null},prefetchAt={GROUP:0,SUPERADMIN_PRIVATE:0};"+src.slice(src.indexOf('async function fetchChannel('),src.indexOf('async function prewarm('))+src.slice(src.indexOf('function refreshState('),src.indexOf('async function send('))+"return {load,switchTo:()=>{ch='SUPERADMIN_PRIVATE';loadSeq++;loadJob=null},cache:()=>{prefetch.GROUP=[{id:'kept'}];prefetchAt.GROUP=Date.now()},close:()=>{loadSeq++;loadJob=null;s.open=false}};");
function fixture(){const s={open:true,nodes:{fsRefresh:{setAttribute(){}},fsMsgs:{innerHTML:'',scrollTop:44},fsInput:{value:'draft'},rrFSChat:{classList:{contains:()=>s.open}}},document:{hidden:false},paints:[],requests:[],timers:[]};return Object.assign(s,factory(s))}
const flush=async()=>{for(let i=0;i<10;i++)await Promise.resolve()};
test('refresh coalesces repeated taps and preserves draft and scroll',async()=>{const s=fixture(),p=s.load(true);assert.equal(p,s.load(true));await flush();assert.equal(s.requests.length,1);s.requests[0].resolve([{id:2},{id:1}]);await p;assert.equal(s.paints[0][0].id,1);assert.equal(s.nodes.fsRefresh.disabled,false);assert.equal(s.nodes.fsInput.value,'draft');assert.equal(s.nodes.fsMsgs.scrollTop,44)});
test('late group response cannot paint over private channel',async()=>{const s=fixture(),a=s.load(true);await flush();s.switchTo();const b=s.load(true);await flush();s.requests[1].resolve([{id:'private'}]);await b;s.requests[0].resolve([{id:'group'}]);await a;assert.equal(s.paints.length,1);assert.equal(s.paints[0][0].id,'private')});
test('timeout unlocks Retry and late response cannot overwrite retry',async()=>{const s=fixture(),a=s.load(true);await flush();s.timers[0]();await a;assert.equal(s.nodes.fsRefresh.textContent,'↻ Retry');assert.equal(s.nodes.fsRefresh.disabled,false);const b=s.load(true);await flush();s.requests[1].resolve([{id:'new'}]);await b;s.requests[0].resolve([{id:'old'}]);await flush();assert.equal(s.paints.length,1);assert.equal(s.paints[0][0].id,'new')});
test('offline retains cached chat and hidden polling pauses',async()=>{const s=fixture();s.cache();const a=s.load(true);await flush();s.requests[0].reject(Error('offline'));await a;assert.equal(s.paints[0][0].id,'kept');assert.equal(s.nodes.fsMsgs.innerHTML,'');s.document.hidden=true;await s.load();assert.equal(s.requests.length,1)});
test('closed chat ignores late response',async()=>{const s=fixture(),a=s.load(true);await flush();s.close();s.requests[0].resolve([{id:'late'}]);await a;assert.equal(s.paints.length,0)});
