const {test}=require('node:test');
const assert=require('node:assert/strict');
const {readFileSync}=require('node:fs');
const {webcrypto}=require('node:crypto');
const {JSDOM}=require('jsdom');
const {createCanvas}=require('@napi-rs/canvas');
const source=readFileSync('redzed-store/test71-readymade-receipt-share.js','utf8');
const fixture={status:'POSTED',purchase_id:'purchase-1',purchase_no:'RM-1',bill_no:'B1',supplier_name:'Supplier',purchase_date:'2026-10-06',prepared_at:'2026-10-06T12:00:00Z',bill_value:81000,received_value:79500,lines:[{lot_no:'L1',art_no:'A1',item_name:'Shirt',category:'Shirts',size_text:'M',colours_text:'Blue',bill_qty:540,received_qty:530,purchase_rate:150,difference_qty:-10,note_type:'DEBIT_NOTE',note_amount:1500,voucher_no:'DN1',bill_value:81000,received_value:79500}]};
function env(){const d=new JSDOM('<div id="modal"><div data-message></div><footer data-footer></footer></div>',{runScripts:'outside-only',url:'https://example.com/test70-cb-purchase-real-chat-pilot.html'}),w=d.window;Object.defineProperty(w,'crypto',{value:webcrypto});w.Blob=Blob;w.File=File;w.AbortSignal=AbortSignal;w.URL.createObjectURL=()=> 'blob:receipt';w.URL.revokeObjectURL=()=>{};const labels=[];w.HTMLCanvasElement.prototype.getContext=function(){this.real=createCanvas(this.width,this.height);const c=this.real.getContext('2d'),fill=c.fillText.bind(c);c.fillText=(s,...a)=>{labels.push(s);fill(s,...a)};return c};w.HTMLCanvasElement.prototype.toBlob=function(cb){cb(new Blob([this.real.toBuffer('image/jpeg')],{type:'image/jpeg'}))};w.HTMLCanvasElement.prototype.toDataURL=function(type){return this.real.toDataURL(type)};w.eval(source);return{w,d,labels}}
const tick=()=>new Promise(r=>setTimeout(r,10));
async function ready(e,{failRecord=false}={}){const blob=new Blob(['saved JPG'],{type:'image/jpeg'}),hash=Buffer.from(await webcrypto.subtle.digest('SHA-256',await blob.arrayBuffer())).toString('hex');const calls=[];let upload=0;const receipt={...fixture,files:[{name:'receipt.jpg',path:'saved.jpg',sha256:hash}]};e.w.fetch=async()=>({ok:true,blob:async()=>blob});const ctx={s:{db:{storage:{from:()=>({upload:async()=>{upload++;return{}},getPublicUrl:()=>({data:{publicUrl:'https://test/saved.jpg'}})})}}},rpc:async(n,p)=>{calls.push([n,p]);if(n.includes('share_record')&&failRecord){failRecord=false;throw Error('temporary')}return receipt}};const modal=e.w.document.querySelector('#modal');modal.addEventListener('click',ev=>{if(ev.target.tagName==='A')ev.preventDefault()});e.w.RRReadymadeReceipt71.attach(ctx,modal,receipt);for(let i=0;i<100&&modal.querySelector('[data-share-jpg]').disabled;i++)await tick();assert.equal(modal.querySelector('[data-share-jpg]').disabled,false,modal.querySelector('[data-message]').textContent);return{ctx,modal,calls,get upload(){return upload}}}
test('Rendered and synchronous Proforma note are genuine downloadable JPEG images',async()=>{const e=env();const old=await e.w.RRReadymadeReceipt71.render(fixture),pack=e.w.RRReadymadeReceipt71.proforma(fixture);for(const f of [old[0],pack.files[0]]){assert.equal(f.type,'image/jpeg');assert.match(f.name,/Proforma-DR-CR-Note/);const bytes=Buffer.from(await f.arrayBuffer());assert.equal(bytes.subarray(0,2).toString('hex'),'ffd8');assert.ok(bytes.length>10000)}for(const value of ['PROFORMA DR/CR NOTE','540 PCS','530 PCS','1,500','79,500'])assert.ok(e.labels.join('\n').includes(value),value);e.w.close()});
test('Share starts synchronously with image only and no policy or link detour',async()=>{const e=env();const pack=e.w.RRReadymadeReceipt71.proforma(fixture);let payload;e.w.document.permissionsPolicy={allowsFeature:()=>false};e.w.navigator.canShare=()=>false;e.w.navigator.share=p=>{payload=p;return Promise.resolve()};const done=e.w.RRReadymadeReceipt71.shareNow(pack.files,pack.png);assert.equal(payload.files[0].type,'image/png');assert.equal(payload.title,'Proforma DR/CR Note');assert.ok(!payload.url&&!payload.text);assert.equal((await done).shared,true);e.w.close()});
test('CB-compatible PNG image fallback retains JPG download and never shares a link',async()=>{const e=env(),pack=e.w.RRReadymadeReceipt71.proforma(fixture);let payload;e.w.navigator.canShare=p=>p.files[0].type==='image/png';e.w.navigator.share=p=>{payload=p;return Promise.resolve()};await e.w.RRReadymadeReceipt71.shareNow(pack.files,pack.png);assert.equal(payload.files[0].type,'image/png');assert.equal(pack.files[0].type,'image/jpeg');assert.ok(!payload.url);e.w.close()});
test('Cancellation is not a handoff and unsupported API never sends text/link',async()=>{const e=env(),pack=e.w.RRReadymadeReceipt71.proforma(fixture);assert.throws(()=>e.w.RRReadymadeReceipt71.shareNow(pack.files),/image picker/);e.w.navigator.share=()=>Promise.reject(Object.assign(Error(),{name:'AbortError'}));const result=await e.w.RRReadymadeReceipt71.shareNow(pack.files);assert.equal(result.shared,false);assert.equal(result.error,null);e.w.close()});
test('Saved receipt panel offers one image send button and saveable JPG with no WhatsApp link prompts',async()=>{const e=env(),r=await ready(e);assert.equal(r.modal.querySelectorAll('[data-share-jpg]').length,1);assert.equal(r.modal.querySelectorAll('a:not([download])').length,0);assert.equal(r.modal.querySelector('[data-share-jpg]').textContent,'Save & Send · Proforma DR/CR Note');assert.match(r.modal.querySelector('a[download]').download,/Proforma-DR-CR-Note/);e.w.close()});
