'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {JSDOM}=require('jsdom');const fs=require('node:fs');const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../../real-pi-customer-receipt-test71.js'),'utf8');
function setup(rpc){const d=new JSDOM('',{url:'https://example.test/real-pi-specimen-v9514.html',runScripts:'outside-only'});const drawn=[],images=[];const painter={fillRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},measureText:s=>({width:String(s).length*12}),fillText:(s)=>drawn.push(s)};d.window.HTMLCanvasElement.prototype.getContext=()=>painter;d.window.HTMLCanvasElement.prototype.toDataURL=function(type){images.push({type,width:this.width,height:this.height});return 'data:image/jpeg;base64,/9j/2Q==';};d.window.RF853={rpc};d.window.eval(source);return {d,drawn,images};}
const documentData={pi_id:'pi-a',document_kind:'PI',document_no:'26/101',customer_name:'Party A',dispatch_details:'Truck A',lines:[{lot_no:'N1',item_name:'SHIRT',qty:36,gross_rate:100,discount:5,net_rate:95,amount:3420}],total_qty:36,sub_total:3420,value_added_pct:-1,value_added_amount:-34.2,freight_amount:300,other_charges:50,gst_amount:0,round_off:4.2,grand_total:3740,internal_rrq:'DO NOT SEND',godown:'DO NOT SEND'};
test('saved canonical details produce customer JPG and send to returned exact party chat',async()=>{const calls=[];const s=setup(async(n,a)=>{calls.push({n,a});return n==='rr_pi_customer_document_test71'?{chat_id:'party-a',fingerprint:'saved-hash',document:documentData}:{sent:true};});try{const r=await s.d.window.RRPIReceipt71.send('pi-a','party-a');assert.ok(r.sent);assert.equal(calls.length,2);assert.equal(calls[1].a.p_chat_id,'party-a');assert.equal(calls[1].a.p_fingerprint,'saved-hash');assert.equal(calls[1].a.p_pages.length,1);assert.ok(s.drawn.includes('26/101'));assert.ok(s.drawn.includes('Value Added (-1%)'));assert.ok(s.drawn.includes('₹3,740'));assert.ok(!s.drawn.includes('DO NOT SEND'));assert.equal(s.images[0].type,'image/jpeg');}finally{s.d.window.close()}});
test('already delivered snapshot skips both JPG generation and another send request',async()=>{let calls=0;const s=setup(async()=>{calls++;return {already_sent:true,message_ids:['message']};});try{const r=await s.d.window.RRPIReceipt71.send('pi-a','party-a');assert.ok(r.already_sent);assert.equal(calls,1);assert.equal(s.images.length,0);}finally{s.d.window.close()}});
test('long invoice creates all JPG pages in one atomic send request',async()=>{const lines=Array.from({length:37},(_,i)=>({...documentData.lines[0],lot_no:'N'+(i+1)}));let sent;const s=setup(async(n,a)=>n==='rr_pi_customer_document_test71'?{chat_id:'party-a',fingerprint:'hash',document:{...documentData,lines}}:(sent=a,{sent:true}));try{await s.d.window.RRPIReceipt71.send('pi-a');assert.equal(sent.p_pages.length,3);assert.ok(s.drawn.includes('N37'));assert.ok(s.drawn.includes('Page 3 / 3'));assert.equal(s.drawn.filter(x=>x==='TOTAL').length,1);}finally{s.d.window.close()}});
test('JPEG rendering failure never sends an incomplete attachment message',async()=>{let calls=0;const s=setup(async()=>{calls++;return {chat_id:'party-a',fingerprint:'hash',document:documentData};});try{s.d.window.HTMLCanvasElement.prototype.getContext=()=>null;await assert.rejects(s.d.window.RRPIReceipt71.send('pi-a'),/could not be generated/);assert.equal(calls,1);}finally{s.d.window.close()}});
