const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),{JSDOM}=require('jsdom');
test('slow or failed Sales queue cannot hide Customer Chats; Retry recovers cards',async()=>{const src=fs.readFileSync('test70-real-chat-live-v70.js','utf8'),start=src.indexOf('async function openCommercialChat('),fn=src.slice(start,src.indexOf('\n',start)),d=new JSDOM('<div id="chatName"></div><div id="kind"></div><button id="manageStaffAction"></button><div id="contextAction"></div><div id="searchNotice"></div><div id="messages"></div><div id="inbox"></div><div id="chat"></div>',{runScripts:'outside-only'}),w=d.window;try{w.S={status:'OPEN',chatSeq:0,search:''};w.$=id=>w.document.getElementById(id);for(const n of ['commercialCss','clearRateFocusGuard','syncStatusButtons','syncWorkFilters','pushCurrentView'])w[n]=()=>{};w.membershipAdminRole=()=>true;w.arr=x=>x||[];w.emptyStateV705=()=>'<div>Recovered</div>';w.safe=x=>x;w.err=e=>e.message;w.console.warn=()=>{};let reject;w.rpc=()=>new Promise((yes,no)=>reject=no);w.eval(fn+';window.openCommercialChat=openCommercialChat');const waiting=w.openCommercialChat('SALES','Sales',false);assert.ok(w.document.querySelector('[data-sales-chat-list]'),'entry must appear before query resolves');reject(Error('canceling statement due to statement timeout'));await waiting;assert.ok(w.document.querySelector('[data-sales-chat-list]'));assert.ok(w.document.getElementById('rrSalesRetry71'));assert.doesNotMatch(w.document.getElementById('messages').textContent,/statement timeout/);w.rpc=async()=>({cards:[]});w.document.getElementById('rrSalesRetry71').click();await new Promise(r=>setTimeout(r,5));assert.match(w.document.getElementById('messages').textContent,/Recovered/);}finally{w.close()}});
test('Sales OPEN and WORKING both expose the same customer inbox even with no workflow cards',async()=>{const src=fs.readFileSync('test70-real-chat-live-v70.js','utf8'),start=src.indexOf('async function openCommercialChat('),fn=src.slice(start,src.indexOf('\n',start));for(const status of ['OPEN','WORKING']){const d=new JSDOM('<div id="chatName"></div><div id="kind"></div><button id="manageStaffAction"></button><div id="contextAction"></div><div id="searchNotice"></div><div id="messages"></div><div id="inbox"></div><div id="chat"></div>',{runScripts:'outside-only'}),w=d.window;try{w.S={status,chatSeq:0,search:''};w.$=id=>w.document.getElementById(id);for(const name of ['commercialCss','clearRateFocusGuard','syncStatusButtons','syncWorkFilters','pushCurrentView'])w[name]=()=>{};w.membershipAdminRole=()=>true;w.rpc=async()=>({cards:[]});w.arr=x=>x||[];w.emptyStateV705=()=>'<div>No cards</div>';w.safe=x=>x;w.err=e=>e.message;w.eval(fn+';window.openCommercialChat=openCommercialChat');await w.openCommercialChat('SALES','Sales',false);const a=w.document.querySelector('[data-sales-chat-list]');assert.ok(a,status);assert.equal(new URL(a.href,'https://example.test').searchParams.get('inbox'),'1');assert.match(w.document.getElementById('messages').textContent,/No cards/);}finally{w.close()}}});
test('all customer list is accessible from a conversation, keeps identity and supports name/mobile search',async()=>{const d=new JSDOM('<div id="inbox" class="hide"><div class="head"></div><div id="inboxRows"><div class="chatrow" data-chat="lukman" data-customer-name="Lukman Sales" data-mobile="9679749124">Lukman Sales</div><div class="chatrow" data-chat="avni" data-customer-name="Avnimycutie" data-mobile="9991112222">Avnimycutie</div></div></div><div class="chathead"></div><div id="rrChatLocalPanel"><div class="rrChatLocalHead"></div></div><div id="rrChatLocalBack" class="open"></div>',{url:'https://example.test/real-sales-live-chat-v9434.html?chat_id=lukman&followup=1&collection_cycle_id=cycle',runScripts:'outside-only'}),w=d.window;try{let lists=0;w.RRSalesChatActions71={showInbox:()=>lists++,refreshInbox:()=>{}};w.eval(fs.readFileSync('real-sales-customer-inbox-test71.js','utf8'));assert.equal(w.document.getElementById('rrCustomerChatCount71').textContent,'2 chats');const input=w.document.getElementById('rrCustomerChatSearch71');input.value='967974';input.dispatchEvent(new w.Event('input'));assert.equal(w.document.querySelector('[data-chat="avni"]').style.display,'none');assert.equal(w.document.querySelector('[data-chat="lukman"]').style.display,'');w.document.getElementById('rrAllCustomerChats71').click();assert.equal(lists,1);assert.equal(w.document.getElementById('inbox').classList.contains('hide'),false);assert.equal(new URL(w.location.href).searchParams.get('chat_id'),null);assert.equal(new URL(w.location.href).searchParams.get('collection_cycle_id'),null);assert.equal(w.location.hash,'#rr-inbox');assert.equal(input.value,'');assert.ok(w.document.getElementById('rrCustomerChatsMenu71'));await new Promise(r=>setTimeout(r,10));assert.equal(w.document.querySelectorAll('#rrAllCustomerChats71').length,1);w.dispatchEvent(new w.Event('pagehide'));}finally{w.close()}});
test('inbox module leaves distributor private lane unchanged',()=>{const d=new JSDOM('<div id="inbox"></div>',{runScripts:'outside-only'});try{d.window.__RR_PARTNER_STAFF_CHAT_ADAPTER_V82__=true;d.window.eval(fs.readFileSync('real-sales-customer-inbox-test71.js','utf8'));assert.equal(d.window.RRSalesCustomerInbox71,undefined);}finally{d.window.close()}});

test('Sales boot accepts notification chat alias and canonical chat_id, with exact customer precedence',async()=>{
 const src=fs.readFileSync('real-sales-live-chat-v9434.js','utf8'),start=src.lastIndexOf('(async()=>{try{await auth();await loadInbox();'),end=src.indexOf('})()',start)+4;assert.ok(start>0&&end>start);
 for(const [search,wanted]of [['?chat=push-b','push-b'],['?chat_id=canonical-a','canonical-a'],['?chat=push-b&chat_id=canonical-a','canonical-a'],['?inbox=1',null]]){
  const opened=[],environment={location:{search},URLSearchParams,auth:async()=>{},loadInbox:async()=>{},inbox:[{chat_id:'canonical-a'},{chat_id:'push-b'}],openChat:async row=>opened.push(row.chat_id),$:()=>({style:{}}),flash:()=>{},esc:x=>x};require('node:vm').runInNewContext(src.slice(start,end),environment);await new Promise(setImmediate);assert.deepEqual(opened,wanted?[wanted]:[]);
 }
});
