const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const {JSDOM}=require('jsdom');
async function setup(role='OWNER'){
 const dom=new JSDOM('<body></body>',{url:'https://example.com/test70-cb-purchase-real-chat-pilot.html'}),w=dom.window,calls=[],location={href:w.location.href,pathname:w.location.pathname,search:'',reload(){}};
 const db={auth:{getSession:async()=>({data:{session:{user:{id:'owner'}}}})},from(table){const result={data:table==='rr_user_profiles'?{full_name:'Owner',role_code:role,is_active:true}:[]};const b={};for(const k of ['select','eq','order','in','maybeSingle'])b[k]=()=>b;b.then=(yes,no)=>Promise.resolve(result).then(yes,no);return b;},rpc:async(name,args)=>{calls.push({name,args});return {data:name==='rr_test_customer_source_test71'?[{customer_id:'C',customer_name:'Buyer One',has_collection:true},{customer_id:'D',customer_name:'Buyer Two',has_collection:false}]:name==='rr_test_act_as_customer_test71'?{session_token:'bound',share_token:'share',data_mode:'TEST'}:name==='rr_real_chat_directory_v600'?{departments:[]}:{}};}};
 const context={window:w,document:w.document,sessionStorage:w.sessionStorage,localStorage:w.localStorage,location,URL,URLSearchParams,Map,Set,crypto:{randomUUID:()=> 'device'},setTimeout,console};w.supabaseClient=db;
 vm.runInNewContext(fs.readFileSync('real-superadmin-view-as-v176.js','utf8'),context);w.document.dispatchEvent(new w.Event('DOMContentLoaded'));for(let i=0;i<5;i++)await new Promise(setImmediate);return {dom,w,location,calls,context};
}
test('Owner has separate searchable existing Customers block and opens bound TEST customer collection',async()=>{const x=await setup();try{const d=x.w.document;assert.equal(d.querySelector('details summary').textContent,'CUSTOMERS · TEST');assert.equal(d.querySelector('details').open,true);assert.equal(d.querySelector('[data-actual]').nextElementSibling.tagName,'DETAILS');const buttons=d.querySelectorAll('[data-customer-list] button');assert.equal(buttons.length,2);assert.equal(buttons[1].disabled,true);d.querySelector('[data-customer-search]').value='One';d.querySelector('[data-customer-search]').oninput();assert.equal(d.querySelectorAll('[data-customer-list] button').length,1);d.querySelector('[data-customer-list] button').click();for(let i=0;i<5;i++)await new Promise(setImmediate);assert.equal(new URL(x.location.href).pathname,'/s.html');assert.equal(new URL(x.location.href).searchParams.get('t'),'share');assert.equal(JSON.parse(x.w.localStorage.getItem('rr_customer_secure_session_v9592')).session_token,'bound');assert.ok(x.calls.some(c=>c.name==='rr_test_clear_on_behalf_context_v176'));assert.ok(!x.calls.some(c=>c.name==='rr_test_set_on_behalf_context_v176'));}finally{x.dom.window.close()}});
test('Admin cannot mount customer Act As',async()=>{const x=await setup('ADMIN');try{assert.equal(x.w.document.getElementById('rrGlobalViewAs172'),null);assert.ok(!x.calls.some(c=>c.name==='rr_test_customer_source_test71'));}finally{x.dom.window.close()}});
test('Customer preview visibly identifies TEST and returns to actual owner',()=>{const dom=new JSDOM('<body></body>',{url:'https://example.com/s.html?t=share'}),w=dom.window,location={href:w.location.href,origin:w.location.origin};w.sessionStorage.setItem('rr_test_customer_preview71',JSON.stringify({name:'Buyer One',return_url:'https://example.com/test70-cb-purchase-real-chat-pilot.html'}));try{vm.runInNewContext(fs.readFileSync('test71-customer-preview-banner.js','utf8'),{document:w.document,sessionStorage:w.sessionStorage,location,URL});assert.match(w.document.body.textContent,/ACT AS CUSTOMER · TEST · Buyer One/);w.document.querySelector('button').click();assert.equal(w.sessionStorage.getItem('rr_test_customer_preview71'),null);assert.match(location.href,/test70-cb-purchase/);}finally{w.close()}});
