const {test}=require('node:test');
const assert=require('node:assert/strict');
const {readFileSync}=require('node:fs');
const {webcrypto}=require('node:crypto');
const {JSDOM}=require('jsdom');
const {createCanvas}=require('@napi-rs/canvas');
const source=readFileSync('redzed-store/test71-readymade-receipt-share.js','utf8');
const fixture={status:'POSTED',purchase_id:'purchase-1',purchase_no:'RM-1',bill_no:'B1',supplier_name:'Supplier',purchase_date:'2026-10-06',prepared_at:'2026-10-06T12:00:00Z',bill_value:81000,received_value:79500,lines:[{lot_no:'L1',art_no:'A1',item_name:'Shirt',category:'Shirts',size_text:'M',colours_text:'Blue',bill_qty:540,received_qty:530,purchase_rate:150,difference_qty:-10,note_type:'DEBIT_NOTE',note_amount:1500,voucher_no:'DN1',bill_value:81000,received_value:79500}]};
function env(){const d=new JSDOM('<div id="modal"><div data-message></div><footer data-footer></footer></div>',{runScripts:'outside-only',url:'https://example.com/test70-cb-purchase-real-chat-pilot.html'}),w=d.window;Object.defineProperty(w,'crypto',{value:webcrypto});w.Blob=Blob;w.File=File;w.AbortSignal=AbortSignal;w.URL.createObjectURL=()=> 'blob:receipt';w.URL.revokeObjectURL=()=>{};const labels=[];w.HTMLCanvasElement.prototype.getContext=function(){this.real=createCanvas(this.width,this.height);const c=this.real.getContext('2d'),fill=c.fillText.bind(c);c.fillText=(s,...a)=>{labels.push(s);fill(s,...a)};return c};w.HTMLCanvasElement.prototype.toBlob=function(cb){cb(new Blob([this.real.toBuffer('image/jpeg')],{type:'image/jpeg'}))};w.eval(source);return{w,d,labels}}
const tick=()=>new Promise(r=>setTimeout(r,10));
async function ready(e,{failRecord=false}={}){const blob=new Blob(['saved JPG'],{type:'image/jpeg'}),hash=Buffer.from(await webcrypto.subtle.digest('SHA-256',await blob.arrayBuffer())).toString('hex');const calls=[];let upload=0;const receipt={...fixture,files:[{name:'receipt.jpg',path:'saved.jpg',sha256:hash}]};e.w.fetch=async()=>({ok:true,blob:async()=>blob});const ctx={s:{db:{storage:{from:()=>({upload:async()=>{upload++;return{}},getPublicUrl:()=>({data:{publicUrl:'https://test/saved.jpg'}})})}}},rpc:async(n,p)=>{calls.push([n,p]);if(n.includes('share_record')&&failRecord){failRecord=false;throw Error('temporary')}return receipt}};const modal=e.w.document.querySelector('#modal');modal.addEventListener('click',ev=>{if(ev.target.tagName==='A')ev.preventDefault()});e.w.RRReadymadeReceipt71.attach(ctx,modal,receipt);await tick();return{ctx,modal,calls,get upload(){return upload}}}
test('Rendered receipt is real JPG with quantity, purchase valuation and linked note',async()=>{const e=env();const files=await e.w.RRReadymadeReceipt71.render(fixture);assert.equal(files.length,1);const bytes=Buffer.from(await files[0].arrayBuffer());assert.equal(bytes.subarray(0,2).toString('hex'),'ffd8');assert.ok(bytes.length>10000);const text=e.labels.join('\n');for(const value of ['540 PCS','530 PCS','DEBIT NOTE','10 PCS','1,500','DN1','79,500'])assert.ok(text.includes(value),value);assert.ok(!text.includes('Sale Rate'));await assert.rejects(e.w.RRReadymadeReceipt71.render({...fixture,status:'DRAFT'}));e.d.window.close()});
test('Saved JPG reused and native file share begins synchronously; OK retries idempotently',async()=>{const e=env(),r=await ready(e,{failRecord:true});let shared=0;let file;e.w.navigator.canShare=()=>true;e.w.navigator.share=p=>{shared++;file=p.files[0];return Promise.resolve()};const share=r.modal.querySelector('[data-share-jpg]'),ok=r.modal.querySelector('[data-share-ok]');share.click();assert.equal(shared,1);assert.equal(file.name,'receipt.jpg');await tick();assert.equal(ok.hidden,false);ok.click();await tick();ok.click();await tick();const events=r.calls.filter(c=>c[0].includes('share_record'));assert.equal(events.length,2);assert.equal(events[0][1].p_event_id,events[1][1].p_event_id);assert.equal(r.upload,0);share.click();assert.equal(shared,2);e.d.window.close()});
test('Cancelled share records no delivery; unsupported file sharing keeps JPG download',async()=>{const e=env(),r=await ready(e);e.w.navigator.canShare=()=>true;e.w.navigator.share=()=>Promise.reject(Object.assign(Error(),{name:'AbortError'}));r.modal.querySelector('[data-share-jpg]').click();await tick();assert.equal(r.calls.filter(c=>c[0].includes('share_record')).length,0);assert.equal(r.modal.querySelector('[data-share-ok]').hidden,true);e.w.navigator.canShare=()=>false;r.modal.querySelector('[data-share-jpg]').click();assert.ok(r.modal.querySelector('[data-message]').textContent.includes('Receipt link'));assert.equal(r.modal.querySelector('a[download]').download,'receipt.jpg');e.d.window.close()});
test('File-disabled browser opens native app picker with receipt link instead of stopping',async()=>{const e=env(),r=await ready(e);let payload;e.w.navigator.canShare=p=>!p.files;e.w.navigator.share=p=>{payload=p;return Promise.resolve()};r.modal.querySelector('[data-share-jpg]').click();assert.ok(payload.url.includes('test71-readymade-supplier-receipt.html#'));assert.ok(!payload.files);const snapshot=JSON.parse(decodeURIComponent(new URL(payload.url).hash.slice(1)));assert.equal(snapshot.files[0].url,'https://test/saved.jpg');assert.ok(snapshot.files[0].sha256);await tick();assert.equal(r.modal.querySelector('[data-share-ok]').hidden,false);e.d.window.close()});
test('Missing canShare does not suppress native JPEG sharing',async()=>{const e=env(),r=await ready(e);let called=0;e.w.navigator.share=p=>{called++;assert.equal(p.files[0].name,'receipt.jpg');return Promise.resolve()};r.modal.querySelector('[data-share-jpg]').click();assert.equal(called,1);await tick();e.d.window.close()});
test('Denied policy or missing native API still opens manual WhatsApp chooser with immutable receipt link',async()=>{for(const deny of [false,true]){const e=env(),r=await ready(e);let opened='';const a=r.modal.querySelector('[data-whatsapp-receipt]');a.addEventListener('click',()=>{opened=a.href});if(deny){e.w.document.permissionsPolicy={allowsFeature:()=>false};e.w.navigator.canShare=()=>true;e.w.navigator.share=()=>{throw Error('Must not call denied API')}}r.modal.querySelector('[data-share-jpg]').click();assert.ok(opened.startsWith('https://wa.me/?text='));assert.match(decodeURIComponent(opened),/test71-readymade-supplier-receipt.html/);assert.equal(r.calls.filter(c=>c[0].includes('share_record')).length,0);assert.equal(r.modal.querySelector('[data-share-ok]').hidden,false);assert.equal(r.upload,0);e.d.window.close()}});
test('Share failure keeps standalone browser JPG route and manual WhatsApp link available',async()=>{const e=env(),r=await ready(e);e.w.navigator.canShare=()=>true;e.w.navigator.share=()=>Promise.reject(Object.assign(Error(),{name:'NotAllowedError'}));r.modal.querySelector('[data-share-jpg]').click();await tick();assert.match(r.modal.querySelector('[data-message]').textContent,/Open in browser/);assert.equal(r.modal.querySelector('[data-browser-receipt]').target,'_blank');assert.equal(r.modal.querySelector('[data-browser-receipt]').hidden,false);assert.equal(r.modal.querySelector('[data-share-ok]').hidden,true);e.d.window.close()});
