'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.resolve(__dirname,'../../real-common.js'),'utf8');
test('universal business uppercase authority is installed and protected',()=>{assert.match(source,/installBusinessUppercaseInputs/);assert.match(source,/toLocaleUpperCase/);assert.match(source,/password.*email.*url.*search/);assert.match(source,/remark\|remarks\|note\|notes\|description/);assert.match(source,/addEventListener\('submit'/);assert.match(source,/dataset\.rrUppercase==='off'/)});

test('number assist must normalize before matching',()=>{const accessory=fs.readFileSync(path.resolve(__dirname,'../../real-accessory-master-v804.js'),'utf8');assert.match(accessory,/uppercaseBusinessValue\?\.\(input\).*const rows=matches\(\)/s);});

test('active TEST71 business feeding surfaces are covered by common uppercase authority or exempt-only',()=>{const active=['real-cutting-master.html','real-finished-goods-v787.html','real-metal-id-master-v804.html','real-print-master.html','real-product-master-v720.html','real-sticker-master-v804.html','real-art-master.html','real-department-lite-v9127.html'];for(const file of active){const html=fs.readFileSync(path.resolve(__dirname,'../../'+file),'utf8');assert.match(html,/real-common\.js/,file+' must load real-common.js')}const exemptOnly=['real-accounts-suite-v857.html','test70-cb-purchase-real-chat-pilot.html'];for(const file of exemptOnly){const html=fs.readFileSync(path.resolve(__dirname,'../../'+file),'utf8');const fields=[...html.matchAll(/<(?:input|textarea)\b[^>]*>/gi)].map(m=>m[0]);assert.ok(fields.every(x=>/type=[\"']search[\"']/i.test(x)),file+' may omit common only while all manual fields are search-only')}});

test('accessory image stays before number and name',()=>{for(const file of ['real-sticker-master-v804.html','real-metal-id-master-v804.html']){const html=fs.readFileSync(path.resolve(__dirname,'../../'+file),'utf8'),image=html.indexOf('id="currentImageBox"'),no=html.indexOf('id="itemNo"'),name=html.indexOf('id="itemName"');assert.ok(image>=0&&image<no&&no<name,file+' must keep image -> number -> name DOM order')}});

test('division display authority is S-only while backend may remain D canonical',()=>{const common=fs.readFileSync(path.resolve(__dirname,'../../real-common.js'),'utf8'),cb=fs.readFileSync(path.resolve(__dirname,'../../real-cb-new-v9130-fix2.html'),'utf8'),art=fs.readFileSync(path.resolve(__dirname,'../../real-art-decide-master-v9231.js'),'utf8');assert.match(common,/displayDivision/);assert.match(common,/installDivisionDisplayAuthority/);assert.doesNotMatch(cb,/>D\\$\\{(?:di\\+1|i)\\}</);assert.match(cb,/id="divisionPreview">S1 · S2/);assert.ok(art.includes('function dNo(unit){return `S${Number(unit?.division_index||1)}`}'));});

test('CB edit keeps compact four-column S child Art thumbnail row before remarks',()=>{const html=fs.readFileSync(path.resolve(__dirname,'../../real-cb-new-v9130-fix2.html'),'utf8');assert.ok(html.indexOf('id="artThumbCard"')<html.indexOf('>Remarks</h3>'));assert.match(html,/grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/);assert.match(html,/rr_cb_art_assignments/);assert.match(html,/entity_type','art'/);assert.ok(html.includes('S\\${Number(unit.division_index||1)}'));});
