'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {JSDOM}=require('jsdom');const fs=require('node:fs');const path=require('node:path');
const root=path.join(__dirname,'../..');const source=fs.readFileSync(path.join(root,'real-pi-specimen-v9514.js'),'utf8');
const tick=()=>new Promise(r=>setTimeout(r,15));
async function setup({superadmin=true,discount=2,save,query='',detail,stockType='REGULAR'}={}){
 const html=fs.readFileSync(path.join(root,'real-pi-specimen-v9514.html'),'utf8');const d=new JSDOM(html,{url:'https://example.test/real-pi-specimen-v9514.html'+query,runScripts:'outside-only'});let current=discount;const calls=[];
 d.window.sessionStorage.setItem('rr_pi_requirement_v9514',JSON.stringify({customer_name:'Party A',lines:[{lot_no:'LOT-A',qty:2,rate:100,discount:9,stock_type:stockType},{lot_no:'LOT-B',qty:3,rate:200,discount:1}]}));
 d.window.RR={requireRoles:async roles=>{assert.ok(roles.includes('super_admin'));}};
 d.window.RF853={rpc:async(n,a)=>{calls.push({n,a});if(n==='rr_pi_actor_context_v9526')return {superadmin};if(n==='rr_sales_pi_detail_v500')return detail;
 if(n==='rr_pi_lot_context_v9517')return {approved_rate:a.p_lot_no==='LOT-A'?100:200,allowed_discount:current,available_qty:100,customer_id:'party-id'};
 if(n==='rr_trade_effective_rate_v849')return {target_sale_rate:120};
 if(n==='rr_fg_save_pi_party_discount_v9557')return save?save(a):{pi_id:'new-pi',party_discount_per_piece:a.p_party_discount??current};
 if(n==='rr_pi_apply_display_no_v9540')return 'PI 123';return '';}};
 d.window.eval(source);await tick();return {d,calls,setDiscount:v=>current=v};
}
const discounts=s=>[...s.d.window.document.querySelectorAll('.disc')].map(x=>Number(x.value));
test('editing any row sets one party-wide flat discount and saves it atomically',async()=>{const s=await setup();try{assert.deepEqual(discounts(s),[2,2]);const el=s.d.window.document.querySelectorAll('.disc')[1];el.value=5;el.dispatchEvent(new s.d.window.Event('change'));assert.deepEqual(discounts(s),[5,5]);s.d.window.document.getElementById('save').click();await tick();const save=s.calls.find(x=>x.n==='rr_fg_save_pi_party_discount_v9557');assert.equal(save.a.p_party_discount,5);assert.deepEqual(Array.from(save.a.p_lines,x=>x.rate),[100,200]);assert.ok(!s.calls.some(x=>x.n==='rr_pi_set_customer_discount_v9525'));assert.deepEqual(discounts(s),[5,5]);}finally{s.d.window.close()}});
test('Sales cannot edit discount and saves with the latest locked server default',async()=>{const s=await setup({superadmin:false});try{assert.ok([...s.d.window.document.querySelectorAll('.disc')].every(x=>x.readOnly));s.setDiscount(7);s.d.window.document.getElementById('save').click();await tick();assert.equal(s.calls.find(x=>x.n==='rr_fg_save_pi_party_discount_v9557').a.p_party_discount,null);assert.deepEqual(discounts(s),[7,7]);}finally{s.d.window.close()}});
test('failed atomic save retains the proposed discount for retry and never calls separate setter',async()=>{const s=await setup({save:async()=>{throw Error('save failed')}});try{const el=s.d.window.document.querySelector('.disc');el.value=6;el.dispatchEvent(new s.d.window.Event('change'));s.d.window.document.getElementById('save').click();await tick();assert.match(s.d.window.document.getElementById('msg').textContent,/save failed/);assert.deepEqual(discounts(s),[6,6]);assert.ok(!s.calls.some(x=>/set_customer_discount/.test(x.n)));}finally{s.d.window.close()}});
test('rapid double save creates one bill and one approval',async()=>{let resolve;const s=await setup({save:()=>new Promise(r=>resolve=r)});try{s.d.window.document.getElementById('save').click();s.d.window.document.getElementById('save').click();await tick();assert.equal(s.calls.filter(x=>x.n==='rr_fg_save_pi_party_discount_v9557').length,1);resolve({pi_id:'new-pi',party_discount_per_piece:2});await tick();}finally{s.d.window.close()}});
test('explicit finalized bill link beats stale requirement session and keeps its discount snapshot',async()=>{const s=await setup({query:'?pi_id=old-pi',detail:{pi_id:'old-pi',pi_no:'PI OLD',status:'CI_FINAL',customer_name:'Party B',lines:[{lot_no:'OLD',qty:1,rate:100,discount:5}]}});try{assert.equal(s.d.window.document.getElementById('customer').value,'Party B');assert.deepEqual(discounts(s),[5]);assert.equal(s.d.window.document.getElementById('total').textContent,'₹100');assert.ok(s.d.window.document.getElementById('save').disabled);assert.equal(s.calls.filter(x=>x.n==='rr_fg_save_pi_party_discount_v9557').length,0);}finally{s.d.window.close()}});
test('traded items use approved gross rate before the same flat party discount',async()=>{const s=await setup({stockType:'TRADED'});try{assert.equal(Number(s.d.window.document.querySelector('.rate').value),120);assert.deepEqual(discounts(s),[2,2]);}finally{s.d.window.close()}});
