const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const source=fs.readFileSync('real-sales-chat-delete-test71.js','utf8');
function bulk(own=true,failAt=0){let chat='chat1',calls=[],refreshes=0,synced=0,reports=[];const selected=new Map([['a',{own}],['b',{own:true}]]);const factory=new Function('selected','context','selectionKey','RF853','api','confirm','syncSelection','report',"let busy=false,selectedContext='chat1|GROUP';"+source.slice(source.indexOf('async function removeSelected('),source.indexOf('function bindSelection('))+"return removeSelected;");const remove=factory(selected,()=>({chatId:chat}),()=>chat+'|GROUP',{rpc:async(n,a)=>{calls.push(a);if(calls.length===failAt)throw Error('offline')}},()=>({refresh:async()=>refreshes++}),()=>true,()=>synced++,x=>reports.push(x));return{remove,selected,calls,reports,get refreshes(){return refreshes},change:()=>chat='chat2'}}
test('multi-delete confirms once and deletes both selected messages through existing RPC',async()=>{const f=bulk();await f.remove('ME');assert.deepEqual(f.calls.map(a=>a.p_message_id),['a','b']);assert.equal(f.refreshes,1);assert.equal(f.selected.size,0)});
test('everyone deletion blocks mixed ownership',async()=>{const f=bulk(false);await f.remove('ALL');assert.equal(f.calls.length,0);assert.equal(f.selected.size,2)});
test('partial deletion preserves failed selection for retry',async()=>{const f=bulk(true,2);await f.remove('ME');assert.deepEqual([...f.selected.keys()],['b']);assert.equal(f.calls.length,2)});
test('selection cannot delete after switching conversation',async()=>{const f=bulk();f.change();await f.remove('ME');assert.equal(f.calls.length,0)});
test('hold selects while scrolling cancels hold and three-dot controls are removed',()=>{const handlers={},timers=[],cleared=[];let toggles=0;const factory=new Function('document','setTimeout','clearTimeout','toggleSelection','navigator',"let holdTimer=0,holdPoint=null,suppressClick=false,holdMoved=false;const selected=new Map();function clearSelection(){}function removeSelected(){}"+source.slice(source.indexOf('function bindSelection('),source.indexOf('bindSelection();'))+"bindSelection();");factory({createElement:()=>({}),head:{appendChild(){}},addEventListener:(ev,fn)=>handlers[ev]=fn},fn=>(timers.push(fn),timers.length),id=>cleared.push(id),()=>toggles++,{vibrate(){}});const row={dataset:{msgId:'a'},classList:{remove(){}}};handlers.touchstart({target:{closest:()=>row},touches:[{clientX:10,clientY:10}]});timers.at(-1)();assert.equal(toggles,1);handlers.touchstart({target:{closest:()=>row},touches:[{clientX:10,clientY:10}]});handlers.touchmove({touches:[{clientX:10,clientY:40}]});assert.ok(cleared.includes(2));assert.ok(!source.includes("b.textContent='⋮'"));});

function gestures(){const handlers={},timers=[],selected=new Map();const factory=new Function('document','setTimeout','clearTimeout','navigator',"let holdTimer=0,holdPoint=null,suppressClick=false,holdMoved=false;const selected=new Map();function toggleSelection(row){const id=row.dataset.msgId;if(selected.has(id))selected.delete(id);else selected.set(id,true)}function clearSelection(){}function removeSelected(){}"+source.slice(source.indexOf('function bindSelection('),source.indexOf('bindSelection();'))+"bindSelection();return selected;");const chosen=factory({createElement:()=>({}),head:{appendChild(){}},addEventListener:(ev,fn)=>handlers[ev]=fn},fn=>(timers.push(fn),timers.length),()=>{},{vibrate(){}});function event(id,x=10,y=10){return{target:{closest:()=>id?{dataset:{msgId:id},classList:{remove(){}}}:null},touches:[{clientX:x,clientY:y}],cancelable:true,preventDefault(){this.prevented=true},stopImmediatePropagation(){this.stopped=true}}}return{handlers,timers,chosen,event}}
test('native touchend selects a second message without relying on synthetic click',()=>{const f=gestures();f.handlers.touchstart(f.event('a'));f.timers.at(-1)();f.handlers.touchend(f.event('a'));assert.deepEqual([...f.chosen.keys()],['a']);f.handlers.touchstart(f.event('b'));f.handlers.touchend(f.event('b'));assert.deepEqual([...f.chosen.keys()],['a','b'])});
test('Cancel and delete toolbar touches remain clickable during selection',()=>{const f=gestures();f.handlers.touchstart(f.event('a'));f.timers.at(-1)();const toolbar=f.event(null);f.handlers.touchend(toolbar);assert.equal(toolbar.prevented,undefined);assert.equal(toolbar.stopped,undefined)});
test('scrolling in selection mode does not select another message',()=>{const f=gestures();f.handlers.touchstart(f.event('a'));f.timers.at(-1)();f.handlers.touchend(f.event('a'));f.handlers.touchstart(f.event('b'));f.handlers.touchmove(f.event('b',10,60));f.handlers.touchend(f.event('b',10,60));assert.deepEqual([...f.chosen.keys()],['a'])});
test('staff reply reader routes through deletion-aware API and observer avoids toolbar subtree',()=>{assert.ok(source.includes("['rr_chat_staff_messages_v9434','rr_chat_staff_messages_v9479'].includes(name)"));assert.ok(source.includes("observer.observe(messageRoot"));assert.ok(!source.includes("observer.observe(document.body"));assert.ok(source.includes('data-me>DELETE FOR ME'));});
