const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{JSDOM}=require('jsdom');
const source=fs.readFileSync('test70-real-chat-live-v70.js','utf8');
const start=source.indexOf('async function openFabricationReceiveV326('),end=source.indexOf('\n',source.indexOf(';refresh()}catch(e)',start));
const code=source.slice(start,end);
function fixture(options={}){
 const dom=new JSDOM('<button data-fab-receive="request">ACCEPT & COUNT</button>'),calls=[],alerts=[],loads=[];
 const state={statusCache:new Map([['old',1]]),craftIdentityCache:new Map([['old',1]]),workerLaneCache:new Map([['old',1]])};
 const context={document:dom.window.document,S:state,arr:x=>Array.isArray(x)?x:[],safe:x=>String(x??''),err:e=>e.message,confirm:()=>true,alert:s=>alerts.push(s),console,
  rpc:async(name,args)=>{calls.push({name,args});if(name==='rr_chat_prepare_accept_count_test71')return {lot_no:'2634',accept_count_complete:options.complete||false,colour_rows:[{colour_code:'C1',assignment_id:'assignment',sizes:[{size_code:'L',ready_qty:22},{size_code:'XL',ready_qty:22}]}]};if(name==='rr_material_direct_pending_v658')return {rows:options.material?[{mapping_id:'mapping',material_name:'THREAD',unit:'KG'}]:[]};if(name==='rr_chat_accept_count_test71'){if(options.error)throw Error('Save failed');if(options.save)return options.save(args);return {status:'COMPLETED',accept_count_complete:true};}throw Error('Unexpected RPC '+name);},
  load:async(force)=>loads.push(force)};
 vm.createContext(context);vm.runInContext(code,context);
 const button=dom.window.document.querySelector('button'),q=s=>dom.window.document.querySelector(s);
 return {dom,context,calls,alerts,loads,state,button,q,open:()=>context.openFabricationReceiveV326(button),save:()=>q('[data-save]').onclick(),cleanup:()=>dom.window.close()};
}
test('opening and Cancel never call an acceptance mutation',async()=>{const f=fixture();try{await f.open();assert.deepEqual(f.calls.map(x=>x.name),['rr_chat_prepare_accept_count_test71','rr_material_direct_pending_v658']);f.q('[data-close]').click();assert.equal(f.q('.fab-receive-overlay'),null);assert.equal(f.button.disabled,false);assert.equal(f.loads.length,0);}finally{f.cleanup()}});
test('blank, fractional, negative and partially unchecked count cannot Save',async()=>{for(const value of ['', '-1','1.5']){const f=fixture();try{await f.open();f.q('[data-fab-count="0"]').value=value;await f.save();assert.equal(f.calls.some(x=>x.name==='rr_chat_accept_count_test71'),false);assert.ok(f.q('[data-state]').textContent);}finally{f.cleanup()}}const f=fixture();try{await f.open();f.q('[data-fab-take="1"]').checked=false;await f.save();assert.equal(f.calls.some(x=>x.name==='rr_chat_accept_count_test71'),false);}finally{f.cleanup()}});
test('full count Saves once, clears pending caches and reloads the next-stage projection',async()=>{const f=fixture();try{await f.open();await f.save();const saves=f.calls.filter(x=>x.name==='rr_chat_accept_count_test71');assert.equal(saves.length,1);assert.deepEqual(JSON.parse(JSON.stringify(saves[0].args)),{p_request_id:'request',p_count_rows:[{colour_code:'C1',size_code:'L',qty:22},{colour_code:'C1',size_code:'XL',qty:22}],p_material_rows:[]});assert.equal(f.q('.fab-receive-overlay'),null);for(const cache of Object.values(f.state))assert.equal(cache.size,0);assert.deepEqual(f.loads,[true]);}finally{f.cleanup()}});
test('Save failure keeps the card unaccepted, retains inputs and permits retry',async()=>{const f=fixture({error:true});try{await f.open();f.q('[data-fab-count="0"]').value='21';await f.save();assert.equal(f.q('[data-fab-count="0"]').value,'21');assert.equal(f.q('[data-save]').disabled,false);assert.equal(f.q('[data-state]').textContent,'Save failed');assert.equal(f.loads.length,0);}finally{f.cleanup()}});
test('material validation precedes acceptance and material consumption is in the same RPC',async()=>{const f=fixture({material:true});try{await f.open();f.q('[data-direct-use="0"]').checked=true;await f.save();assert.equal(f.calls.some(x=>x.name==='rr_chat_accept_count_test71'),false);f.q('[data-direct-qty="0"]').value='1.25';await f.save();const save=f.calls.find(x=>x.name==='rr_chat_accept_count_test71');assert.deepEqual(JSON.parse(JSON.stringify(save.args.p_material_rows)),[{assignment_id:'assignment',mapping_id:'mapping',consumed_qty:1.25}]);assert.equal(f.calls.some(x=>x.name==='rr_material_direct_confirm_v658'),false);}finally{f.cleanup()}});
test('in-flight Save blocks a second Save and Cancel',async()=>{let resolve;const f=fixture({save:()=>new Promise(r=>resolve=r)});try{await f.open();const first=f.save();await f.save();f.q('[data-close]').onclick();assert.ok(f.q('.fab-receive-overlay'));assert.equal(f.calls.filter(x=>x.name==='rr_chat_accept_count_test71').length,1);resolve({status:'COMPLETED',accept_count_complete:true});await first;assert.equal(f.q('.fab-receive-overlay'),null);}finally{f.cleanup()}});
test('mismatch remains explicitly Not Accepted and refreshes the existing final-decision workflow',async()=>{const f=fixture({save:async()=>({status:'DISPUTED',difference:-1,accept_count_complete:false})});try{await f.open();await f.save();assert.match(f.q('[data-state]').textContent,/Accepted नहीं/);assert.deepEqual(f.loads,[true]);assert.ok(f.q('.fab-receive-overlay'));}finally{f.cleanup()}});
test('already completed handover refreshes without exposing another acceptance form',async()=>{const f=fixture({complete:true});try{await f.open();assert.equal(f.q('.fab-receive-overlay'),null);assert.deepEqual(f.loads,[true]);assert.equal(f.calls.length,1);}finally{f.cleanup()}});

test('legacy Accepted history on an incomplete card is labeled pending without changing unrelated history',()=>{const s=fs.readFileSync('real-chat-action-receipts-test71.js','utf8'),c={};vm.createContext(c);vm.runInContext(s.slice(s.indexOf('function pendingHandoverLabel('),s.indexOf(' function tick(')),c);assert.equal(c.pendingHandoverLabel({},'Submit · LM ACCEPTED',{dataset:{acceptCountComplete:'false'}}),'Submit · Accept & Count pending');assert.equal(c.pendingHandoverLabel({},'Submit · LM ACCEPTED',{dataset:{acceptCountComplete:'true'}}),'Submit · LM ACCEPTED');assert.equal(c.pendingHandoverLabel({},'SUBMIT',{dataset:{acceptCountComplete:'false'}}),'SUBMIT');});
