BEGIN;
DO $test$
DECLARE s public.rr_market_share_v9420%rowtype;c public.rr_customers%rowtype;r jsonb;r2 jsonb;rid uuid;code text;mob text;admin_uid uuid;session_token text;dev text:='test71-whatsapp-rollback-device-123456789';
BEGIN
 SELECT ms.* INTO s FROM public.rr_market_share_v9420 ms JOIN public.rr_customers rc ON rc.id=ms.customer_id WHERE ms.status='ACTIVE' AND ms.data_mode='TEST' AND rc.is_active AND length(regexp_replace(rc.mobile,'[^0-9]','','g'))>=10 AND public.rr_market_share_relation_v81(ms.token)<>'DISTRIBUTOR_CUSTOMER' LIMIT 1;
 IF s.id IS NULL THEN RAISE EXCEPTION 'Active TEST customer fixture required';END IF;
 SELECT * INTO c FROM public.rr_customers WHERE id=s.customer_id;
 mob:=right(regexp_replace(c.mobile,'[^0-9]','','g'),10);
 SELECT auth_user_id INTO admin_uid FROM public.rr_user_profiles WHERE full_name='TEST71 E2E Super Admin' AND is_active;
 IF admin_uid IS NULL THEN RAISE EXCEPTION 'TEST Super Admin fixture required';END IF;
 IF has_function_privilege('anon','public.rr_customer_whatsapp_approve_test71(uuid,text,text)','execute') OR has_table_privilege('authenticated','rr_customer_auth_test71.whatsapp_challenges','select') THEN RAISE EXCEPTION 'Private verification exposed';END IF;
 r:=public.rr_customer_whatsapp_request_test71(s.token,'Forged name',mob,dev);rid:=(r->>'request_id')::uuid;code:=r->>'whatsapp_code';
 IF r->>'customer_name'<>c.customer_name OR r->>'approval_status'<>'PENDING' OR length(code)<>16 THEN RAISE EXCEPTION 'Canonical pending challenge required';END IF;
 r2:=public.rr_customer_whatsapp_request_test71(s.token,c.customer_name,mob,dev);
 IF r2->>'whatsapp_code'<>code THEN RAISE EXCEPTION 'Active challenge unexpectedly renewed';END IF;
 IF rr_customer_auth_test71.number_verified(rid) OR rr_customer_auth_test71.otp_owned(rid) THEN RAISE EXCEPTION 'Unverified request gained authority';END IF;
 r2:=public.rr_customer_session_issue_bound_v9680(s.token,c.customer_name,mob,dev);
 IF r2 ? 'session_token' THEN RAISE EXCEPTION 'Pending request issued session';END IF;
 BEGIN PERFORM public.rr_customer_login_status_test71(rid,'wrong-device-binding-123456789');RAISE EXCEPTION 'Wrong device accepted';EXCEPTION WHEN OTHERS THEN IF SQLERRM='Wrong device accepted' THEN RAISE;END IF;END;
 PERFORM set_config('request.jwt.claims','{}',true);
 BEGIN PERFORM public.rr_customer_whatsapp_approve_test71(rid,mob,code);RAISE EXCEPTION 'Unauthenticated approval accepted';EXCEPTION WHEN OTHERS THEN IF SQLERRM='Unauthenticated approval accepted' THEN RAISE;END IF;END;
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',admin_uid,'role','authenticated')::text,true);
 BEGIN PERFORM public.rr_customer_whatsapp_approve_test71(rid,'0000000000',code);RAISE EXCEPTION 'Wrong sender accepted';EXCEPTION WHEN OTHERS THEN IF SQLERRM='Wrong sender accepted' THEN RAISE;END IF;END;
 BEGIN PERFORM public.rr_customer_whatsapp_approve_test71(rid,mob,'0000000000000000');RAISE EXCEPTION 'Wrong code accepted';EXCEPTION WHEN OTHERS THEN IF SQLERRM='Wrong code accepted' THEN RAISE;END IF;END;
 BEGIN PERFORM public.rr_customer_login_approval_decide_test71(rid,'APPROVED',true);RAISE EXCEPTION 'Checkbox bypass accepted';EXCEPTION WHEN OTHERS THEN IF SQLERRM='Checkbox bypass accepted' THEN RAISE;END IF;END;
 UPDATE rr_customer_auth_test71.whatsapp_challenges SET expires_at=clock_timestamp()-interval '1 second' WHERE request_id=rid;
 BEGIN PERFORM public.rr_customer_whatsapp_approve_test71(rid,mob,code);RAISE EXCEPTION 'Expired code accepted';EXCEPTION WHEN OTHERS THEN IF SQLERRM='Expired code accepted' THEN RAISE;END IF;END;
 r:=public.rr_customer_whatsapp_request_test71(s.token,c.customer_name,mob,dev);code:=r->>'whatsapp_code';
 PERFORM public.rr_customer_permission_set_test71(c.id,'PAUSE');
 BEGIN PERFORM public.rr_customer_whatsapp_approve_test71(rid,mob,code);RAISE EXCEPTION 'Paused approval accepted';EXCEPTION WHEN OTHERS THEN IF SQLERRM='Paused approval accepted' THEN RAISE;END IF;END;
 PERFORM public.rr_customer_permission_set_test71(c.id,'RESUME');
 PERFORM public.rr_customer_whatsapp_approve_test71(rid,'+91'||mob,lower(code));
 IF NOT rr_customer_auth_test71.number_verified(rid) OR rr_customer_auth_test71.otp_owned(rid) THEN RAISE EXCEPTION 'Manual/SMS evidence confused';END IF;
 BEGIN PERFORM public.rr_customer_whatsapp_approve_test71(rid,mob,code);RAISE EXCEPTION 'Consumed code accepted';EXCEPTION WHEN OTHERS THEN IF SQLERRM='Consumed code accepted' THEN RAISE;END IF;END;
 r:=public.rr_customer_session_issue_bound_v9680(s.token,c.customer_name,mob,dev);session_token:=r->>'session_token';
 IF session_token IS NULL THEN RAISE EXCEPTION 'Manually approved device failed to issue session';END IF;
 PERFORM public.rr_customer_session_validate_v9590(session_token,dev);
 UPDATE public.rr_customers SET mobile='0000000000' WHERE id=c.id;
 IF rr_customer_auth_test71.number_verified(rid) THEN RAISE EXCEPTION 'Changed phone kept manual authority';END IF;
 BEGIN PERFORM public.rr_customer_session_validate_v9590(session_token,dev);RAISE EXCEPTION 'Changed phone kept session';EXCEPTION WHEN OTHERS THEN IF SQLERRM='Changed phone kept session' THEN RAISE;END IF;END;
 UPDATE public.rr_customers SET mobile=c.mobile WHERE id=c.id;
 PERFORM public.rr_customer_login_approval_decide_test71(rid,'REVOKED',false);
 IF rr_customer_auth_test71.number_verified(rid) THEN RAISE EXCEPTION 'Revoked manual evidence kept authority';END IF;
 BEGIN PERFORM public.rr_customer_session_validate_v9590(session_token,dev);RAISE EXCEPTION 'Revoked session accepted';EXCEPTION WHEN OTHERS THEN IF SQLERRM='Revoked session accepted' THEN RAISE;END IF;END;
END $test$;
ROLLBACK;
SELECT 'PASS: bound manual verification, expiry, reuse, sender/code/Admin checks, pause/revoke, canonical phone, session validation; rollback' result;
