const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('supabase/functions/rr-customer-phone-otp-test71/index.ts','utf8').replace(/^import[^\n]+\n/,'').replace('(status:number,data:unknown)','(status,data)');
function fixture(mode){let handler;const calls=[],sent=[];const client={rpc:async(name,args)=>{calls.push([name,args]);if(name.includes('prepare'))return mode==='wrong-phone'?{error:{message:'wrong'}}:{data:{phone:'+919000000000',challenge_id:'challenge',customer_name:'Registered'}};if(name.includes('challenge'))return mode==='exhausted'?{error:{message:'limit'}}:{data:{phone:'+919000000000'}};return {data:{otp_verified:true,approval_status:'PENDING',request_id:'request'}};},auth:{getUser:async()=>({data:{user:{id:'user',phone_confirmed_at:'today'}}})}};vm.runInNewContext(source,{Deno:{env:{get:()=> 'public'},serve:h=>handler=h},createClient:()=>client,Response,atob,fetch:async(url,options)=>{sent.push(JSON.parse(options.body));if(mode==='disabled')return new Response(JSON.stringify({msg:'Phone provider disabled'}),{status:400});if(mode==='wrong-otp')return new Response('{}',{status:400});return new Response(JSON.stringify({access_token:'x.'+Buffer.from(JSON.stringify({session_id:'session'})).toString('base64url')+'.x',refresh_token:'secret'}),{status:200});}});return {calls,sent,run:body=>handler(new Request('https://example.test',{method:'POST',headers:{Origin:'https://redzed-customer-collection.jggfab2011.chatgpt.site'},body:JSON.stringify({device_id:'device-binding-long-enough-12345',...body})}))};}
test('wrong registered number never triggers SMS or approval',async()=>{const f=fixture('wrong-phone'),r=await f.run({action:'send',mobile:'other'});assert.equal(r.status,400);assert.equal(f.sent.length,0);assert.equal(f.calls.length,1);});
test('disabled SMS service fails closed without approval',async()=>{const f=fixture('disabled'),r=await f.run({action:'send'});assert.equal(r.status,503);assert.equal((await r.json()).otp_sent,undefined);assert.equal(f.calls.length,1);assert.equal(f.sent[0].channel,'sms');});
test('wrong OTP cannot call trusted completion',async()=>{const f=fixture('wrong-otp'),r=await f.run({action:'verify',otp:'123456',challenge_id:'challenge'});assert.equal(r.status,400);assert(!f.calls.some(([n])=>n.includes('complete')));assert.equal(f.sent[0].type,'sms');});
test('attempt exhaustion never calls SMS verification',async()=>{const f=fixture('exhausted'),r=await f.run({action:'verify',otp:'123456'});assert.equal(r.status,400);assert.equal(f.sent.length,0);});
test('verified SMS completes bound challenge without exposing Auth tokens',async()=>{const f=fixture('valid'),r=await f.run({action:'verify',otp:'123456',challenge_id:'challenge'}),data=await r.json();assert.equal(r.status,200);assert.equal(data.approval_status,'PENDING');assert.equal(data.access_token,undefined);assert.equal(data.refresh_token,undefined);const args=f.calls.find(([n])=>n.includes('complete'))[1];assert.equal(args.p_auth_user_id,'user');assert.equal(args.p_auth_session_id,'session');assert.equal(args.p_challenge_id,'challenge');});
function uiFixture(mode){const values=new Map(),nodes=[],calls=[];let issueCalls=0;const rpc=async name=>{calls.push(name);if(name==='rr_customer_session_issue_bound_v9680')return ++issueCalls===1?{approval_status:'OTP_REQUIRED'}:{session_token:'approved-session'};if(name==='rr_customer_login_status_test71')return {approval_status:'APPROVED'};if(name==='rr_customer_session_validate_v9590')return {valid:true};};const window={supabase:{createClient:()=>({rpc})}};const document={readyState:'loading',addEventListener(){},getElementById:()=>null,body:{appendChild:n=>nodes.push(n)},createElement:()=>{const fields={};return {style:{},setAttribute(){},querySelector:s=>fields[s]||(fields[s]={value:'',style:{},focus(){},setAttribute(){}}),querySelectorAll:()=>[],remove(){this.removed=true;}};}};vm.runInNewContext(fs.readFileSync('real-customer-secure-session-addon-v9592.js','utf8').replace('  const invalidSession =','  window.test={issue};\n  const invalidSession ='),{window,document,location:{search:'?t=share'},URLSearchParams,SUPABASE_URL:'https://example.test',SUPABASE_ANON_KEY:'public',RF853:{rpc},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)},fetch:async(_,options)=>{const body=JSON.parse(options.body);calls.push(body.action);if(mode==='disabled')return {ok:false,json:async()=>({error:'SMS service disabled'})};return {ok:true,json:async()=>body.action==='send'?{challenge_id:'challenge',customer_name:'Registered',phone:'+919000000000'}:mode==='bad-proof'?{otp_verified:false}:{otp_verified:true,approval_status:'PENDING',request_id:'request'}};},setTimeout:f=>queueMicrotask(f),console,crypto:require('node:crypto').webcrypto,Uint8Array,CustomEvent:function(){}});return {values,nodes,calls,issue:()=>window.test.issue({name:'Typed',mobile:'9000000000'},'trusted-device-binding-123456789')};}
test('customer OTP provider error leaves session empty and sends no approval poll',async()=>{
 const f=uiFixture('disabled'),pending=f.issue();await new Promise(setImmediate);const choice=f.nodes[0];
 await choice.querySelector('[data-verification-sms]').onclick();
 assert.match(choice.querySelector('[data-verification-error]').textContent,/SMS service disabled/);
 assert.equal(f.values.has('rr_customer_secure_session_v9592'),false);assert(!f.calls.includes('rr_customer_login_status_test71'));
 choice.querySelector('[data-verification-cancel]').onclick();await assert.rejects(pending,/cancelled/);
});
test('customer cannot turn OTP response without ownership proof into a session',async()=>{
 const f=uiFixture('bad-proof'),pending=f.issue();await new Promise(setImmediate);const choice=f.nodes[0];choice.querySelector('[data-verification-sms]').onclick();await new Promise(setImmediate);
 const modal=f.nodes[1];modal.querySelector('[data-otp-code]').value='123456';await modal.querySelector('[data-otp-verify]').onclick();
 assert.match(modal.querySelector('[data-otp-error]').textContent,/verification required/);assert.equal(f.values.has('rr_customer_secure_session_v9592'),false);
 modal.querySelector('[data-otp-cancel]').onclick();await new Promise(setImmediate);choice.querySelector('[data-verification-cancel]').onclick();await assert.rejects(pending,/cancelled/);
});
test('customer verified OTP still requires admin approval before validated session',async()=>{
 const f=uiFixture('valid'),pending=f.issue();await new Promise(setImmediate);f.nodes[0].querySelector('[data-verification-sms]').onclick();await new Promise(setImmediate);
 const modal=f.nodes[1];modal.querySelector('[data-otp-code]').value='123456';await modal.querySelector('[data-otp-verify]').onclick();await pending;
 assert(f.calls.indexOf('verify')<f.calls.indexOf('rr_customer_login_status_test71'));assert.equal(JSON.parse(f.values.get('rr_customer_secure_session_v9592')).session_token,'approved-session');assert(f.calls.includes('rr_customer_session_validate_v9590'));assert(modal.removed);
});
