const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const sw=fs.readFileSync('rz-sw-v61.js','utf8'),core=fs.readFileSync('test70-real-chat-live-v70.js','utf8');
function fixture(windows=[]){const handlers={},opened=[],focused=[],navigated=[];let notification;const clients={matchAll:async()=>windows,openWindow:async url=>{opened.push(url);return{focus:async()=>focused.push('new')}}};const self={location:{origin:'https://example.test'},registration:{scope:'https://example.test/',showNotification:async(title,options)=>notification=options},clients,addEventListener:(name,fn)=>handlers[name]=fn};vm.runInNewContext(sw,{self,clients,URL,Object,String,Number,Date});return {handlers,opened,focused,navigated,get notification(){return notification;}};}
async function push(f,data){let work;f.handlers.push({data:{json:()=>data},waitUntil:p=>work=p});await work;return f.notification;}
async function click(f,data,tag=''){let work;f.handlers.notificationclick({notification:{data,tag,close(){}},waitUntil:p=>work=p});await work;}
function exact(url){const u=new URL(url);assert.equal(u.pathname,'/test70-cb-purchase-real-chat-pilot.html');for(const [k,v]of Object.entries({rc_view:'chat',rc_kind:'group',rc_id:'ADMIN',rc_parent:'ADMIN',rc_status:'OPEN',rc_login_request:'request-1'}))assert.equal(u.searchParams.get(k),v);}
test('approval push overrides main-page URL with exact Admin OPEN request and persists request identity',async()=>{const f=fixture();const n=await push(f,{login_request_id:'request-1',url:'real-sales-live-chat-v9434.html',preview:'Waiting'});assert.equal(n.data.loginRequestId,'request-1');exact(n.data.url);await click(f,n.data);exact(f.opened[0]);});
test('mobile without navigate opens the exact destination rather than only focusing main page',async()=>{let staleFocus=0;const f=fixture([{url:'https://example.test/test70-cb-purchase-real-chat-pilot.html',focus:async()=>staleFocus++}]);await click(f,{loginRequestId:'request-1',url:'https://example.test/test70-cb-purchase-real-chat-pilot.html'});exact(f.opened[0]);assert.equal(staleFocus,0);assert.deepEqual(f.focused,['new']);});
test('null or rejected navigate falls back to exact openWindow',async()=>{for(const navigate of [async()=>null,async()=>{throw Error('unsupported')}]){const f=fixture([{url:'https://example.test/real-sales-live-chat-v9434.html',navigate}]);await click(f,{loginRequestId:'request-1'});exact(f.opened[0]);}});
test('successful navigation focuses the navigated client, with exact request destination',async()=>{let url,focus=0;const f=fixture([{url:'https://example.test/real-sales-live-chat-v9434.html',navigate:async value=>{url=value;return{focus:async()=>focus++}}}]);await click(f,{loginRequestId:'request-1'});exact(url);assert.equal(focus,1);assert.equal(f.opened.length,0);});
test('request-only or stale WORKING URL forces Admin OPEN at boot and clears unrelated search',()=>{const start=core.indexOf('const p=new URLSearchParams(location.search);'),end=core.indexOf('const resumeState=initialState;',start);assert.ok(start>0&&end>start);for(const search of ['?rc_login_request=request-1','?rc_login_request=request-1&rc_view=chat&rc_kind=group&rc_id=CUTTING&rc_status=WORKING']){const context={location:{search},URLSearchParams,S:{status:'WORKING',search:'old lot',searchTerms:['old lot']}};vm.runInNewContext(core.slice(start,end)+'globalThis.initial=initialState;',context);assert.equal(context.initial.id,'ADMIN');assert.equal(context.initial.status,'OPEN');assert.equal(context.initial.kind,'group');assert.equal(context.S.userStatusLock,'OPEN');assert.equal(context.S.search,'');}});
test('non-approval push keeps its existing sales route',async()=>{const f=fixture();const n=await push(f,{url:'real-sales-live-chat-v9434.html?chat=customer-2'});assert.equal(new URL(n.data.url).searchParams.get('chat'),'customer-2');assert.equal(n.data.loginRequestId,'');});
test('approval router waits for host and card, then focuses the actual customer card after rendering',async()=>{const timers=[],events={};let ready=false,visible=false,target=null,opens=0,scrolls=0,focuses=0;let context={kind:'inbox',status:'WORKING',role:'SUPER_ADMIN'};const host={context:()=>context,changed(){},openApproval:async()=>{if(!ready)return false;opens++;context={kind:'group',id:'ADMIN',status:'OPEN',role:'SUPER_ADMIN'};return true;}};const document={readyState:'loading',hidden:false,addEventListener:(type,fn)=>events[type]=fn,getElementById:id=>id==='chat'?{hidden:!visible}:null,querySelectorAll:selector=>selector==='#messages [data-login-request]'&&target?[{dataset:{loginRequest:'request-1'},closest:()=>target}]:[]};const environment={location:{pathname:'/test70-cb-purchase-real-chat-pilot.html',search:'?rc_login_request=request-1'},URLSearchParams,URL,Object,Date,window:{RRAdminApprovalHost71:host,RF853:{rpc:async()=>[{customer_id:'customer-1',devices:[{request_id:'request-1',status:'PENDING'}]}]}},document,setTimeout:fn=>timers.push(fn),setInterval(){},requestAnimationFrame:fn=>fn()};vm.runInNewContext(fs.readFileSync('real-customer-login-approvals-test71.js','utf8'),environment);await environment.window.RRAdminLoginApprovals71.refresh();const tick=async()=>{timers.shift()?.();await new Promise(resolve=>setImmediate(resolve));};await tick();assert.equal(opens,0);ready=true;await tick();assert.equal(opens,1);assert.equal(focuses,0);visible=true;target={style:{},setAttribute(){},scrollIntoView(){scrolls++},focus(){focuses++}};await tick();assert.equal(focuses,1);assert.equal(scrolls,1);assert.equal(target.style.outline,'3px solid #ffe095');await tick();assert.equal(focuses,1);target={style:{},setAttribute(){},scrollIntoView(){scrolls++},focus(){focuses++}};await tick();assert.equal(focuses,2);events.pointerdown({isTrusted:true});target={style:{},setAttribute(){},scrollIntoView(){scrolls++},focus(){focuses++}};await tick();assert.equal(focuses,2);});

test('existing approval notification recovers request identity from its saved tag',async()=>{const f=fixture();await click(f,{url:'https://example.test/test70-cb-purchase-real-chat-pilot.html'},'rz-login-approval-request-1');exact(f.opened[0]);});

test('universal action notice without navigate opens its exact department card route',async()=>{let staleFocus=0;const f=fixture([{url:'https://example.test/test70-cb-purchase-real-chat-pilot.html',focus:async()=>staleFocus++}]);const url='https://example.test/test70-cb-purchase-real-chat-pilot.html?rc_view=chat&rc_kind=group&rc_id=FOLDING&rc_parent=FOLDING&rc_status=WORKING&rc_bridge=event-1&rc_notice=notice-1';await click(f,{url,noticeId:'notice-1'});assert.equal(f.opened[0],url);assert.equal(staleFocus,0)});

test('action push preserves department, status, bridge and notice on successful notification navigation',async()=>{
 for(const department of ['CUTTING','FABRICATION','PRINTING','STITCHING','OVERLOCK','FOLDING','KAAJ_BUTTON','TEAK_TANKI','THREAD_CUT','QC','PRESS','PACKING','DESPATCH','COSTING','ADMIN','ACCOUNTS','SALES'])for(const status of ['OPEN','WORKING','CLOSE']){
  let destination,focused=0;const f=fixture([{url:'https://example.test/test70-cb-purchase-real-chat-pilot.html',navigate:async url=>{destination=url;return{focus:async()=>focused++}}}]);
  const url='test70-cb-purchase-real-chat-pilot.html?rc_view=chat&rc_kind=group&rc_id='+department+'&rc_parent='+department+'&rc_status='+status+'&rc_bridge=bridge-1&rc_notice=notice-1';
  const notice=await push(f,{url,notice_id:'notice-1'});assert.equal(notice.data.noticeId,'notice-1');assert.equal(notice.tag,'rz-notice-notice-1');assert.equal(notice.renotify,false);await click(f,notice.data);assert.equal(destination,new URL(url,'https://example.test/').href);assert.equal(focused,1);
 }
});
test('reading one work notice closes only that recipient notice',async()=>{
 const handlers={},closed=[];const self={registration:{getNotifications:async()=>['a','b'].map(id=>({data:{noticeId:id},close:()=>closed.push(id)}))},addEventListener:(name,fn)=>handlers[name]=fn};vm.runInNewContext(sw,{self,URL});let work;handlers.message({data:{type:'RZ_NOTICE_READ71',ids:['a']},waitUntil:p=>work=p});await work;assert.deepEqual(closed,['a']);
});
