const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('test70-real-chat-live-v70.js','utf8');
function extract(name,next){return source.slice(source.indexOf('function '+name+'('),source.indexOf(next,source.indexOf('function '+name+'(')));}
const context={arr:x=>Array.isArray(x)?x:[],Map,Set};vm.createContext(context);
vm.runInContext(extract('consolidateFabricationOpen71','async function departmentProjectionV709'),context);
vm.runInContext(extract('consolidateWorkerLotCardsV687','function consolidateReadyAssignRowsV202'),context);
const departments=['FOLDING','KAAJ_BUTTON','TEAK_TANKI','THREAD_CUT','QC','PRESS'];
// Captured FABRICATION OPEN Lot 2640 shape: six departments share the same 108 PCS.
const evidence=departments.map(source_department_code=>({lot_no:'2640',canonical_lot_id:'rr_cutting_lots_v3:a3d3f456-d9ff-479b-9b44-910f7a6bc779',department_code:'FABRICATION',source_department_code,qty:108,pieces:108,event_key:'FAB:OPEN:'+source_department_code+':2640',actions:[{code:'ASSIGN_WORKER',department_code:source_department_code,label:'ASSIGN WORK'}]}));
test('Lot 2640 six ready departments become one 108 PCS card with all department identities',()=>{const result=context.consolidateFabricationOpen71(evidence,'OPEN');assert.equal(result.length,1);assert.equal(result[0].qty,108);assert.equal(result[0].pieces,108);assert.equal(result[0].actions.length,1);assert.equal(result[0].source_department_codes.length,6);assert.equal(result[0].source_event_keys.length,6);assert.match(result[0].message,/FOLDING/);assert.match(result[0].message,/PRESS/);});
test('different lots stay separate and WORKING handovers retain their individual actions',()=>{const result=context.consolidateFabricationOpen71(evidence.concat({...evidence[0],lot_no:'2641',canonical_lot_id:'lot-2641'}),'OPEN');assert.equal(result.length,2);assert.equal(context.consolidateFabricationOpen71(evidence,'WORKING').length,6);});
test('canonical UPM projection colours consolidate by lot+department+worker and retain exact assignments',()=>{const make=(assignment_id,worker_id,colour_code,qty)=>({source_module:'REAL_CHAT_PROJECTION_V709',assignment_id,worker_id,colour_code,qty,department_code:'STICKER',canonical_lot_id:'2640',actions:[]});const result=context.consolidateWorkerLotCardsV687([make('a','kartik','RED',50),make('b','kartik','BLUE',58),make('c','madan','RED',20)]);assert.equal(result.length,2);const card=result.find(r=>r.worker_id==='kartik');assert.equal(card.qty,108);assert.equal(card.assignment_ids.length,2);assert.equal(card.colour_count,2);});
test('notification selects the exact card action filter without changing unrelated chats or looping',()=>{
 const fixture={S:{status:'WORKING',workFilter:'READY_TO_SUBMIT',active:{kind:'group',id:'FABRICATION'},noticeSourceRows:{scope:'group|FABRICATION|WORKING',rows:[{submit_request_id:'request-2622',work_category:'RECEIPT_PENDING'}]}},arr:x=>Array.isArray(x)?x:[],workType:c=>c.work_category,twoScreenContext71:()=>false,manufacturingLanes71:()=>false,renders:0};fixture.renderActive=()=>fixture.renders++;vm.createContext(fixture);vm.runInContext(extract('focusUnreadCard71','window.RRAdminApprovalHost71='),fixture);
 assert.equal(fixture.focusUnreadCard71({submit_request_id:'unrelated'}),false);assert.equal(fixture.focusUnreadCard71({submit_request_id:'request-2622'}),true);assert.equal(fixture.S.workFilter,'RECEIPT_PENDING');assert.equal(fixture.renders,1);assert.equal(fixture.focusUnreadCard71({submit_request_id:'request-2622'}),false);
});
test('every production department preserves worker and department boundaries and existing colour assignments',()=>{
 const deps=['PRINTING','STICKER','METAL_ID','STITCHING','OVERLOCK','FOLDING','KAAJ_BUTTON','TEAK_TANKI','THREAD_CUT','QC','PRESS','PACKING','DISPATCH','FABRICATION'];const rows=deps.flatMap(department_code=>['a','b'].map((assignment_id,i)=>({source_module:'REAL_CHAT_PROJECTION_V709',canonical_lot_id:'2640',worker_id:'worker',department_code,assignment_id:department_code+assignment_id,colour_code:assignment_id,qty:i?58:50,actions:[]})));rows.push({...rows[0],assignment_id:'different-worker',worker_id:'other',qty:20});const result=context.consolidateWorkerLotCardsV687(rows);assert.equal(result.length,deps.length+1);for(const dep of deps){const card=result.find(x=>x.department_code===dep&&x.worker_id==='worker');assert.equal(card.qty,108);assert.equal(card.colour_count,2);const again=context.consolidateWorkerLotCardsV687([card])[0];assert.equal(again.qty,108);assert.equal(again.colour_count,2);assert.deepEqual(Array.from(again.assignment_ids),Array.from(card.assignment_ids));}
});
test('Fabrication ready summary never combines assigned workers',()=>{const rows=evidence.concat({...evidence[0],worker_id:'worker-a'},{...evidence[0],worker_id:'worker-b'});assert.equal(context.consolidateFabricationOpen71(rows,'OPEN').length,3);});
