const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const s=fs.readFileSync('test70-real-chat-live-v70.js','utf8');const c={arr:x=>Array.isArray(x)?x:[],S:{status:'WORKING',workLane:'STAFF',active:{kind:'group',id:'FABRICATION'}}};vm.createContext(c);vm.runInContext(s.slice(s.indexOf('function manufacturingLanes71('),s.indexOf('function syncWorkLanes71(')),c);vm.runInContext(s.slice(s.indexOf('function activeAlterCustody71('),s.indexOf('function syncStatusButtons(')),c);
const card=(code,extra={})=>({qty:108,actions:code?[{code}]:[],...extra});
test('legacy incomplete handover stays pending until atomic Accept & Count; complete Save leaves both working lanes',()=>{assert.equal(c.pendingLane71(card('ACCEPT_AND_COUNT',{submit_status:'WAITING_LM'})),'STAFF');assert.equal(c.pendingLane71(card('ACCEPT_AND_COUNT',{submit_status:'LM_ACCEPTED'})),'STAFF');assert.equal(c.pendingLane71(card('ACCEPT_AND_COUNT',{submit_status:'COMPLETED'})),null);});
test('assignment is staff, submitted receipt count is staff; initial assigned receipt belongs to worker and submit is worker; no historical read-only cards',()=>{assert.equal(c.pendingLane71(card('ASSIGN_WORKER')),'STAFF');assert.equal(c.pendingLane71(card('CONFIRM_RECEIVED_PCS')),'STAFF');assert.equal(c.pendingLane71(card('CONFIRM_RECEIVED_PCS',{receipt_kind:'ASSIGNED_GOODS'})),'WORKER');assert.equal(c.pendingLane71(card('SUBMIT')),'WORKER');assert.equal(c.pendingLane71(card(null)),null);});
test('ALTER follows current step regardless of viewer permission, not stale legacy label',()=>{for(const next_action of ['LM_ACCEPT','REMAKE_ISSUE','RECEIVE_FROM_MASTER','DELIVER_TO_KARIGAR','RECEIVE_FROM_KARIGAR'])assert.equal(c.pendingLane71(card(null,{journey_id:'j',next_action})),'STAFF');assert.equal(c.pendingLane71(card(null,{journey_id:'j',next_action:'KARIGAR_SUBMIT_GOOD'})),'WORKER');assert.equal(c.pendingLane71(card(null,{journey_id:'j',next_action:'',qty:0})),null);});
test('every production group separates staff and worker; cards never occupy both lanes',()=>{for(const id of ['CUTTING','FABRICATION','PRINTING','STICKER','METAL_ID','STITCHING','OVERLOCK','FOLDING','KAAJ_BUTTON','TEAK_TANKI','THREAD_CUT','QC','PRESS','PACKING','DISPATCH']){c.S.active.id=id;const rows=[card('ACCEPT_AND_COUNT'),card('SUBMIT'),card(null)];c.S.workLane='STAFF';assert.equal(c.laneRows71(rows).length,1);c.S.workLane='WORKER';assert.equal(c.laneRows71(rows).length,1);}});
test('staff and worker controls show exact pending counts and select a separate action list',()=>{const {JSDOM}=require('jsdom'),dom=new JSDOM('<nav id="workFilters"></nav>');const d={...c,document:dom.window.document,$:id=>dom.window.document.getElementById(id),renderActive:()=>{d.renders++},openCardScreen71:()=>{},renders:0,S:{status:'WORKING',workLane:'STAFF',workFilter:'ALTER',active:{kind:'group',id:'FABRICATION'}}};vm.createContext(d);vm.runInContext(s.slice(s.indexOf('function manufacturingLanes71('),s.indexOf('function cbDepartmentContext(')),d);try{d.syncWorkLanes71([card('ACCEPT_AND_COUNT'),card('SUBMIT'),card('SUBMIT'),card(null)]);const buttons=d.document.querySelectorAll('[data-work-lane]');assert.equal(buttons[0].textContent,'STAFF 1');assert.equal(buttons[1].textContent,'WORKER 2');buttons[1].click();assert.equal(d.S.workLane,'WORKER');assert.equal(d.S.workFilter,'ALL');assert.equal(d.renders,1);d.S.status='OPEN';d.syncWorkLanes71([]);assert.equal(d.document.getElementById('workLanes71').hidden,true);}finally{dom.window.close();}});

test('STAFF 19 opens all 19; only populated action filters appear; accept count shows exact 13',()=>{const d={...c,cuttingContext:()=>false,upmContext:()=>false,directSearchMatch:()=>false,S:{status:'WORKING',workLane:'STAFF',workFilter:'READY_TO_SUBMIT',search:'',active:{kind:'group',id:'FABRICATION'}}};vm.createContext(d);vm.runInContext(s.slice(s.indexOf('function workType('),s.indexOf('function syncLaneSummary71(')),d);vm.runInContext(s.slice(s.indexOf('function allowedWorkFilters('),s.indexOf('function syncWorkFilters(')),d);const rows=[...Array.from({length:13},()=>card('ACCEPT_AND_COUNT')),...Array.from({length:6},()=>card('REMAKE_ISSUE',{journey_id:'j',next_action:'REMAKE_ISSUE'}))];assert.equal(d.filterWorking(rows).length,19);assert.equal(d.S.workFilter,'ALL');assert.deepEqual(Array.from(d.allowedWorkFilters(rows)),['ALL','RECEIPT_PENDING','ALTER','RECTIFICATION']);d.S.workFilter='RECEIPT_PENDING';assert.equal(d.filterWorking(rows).length,13);d.S.workFilter='ALTER';assert.equal(d.filterWorking(rows).length,6);});
test('WORKER total opens all seven and breakdown filters show five Submit and two Alter',()=>{const d={...c,cuttingContext:()=>false,upmContext:()=>true,directSearchMatch:()=>false,S:{status:'WORKING',workLane:'WORKER',workFilter:'ALL',search:'',active:{kind:'group',id:'STICKER'}}};vm.createContext(d);vm.runInContext(s.slice(s.indexOf('function workType('),s.indexOf('function syncLaneSummary71(')),d);vm.runInContext(s.slice(s.indexOf('function allowedWorkFilters('),s.indexOf('function syncWorkFilters(')),d);const rows=[...Array.from({length:5},()=>card('SUBMIT')),...Array.from({length:2},()=>card('KARIGAR_SUBMIT_GOOD',{journey_id:'j',next_action:'KARIGAR_SUBMIT_GOOD'}))];assert.equal(d.filterWorking(rows).length,7);assert.deepEqual(Array.from(d.allowedWorkFilters(rows)),['ALL','READY_TO_SUBMIT','ALTER','RECTIFICATION']);d.S.workFilter='READY_TO_SUBMIT';assert.equal(d.filterWorking(rows).length,5);d.S.workFilter='ALTER';assert.equal(d.filterWorking(rows).length,2);});

test('completed atomic handover with stale actions never remains in STAFF or WORKER pending counts',()=>{const row=card('ACCEPT_AND_COUNT',{submit_request_id:'request',accept_count_complete:true});assert.equal(c.pendingLane71(row),null);c.S.workLane='STAFF';assert.equal(c.laneRows71([row]).length,0);c.S.workLane='WORKER';assert.equal(c.laneRows71([row]).length,0);});

test('opening an action filter clears the old cards and old count before loading',()=>{const {JSDOM}=require('jsdom'),dom=new JSDOM('<section id="chat"><div id="messages"><article>Old cards</article></div></section>');const d={document:dom.window.document,$:id=>dom.window.document.getElementById(id),twoScreenContext71:()=>true,S:{activeRenderedSearchRows:[1,2,3,4,5,6]},history:{pushState:()=>{}},currentViewState:()=>({}),location:{href:'https://example.com'},syncCardScreen71:()=>{},window:{}};vm.createContext(d);vm.runInContext(s.slice(s.indexOf('function clearPendingCards71('),s.indexOf('function closeCardScreen71(')),d);d.clearPendingCards71();d.openCardScreen71();assert.equal(d.S.activeRenderedSearchRows.length,0);assert.equal(d.document.querySelectorAll('article').length,0);assert.match(d.document.getElementById('messages').textContent,/load/);dom.window.close();});

test('disputed count remains staff final decision work, never accepted or worker Submit',()=>{assert.equal(c.pendingLane71(card(null,{submit_request_id:'q',submit_status:'DISPUTED',accept_count_complete:false})),'STAFF');});
