const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{JSDOM}=require('jsdom');
test('notification setup removes itself after at most 3 seconds without requesting permission',()=>{
 const html=fs.readFileSync('test70-cb-purchase-real-chat-pilot.html','utf8'),script=html.match(/\(\(\)=>\{function showPushSetup[\s\S]*?\}\)\(\);/)[0];const dom=new JSDOM('<body></body>',{runScripts:'outside-only'}),w=dom.window,jobs=[];w.Notification={permission:'default'};w.setTimeout=(fn,ms)=>{jobs.push({fn,ms});return jobs.length};w.eval(script);w.document.dispatchEvent(new w.Event('DOMContentLoaded'));jobs.find(x=>x.ms===900).fn();assert.ok(w.document.getElementById('rzPushSetupCurrent'));const hide=jobs.find(x=>x.ms===3000);assert.ok(hide);hide.fn();assert.equal(w.document.getElementById('rzPushSetupCurrent'),null);dom.window.close();
});
test('Alter save success refreshes only its queue and never treats history-sync timeout as save failure',async()=>{
 const src=fs.readFileSync('test70-real-chat-live-v70.js','utf8'),start=src.indexOf('async function executeAlterInline('),end=src.indexOf('\nasync function openVendorPopup',start),calls=[],alerts=[];const c={confirm:()=>true,prompt:()=>'',rpc:async n=>{calls.push(n);if(n.includes('sync_e2e'))throw Error('timeout');return {ok:true}},S:Object.fromEntries(['statusCache','queueProjectionCache','alterCustodyCache','chatRenderCache','departmentCountCache'].map(k=>[k,new Map()])),renderActive:async()=>calls.push('refresh'),alert:v=>alerts.push(v),console,err:e=>e.message};vm.createContext(c);vm.runInContext(src.slice(start,end),c);const button={dataset:{alterAction:'KARIGAR_SUBMIT_GOOD',journeyId:'j',alterQty:'1'},textContent:'SUBMIT'};await c.executeAlterInline(button);assert.deepEqual(calls,['rr_chat_alter_action_test71','refresh']);assert.deepEqual(alerts,[]);assert.equal(button.textContent,'SAVED');assert.equal(button.disabled,true);
});
test('periodic active manufacturing refresh avoids global work-search before rendering its queue',async()=>{
 const src=fs.readFileSync('test70-real-chat-live-v70.js','utf8'),start=src.indexOf('async function load(fast=false){'),end=src.indexOf('\nfunction ',start);const c={S:{search:'',departments:[{}],active:{kind:'group',id:'FABRICATION'}},actAsActive:x=>x,renderActive:async a=>a.id};vm.createContext(c);vm.runInContext(src.slice(start,end),c);assert.equal(await c.load(true),'FABRICATION');
});
