const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{JSDOM}=require('jsdom');
const src=fs.readFileSync('test70-real-chat-live-v70.js','utf8');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
function fixture(){
 const dom=new JSDOM('<section id="inbox" hidden></section><section id="chat"><div id="chatName"></div><div id="kind"></div><button id="manageStaffAction"></button><a id="contextAction"></a><nav id="workFilters"><button data-work-filter="RECEIPT_PENDING"></button></nav><div id="messages"></div></section>');const jobs=[];
 const c={document:dom.window.document,window:{},setTimeout,clearTimeout,console,Date,arr:x=>Array.isArray(x)?x:[],safe:x=>String(x??''),$:(id)=>dom.window.document.getElementById(id),S:{active:{kind:'group',id:'FABRICATION',parentDepartment:null},status:'WORKING',userStatusLock:'WORKING',workLane:'STAFF',workFilter:'ALL',navigationSeq:0,chatSeq:0,loadSeq:0,departments:[{department_code:'FABRICATION'}],people:[],cards:[],actor:{role:'ADMIN'},chatRenderCache:new Map(),statusCache:new Map(),activeRenderedSearchRows:[],search:''},history:{replaceState(){},pushState(){}},location:{href:'https://fixture.test/',pathname:'/',search:'',hash:''},currentViewState:()=>({}),viewUrl:()=>'',syncStatusButtons:()=>{},groupQueueRows71:async(_,status)=>{const job=deferred();jobs.push({status,...job});return job.promise},mergeQueueIdentity71:async r=>r,mergeCraftIdentityV634:async r=>r,wireRectificationCards71:async r=>r,operationalRowsVisible:r=>r,membershipAdminRole:()=>true,expandedClosedCardKeys:()=>new Set(),restoreExpandedClosedCards:()=>{},card:r=>'<article data-lot="'+r.lot_no+'">'+r.lot_no+'</article>',adminPurchaseAlertsV692:async()=>'',emptyStateV705:()=>'<p>No pending cards</p>',requestAnimationFrame:()=>{},highlightMatches:()=>{},bindMedia:()=>{},bindAccessoryControlsV694:async()=>{},focusSearchCard:()=>{},installRateFocusGuard:()=>{},ensureEmptyStateV708:()=>{},pushCurrentView:()=>{},focusAssignmentCard:()=>{},focusCbCard:()=>{},RR_PRODUCTION_DEPARTMENTS_V763:new Set(['PRINTING']),load:()=>{throw Error('Global load must not gate this queue')},focusSearchCard:()=>{},rpc:async()=>({})};vm.createContext(c);
 for(const [a,b] of [['function beginQueueView71(','async function wireRectificationCards71('],['function manufacturingLanes71(','function syncWorkLanes71('],['function renderActive(','function statusProjectionKey('],['async function openChat(kind,','function restoreView(']]){const start=src.indexOf(a),end=src.indexOf(b,start);assert.ok(start>=0&&end>start,a);vm.runInContext(src.slice(start,end),c);}
 const start=src.indexOf('function changeStatus(');vm.runInContext(src.slice(start,src.indexOf('\n',start)),c);c.syncWorkLanes71=()=>{};c.syncWorkFilters=()=>{};c.syncLaneSummary71=()=>{};c.filterWorking=r=>r;c.cardHasOperationalAction=r=>r.actions?.length>0;
 return {c,dom,jobs};
}
test('Open ready-to-assign and Working final-decision cards survive lifecycle filtering',()=>{const f=fixture();try{assert.equal(f.c.queueLifecycleVisible71({resolved_work_state:'READY_TO_ASSIGN'},'OPEN'),true);assert.equal(f.c.queueLifecycleVisible71({resolved_work_state:'WORKING'},'OPEN'),false);assert.equal(f.c.queueLifecycleVisible71({resolved_work_state:'DECISION_PENDING'},'WORKING'),true);}finally{f.dom.window.close()}});
test('Working → Open → Working ignores late results, clears wrong counts immediately and renders without global load',async()=>{const f=fixture(),{c,jobs}=f;try{
 const first=c.openChat('group','FABRICATION',false);c.changeStatus('OPEN');assert.equal(jobs.length,2);assert.equal(c.S.activeRenderedSearchRows.length,0);assert.equal(c.$('openCards71').hidden,true);assert.equal(c.$('queueState71').hidden,false);
 jobs[0].resolve([{lot_no:'OLD WORK',resolved_work_state:'WORKING',actions:[{code:'ACCEPT_AND_COUNT'}]}]);await first;assert.equal(c.document.querySelectorAll('article').length,0);
 jobs[1].resolve([{lot_no:'OPEN LOT',resolved_work_state:'READY_TO_ASSIGN',actions:[{code:'ASSIGN_WORKER'}]}]);await new Promise(r=>setImmediate(r));assert.equal(c.$('openCards71').textContent,'ASSIGN बाकी · 1');assert.equal(c.$('openCards71').hidden,false);assert.equal(c.$('queueState71').hidden,true);
 c.changeStatus('WORKING');assert.equal(c.$('openCards71').hidden,true);assert.equal(c.S.activeRenderedSearchRows.length,0);jobs[2].resolve([{lot_no:'WORK LOT',resolved_work_state:'WORKING',actions:[{code:'ACCEPT_AND_COUNT'}]}]);await new Promise(r=>setImmediate(r));assert.equal(c.S.activeRenderedSearchRows.length,1);assert.equal(c.document.querySelector('article').textContent,'WORK LOT');assert.equal(c.$('openCards71').hidden,true);
 }finally{f.dom.window.close()}});
test('projection failure is visible with Retry instead of empty forever',async()=>{const f=fixture();try{f.c.beginQueueView71();f.c.renderActive();f.jobs[0].reject(Error('offline'));await new Promise(r=>setImmediate(r));assert.match(f.c.$('queueState71').textContent,/RETRY/);f.c.$('queueState71').querySelector('button').click();assert.equal(f.jobs.length,2);f.jobs[1].resolve([]);await new Promise(r=>setImmediate(r));assert.equal(f.c.$('queueState71').hidden,true);}finally{f.dom.window.close()}});
test('root and chat share one in-flight queue; timeout clears entry and retry starts fresh',async()=>{const timers=[],jobs=[],c={window:{},S:{actor:{},queueProjectionCache:new Map()},setTimeout:fn=>{timers.push(fn);return timers.length},clearTimeout:()=>{},groupQueueRowsFresh71:()=>{const j=deferred();jobs.push(j);return j.promise}};vm.createContext(c);vm.runInContext(src.slice(src.indexOf('async function groupQueueRows71('),src.indexOf('async function groupQueueRowsFresh71(')),c);const first=c.groupQueueRows71('FABRICATION','WORKING'),second=c.groupQueueRows71('FABRICATION','WORKING');assert.equal(jobs.length,1);timers[0]();await assert.rejects(first,/timed out/);await assert.rejects(second,/timed out/);const retry=c.groupQueueRows71('FABRICATION','WORKING');assert.equal(jobs.length,2);jobs[1].resolve([{lot_no:'new'}]);assert.equal((await retry)[0].lot_no,'new');jobs[0].resolve([{lot_no:'old'}]);assert.equal((await c.groupQueueRows71('FABRICATION','WORKING'))[0].lot_no,'new');});
test('slow Art enrichment does not block cards or rerender another tab',async()=>{const job=deferred(),timers=[],rows=[{lot_no:'pending'}];let renders=0;const c={S:{chatSeq:1,status:'WORKING'},mergeCraftIdentityV634:()=>job.promise,setTimeout:fn=>{timers.push(fn);return 1},clearTimeout:()=>{},renderActive:()=>renders++,console};vm.createContext(c);vm.runInContext(src.slice(src.indexOf('async function mergeQueueIdentity71('),src.indexOf('async function groupQueueRows71(')),c);const shown=c.mergeQueueIdentity71(rows);timers[0]();assert.equal(await shown,rows);c.S.status='OPEN';c.S.chatSeq++;job.resolve([{lot_no:'enriched'}]);await new Promise(r=>setImmediate(r));assert.equal(renders,0);});
