begin;
do $test$
declare actor uuid; profile uuid; cid uuid; other_cid uuid; chat uuid; wrong_chat uuid; cname text:='TEST71 PI RECEIPT '||gen_random_uuid(); r jsonb; ctx jsonb; pid uuid; oldfp text; pages jsonb; rejected boolean; stock record; resend_key uuid:=gen_random_uuid(); rid uuid;
begin
 select auth_user_id,id into actor,profile from rr_user_profiles where role_code='owner' and is_active and upper(coalesce(access_status,'ACTIVE'))='ACTIVE' limit 1;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 insert into rr_customers(customer_name) values(cname) returning id into cid;
 insert into rr_customers(customer_name) values(cname||' OTHER') returning id into other_cid;
 select id into chat from rr_customer_chat_v9433 where customer_id=cid and data_mode='TEST' and relation_kind='DIRECT_CUSTOMER';
 select id into wrong_chat from rr_customer_chat_v9433 where customer_id=other_cid and data_mode='TEST' and relation_kind='DIRECT_CUSTOMER';
 insert into rr_customer_chat_members_v9433(chat_id,profile_id,is_active) values(chat,profile,true),(wrong_chat,profile,true) on conflict do nothing;
 r:=rr_fg_save_pi_value_adjustment_test71(null,cname,'DELIVER','[{"lot_no":"RECEIPT-A","stock_type":"REGULAR","qty":2,"rate":100}]',5,-1);
 pid:=(r->>'pi_id')::uuid;
 ctx:=rr_pi_customer_document_test71(pid,chat);oldfp:=ctx->>'fingerprint';
 if (ctx->'document'->>'grand_total')::numeric<>(r->>'grand_total')::numeric or (ctx->'document'->'lines'->0->>'net_rate')::numeric<>95 then raise exception 'Receipt differs from saved bill'; end if;
 if (ctx->'document')::text ilike '%discount%' or (ctx->'document')::text ilike '%gross_rate%' or (ctx->'document')::text ilike '%original_rate%' or (ctx->'document')::text ilike '%godown%' or (ctx->'document')::text ilike '%rrq%' or (ctx->'document')::text ilike '%approved_rate%' then raise exception 'Private fields leaked'; end if;
 pages:=jsonb_build_array(jsonb_build_object('base64','/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAACAAIDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiigD//2Q=='),jsonb_build_object('base64','/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAACAAIDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiigD//2Q=='));
 r:=rr_pi_customer_document_send_test71(pid,chat,oldfp,pages);
 if not (r->>'sent')::boolean then raise exception 'Not sent'; end if;
 if (select count(*) from rr_customer_chat_messages_v9433 where chat_id=chat)<>2 or (select count(*) from rr_customer_chat_attachments_v9434 where chat_id=chat)<>2 then raise exception 'JPG pages not atomically attached'; end if;
 if (select count(*) from rr_chat_push_outbox_v61 where chat_id=chat)<>1 then raise exception 'Expected one phone notification per bill'; end if;
 r:=rr_pi_customer_document_send_test71(pid,chat,oldfp,'[]');
 if not (r->>'already_sent')::boolean or (select count(*) from rr_customer_chat_messages_v9433 where chat_id=chat)<>2 or (select count(*) from rr_chat_push_outbox_v61 where chat_id=chat)<>1 then raise exception 'Retry duplicated delivery/push'; end if;
 rejected:=false;
 begin perform rr_pi_customer_document_send_test71(pid,wrong_chat,oldfp,pages);
 exception when others then if sqlerrm like 'Matching party chat%' then rejected:=true; else raise; end if; end;
 if not rejected then raise exception 'Wrong party accepted'; end if;
 update rr_fg_pi_v787 set grand_total=grand_total+10 where id=pid;
 rejected:=false;
 begin perform rr_pi_customer_document_send_test71(pid,chat,oldfp,pages);
 exception when others then if sqlerrm like 'PI changed%' then rejected:=true; else raise; end if; end;
 if not rejected then raise exception 'Stale receipt accepted'; end if;
 ctx:=rr_pi_customer_document_test71(pid,chat);
 r:=rr_pi_customer_document_send_test71(pid,chat,ctx->>'fingerprint',jsonb_build_array(pages->0));
 if (select count(*) from rr_chat_push_outbox_v61 where chat_id=chat)<>2 then raise exception 'Changed bill notification missing'; end if;
 select * into stock from rr_fg_stock_balance_v787 where data_mode='TEST' and stock_type='REGULAR' and available_qty>=1 limit 1;
 if not found then raise exception 'CI stock fixture required'; end if;
 r:=rr_fg_save_pi_value_adjustment_test71(null,cname,'CI',jsonb_build_array(jsonb_build_object('lot_no',stock.lot_no,'stock_type','REGULAR','qty',1,'rate',100)),null,-1,0,0,0,true,'TEST');
 pid:=(r->>'pi_id')::uuid;ctx:=rr_pi_customer_document_test71(pid,chat);
 if ctx->'document'->>'document_kind'<>'CI' then raise exception 'CI receipt mislabelled'; end if;
 r:=rr_pi_customer_document_send_test71(pid,chat,ctx->>'fingerprint',jsonb_build_array(pages->0));
 if (select count(*) from rr_chat_push_outbox_v61 where chat_id=chat)<>3 then raise exception 'CI notification missing'; end if;
-- Explicit resend creates one new notification, and retries of that request stay idempotent.
 r:=rr_pi_customer_document_resend_test71(pid,chat,ctx->>'fingerprint',jsonb_build_array(pages->0),resend_key);
 r:=rr_pi_customer_document_resend_test71(pid,chat,ctx->>'fingerprint','[]',resend_key);
 if not (r->>'already_sent')::boolean or (select count(*) from rr_chat_push_outbox_v61 where chat_id=chat)<>4 then raise exception 'Resend retry duplicated push'; end if;
 insert into rr_rci_v9740(rci_no,flow_type,linked_ci_id,buyer_id,buyer_snapshot,status,total_qty,total_amount,reason,data_mode,created_by,idempotency_key)
 select 'TEST-RECEIPT-'||gen_random_uuid(),'COMBINED',id,buyer_id,buyer_snapshot,'POSTED',1,95,'Receipt rollback fixture','TEST',actor,gen_random_uuid()::text from rr_fg_pi_v787 where id=pid returning id into rid;
 insert into rr_rci_lines_v9740(rci_id,serial_no,return_type,source_ci_id,source_ci_line_id,original_lot_no,stock_lot_no,category_name,size_text,total_sold_qty,previous_rci_qty,returnable_qty,rci_qty,rate,amount,stock_type,location_code,valuation_source)
 select rid,1,'KNOWN',pid,id,lot_no,lot_no,'SHIRT','L',1,0,1,1,95,95,'REGULAR','MAIN','CI_RATE' from rr_fg_pi_lines_v787 where pi_id=pid limit 1;
 ctx:=rr_rci_customer_document_test71(rid,chat);
 if (ctx->'document')::text ilike '%discount%' or (ctx->'document')::text ilike '%gross_rate%' then raise exception 'RCI internal rates leaked'; end if;
 if ctx->'document'->>'document_kind'<>'RCI' or (ctx->'document'->>'grand_total')::numeric<>95 then raise exception 'RCI wrong receipt'; end if;
 r:=rr_rci_customer_document_send_test71(rid,chat,ctx->>'fingerprint',pages);
 r:=rr_rci_customer_document_send_test71(rid,chat,ctx->>'fingerprint','[]');
 if not (r->>'already_sent')::boolean or (select count(*) from rr_chat_push_outbox_v61 where chat_id=chat)<>5 then raise exception 'RCI retry / multi-page push incorrect'; end if;
rejected:=false;
 begin perform rr_rci_customer_document_test71(rid,wrong_chat);
 exception when others then if sqlerrm like 'Matching party chat%' then rejected:=true; else raise; end if; end;
 if not rejected then raise exception 'Wrong RCI party accepted'; end if;
 update rr_rci_v9740 set linked_ci_id=null,flow_type='STANDALONE' where id=rid;
 ctx:=rr_rci_customer_document_test71(rid,chat);
 if (ctx->>'chat_id')::uuid<>chat or ctx->'document'->>'document_kind'<>'RCI' then raise exception 'Standalone mapping failed'; end if;
end $test$;
rollback;
