const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');
const history=[{kind:'COLLECTION',update_no:0,lots:['LOT-A'],created_at:'2026-10-04T12:00:00Z'},{kind:'REQUIREMENT',update_no:0,total_qty:36,lot_count:1,collection_update_no:0,created_at:'2026-10-04T12:01:00Z'},...Array.from({length:12},(_,i)=>({kind:'COLLECTION',update_no:i+1,lots:['LOT-'+(i+1)],requirement_update_no:0,created_at:'2026-10-04T12:02:00Z'}))];
(async()=>{const browser=await chromium.launch({args:['--no-sandbox']});try{
 for(const staff of [false,true]){
  const page=await browser.newPage({viewport:{width:393,height:820},hasTouch:true,isMobile:true});await page.route('**/*',r=>r.fulfill({body:'<html></html>',contentType:'text/html'}));await page.goto('https://fixture.test/'+(staff?'real-sales-live-chat-v9434.html?chat_id=chat':'s.html?t=fixture'));
  await page.setContent(staff?'<div id="inboxRows"><div class="chatrow on" data-chat="chat"></div></div><div id="msgs"><div class="msg" data-msg-id="req"><button class="rrReqCard9508">OPEN REQUIREMENT</button></div><div class="msg" data-msg-id="col">Collection link update</div><div class="msg" data-msg-id="note">Ordinary message</div></div>':'<div id="fsCollectionCard"><button id="fcOpen">UPDATE COLLECTION</button></div><div id="rrCommercialActions9630"><button id="rrSendReq9630">SEND</button><button id="rrCloseReq9630">CLOSE</button></div><div id="fsMsgs"><div class="fsm" data-rr-cycle71="cycle" data-rr-workflow71="1">Collection link update</div><div class="fsm" id="ordinary">Ordinary message</div></div>');
  await page.evaluate(h=>{window.fixtureState={collection_cycle_id:'cycle',collection_display_no:'RZ COLLECTION 01',collection_update_no:12,requirement_response_collection_update_no:0,update_history:h};window.RF853={rpc:async name=>name==='rr_collection_customer_requirement_summary_v9637'?{lines:[{requested_qty:36}]}:name.includes('messages')?[{id:'req',payload:{source:'DIRECT_MARKET_REQUIREMENT',direct_collection_cycle_id:'cycle'}},{id:'col',payload:{source:'DIRECT_MARKET_WINDOW',direct_collection_cycle_id:'cycle'}}]:window.fixtureState};},history);
  await page.addScriptTag({path:path.resolve('real-direct-cycle-history-test71.js')});
  if(!staff)await page.addScriptTag({path:path.resolve('real-customer-cycle-state-v9675.js')});
  if(staff)await page.evaluate(()=>RF853.rpc('rr_chat_staff_messages_v9434',{}));
  await page.locator('.rrCycleHistory71').waitFor();await page.waitForTimeout(200);
  assert.equal(await page.locator('.rrCycleHistory71').count(),1);assert.equal(await page.locator('.rrCycleHistory71 details').count(),14);assert.match(await page.locator('.rrCycleHistory71').innerText(),/UPDATE 12/);
  await page.getByText('COLLECTION · UPDATE 12',{exact:true}).tap();assert.match(await page.locator('.rrCycleHistory71').innerText(),/LOT-12/);
  assert.equal(await page.getByText('Collection link update',{exact:true}).isVisible(),false);assert.equal(await page.getByText('Ordinary message',{exact:true}).isVisible(),true);
  await page.evaluate(()=>{window.mutations=0;new MutationObserver(ms=>window.mutations+=ms.length).observe(document.body,{childList:true,subtree:true});});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>window.mutations),0);
  if(!staff){assert.equal(await page.locator('#fcOpen').isEnabled(),true);assert.equal(await page.locator('#rrSendReq9630').isEnabled(),true);await page.evaluate(async()=>{window.fixtureState.requirement_response_collection_update_no=12;await RF853.rpc('rr_collection_current_state_v9633',{});});await page.waitForTimeout(100);assert.equal(await page.locator('#rrSendReq9630').isEnabled(),false);await page.evaluate(()=>document.querySelector('#fsCollectionCard').innerHTML='<button>Sent</button>');await page.locator('.rrCycleHistory71').waitFor();assert.equal(await page.locator('.rrCycleHistory71').count(),1);}
  await page.close();
 }
 console.log('PASS: customer/staff one consolidated history through Update 12; expandable lots and confirmations; workflow bubble hidden, normal message intact; DOM settles; history survives card replacement.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
