const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {JSDOM}=require('jsdom');
for(const transport of ['RF853','supabaseClient'])test(transport+': header and department bubbles count messages; only visible exact card is read',async()=>{
 const dom=new JSDOM('<section id="inbox"><header class="head"><h1>Real Chat</h1></header><div id="rows"><button data-department="ADMIN"><b>Admin</b></button><button data-department="SALES"><b>Sales</b></button></div></section><section id="chat" hidden><div id="messages"><article data-event-key="event-1"></article></div></section>',{url:'https://example.test/test70-cb-purchase-real-chat-pilot.html?rc_notice=n1',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
 let rows=[{id:'n1',department_code:'ADMIN',event_key:'event-1',route_url:'test70-cb-purchase-real-chat-pilot.html?rc_status=OPEN',title:'One'},{id:'n2',department_code:'ADMIN',event_key:'event-2',route_url:'test70-cb-purchase-real-chat-pilot.html?rc_status=OPEN',title:'Two'}],context={kind:'inbox'},read=[],scrolled=0;
 w.setTimeout=()=>0;w.setInterval=()=>0;w.RF853={rpc:async(name,args)=>{if(name==='rr_chat_notification_inbox_test71')return rows;if(name==='rr_chat_staff_unread_test71')return [{chat_id:'c',unread_count:3}];if(name==='rr_chat_notification_read_test71'){read.push(...args.p_ids);rows=rows.filter(n=>!args.p_ids.includes(n.id));return args.p_ids.length}throw Error(name)}};if(transport==='supabaseClient'){const call=w.RF853.rpc;delete w.RF853;w.supabaseClient={rpc:async(name,args)=>({data:await call(name,args),error:null})};}w.RRAdminApprovalHost71={context:()=>context};
 w.eval(fs.readFileSync('real-chat-inbox-summary-test71.js','utf8'));await w.RRChatNotifications71.refresh();
 const count=selector=>w.document.querySelector(selector+' .rrMsgBubble71')?.textContent;
 assert.equal(count('h1'),'5');assert.equal(count('[data-department="ADMIN"]'),'2');assert.equal(count('[data-department="SALES"]'),'3');assert.deepEqual(read,[]);
 context={kind:'group',id:'ADMIN',status:'OPEN'};const chat=w.document.getElementById('chat');chat.hidden=false;chat.getBoundingClientRect=()=>({top:0,bottom:500});const card=w.document.querySelector('[data-event-key]');card.getBoundingClientRect=()=>({top:100,bottom:200});card.scrollIntoView=()=>scrolled++;
 await w.RRChatNotifications71.visible();assert.deepEqual(read,['n1']);assert.equal(scrolled,1);assert.equal(count('h1'),'4');assert.equal(count('[data-department="ADMIN"]'),'1');await w.RRChatNotifications71.refresh();assert.equal(count('h1'),'4');dom.window.close();
});
