const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {JSDOM}=require('jsdom');
for(const key of ['assignment_id','submit_request_id'])test('UPM '+key+': focus exact card and preserve same-lot sibling unread',async()=>{
 const dom=new JSDOM('<section id="chat"><div id="messages"><article class="work-card" data-notice-lot="SAME" data-assignment-id="other" data-submit-request-id="other"><h2>Other</h2></article><article data-assignment-id="wanted" data-submit-request-id="wanted"><h2>Target</h2></article></div></section>',{url:'https://example.test/?rc_notice=n',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,read=[];
 w.setTimeout=w.setInterval=()=>0;w.RRAdminApprovalHost71={context:()=>({kind:'group',id:'FOLDING',status:'OPEN'})};w.RF853={rpc:async(name,args)=>name==='rr_chat_notification_inbox_test71'?[{id:'n',department_code:'FOLDING',lot_no:'SAME',[key]:'wanted',route_url:'?rc_status=OPEN'},{id:'missing',department_code:'FOLDING',lot_no:'SAME',[key]:'missing',route_url:'?rc_status=OPEN'}]:name==='rr_chat_staff_unread_test71'?[]:(read.push(...args.p_ids),args.p_ids.length)};
 w.document.getElementById('chat').getBoundingClientRect=()=>({top:0,bottom:500});for(const c of w.document.querySelectorAll('article')){c.getBoundingClientRect=()=>({top:100,bottom:200});c.scrollIntoView=()=>{};}
 try{w.eval(fs.readFileSync('real-chat-inbox-summary-test71.js','utf8'));await w.RRChatNotifications71.refresh();assert.deepEqual(read,['n']);assert.equal(w.document.activeElement.dataset.assignmentId,'wanted');assert.equal(w.document.querySelector('[data-assignment-id="other"]').classList.contains('rrNoticeFocus71'),false);}finally{w.close()}
});
test('stale UPM notice redirects to current status with exact personal context',async()=>{
 const dom=new JSDOM('<div id="messages"></div>'),w=dom.window,location={href:'https://example.test/?rc_notice=n',search:'?rc_notice=n',replace:u=>location.redirect=u};w.setTimeout=w.setInterval=()=>0;w.RRAdminApprovalHost71={context:()=>({kind:'person',id:'worker',parentDepartment:'FOLDING',status:'OPEN'})};w.RF853={rpc:async name=>name==='rr_chat_notification_inbox_test71'?[{id:'n',department_code:'FOLDING',route_url:'?rc_kind=group&rc_id=FOLDING&rc_parent=FOLDING&rc_status=WORKING'}]:[]};
 try{require('node:vm').runInNewContext(fs.readFileSync('real-chat-inbox-summary-test71.js','utf8'),{window:w,document:w.document,navigator:w.navigator,location,URL,URLSearchParams,setTimeout:()=>0,setInterval:()=>0,console});await w.RRChatNotifications71.refresh();const u=new URL(location.redirect);for(const [k,v]of Object.entries({rc_kind:'person',rc_id:'worker',rc_parent:'FOLDING',rc_status:'WORKING',rc_notice:'n'}))assert.equal(u.searchParams.get(k),v);}finally{w.close()}
});
for(const transport of ['RF853','supabaseClient'])test(transport+': header and department bubbles count messages; only visible exact card is read',async()=>{
 const dom=new JSDOM('<section id="inbox"><header class="head"><h1>Real Chat</h1></header><div id="rows"><button data-department="ADMIN"><b>Admin</b></button><button data-department="SALES"><b>Sales</b></button></div></section><section id="chat" hidden><div id="messages"><article data-event-key="event-1"></article></div></section>',{url:'https://example.test/test70-cb-purchase-real-chat-pilot.html?rc_notice=n1',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
 let rows=[{id:'n1',department_code:'ADMIN',event_key:'event-1',route_url:'test70-cb-purchase-real-chat-pilot.html?rc_status=OPEN',title:'One'},{id:'n2',department_code:'ADMIN',event_key:'event-2',route_url:'test70-cb-purchase-real-chat-pilot.html?rc_status=OPEN',title:'Two'}],context={kind:'inbox'},read=[],scrolled=0;
 w.setTimeout=()=>0;w.setInterval=()=>0;w.RF853={rpc:async(name,args)=>{if(name==='rr_chat_notification_inbox_test71')return rows;if(name==='rr_chat_staff_unread_test71')return [{chat_id:'c',unread_count:3}];if(name==='rr_chat_notification_read_test71'){read.push(...args.p_ids);rows=rows.filter(n=>!args.p_ids.includes(n.id));return args.p_ids.length}throw Error(name)}};if(transport==='supabaseClient'){const call=w.RF853.rpc;delete w.RF853;w.supabaseClient={rpc:async(name,args)=>({data:await call(name,args),error:null})};}w.RRAdminApprovalHost71={context:()=>context};
 w.eval(fs.readFileSync('real-chat-inbox-summary-test71.js','utf8'));await w.RRChatNotifications71.refresh();
 const count=selector=>w.document.querySelector(selector+' .rrMsgBubble71')?.textContent;
 assert.equal(count('h1'),'5');assert.equal(count('[data-department="ADMIN"]'),'2');assert.equal(count('[data-department="SALES"]'),'3');assert.deepEqual(read,[]);
 context={kind:'group',id:'ADMIN',status:'OPEN'};const chat=w.document.getElementById('chat');chat.hidden=false;chat.getBoundingClientRect=()=>({top:0,bottom:500});const card=w.document.querySelector('[data-event-key]');card.getBoundingClientRect=()=>({top:100,bottom:200});card.scrollIntoView=()=>scrolled++;
 await w.RRChatNotifications71.visible();assert.deepEqual(read,['n1']);assert.equal(scrolled,1);assert.equal(count('h1'),'4');assert.equal(count('[data-department="ADMIN"]'),'1');await w.RRChatNotifications71.refresh();assert.equal(count('h1'),'4');dom.window.close();
});

for(const role of ['LINE_MAN','MANAGER','ADMIN','ACCOUNTS','SALES','SUPER_ADMIN','WORKER'])test(role+': personal rows and cards retain other workers unread and ignore wrong status',async()=>{
 const dom=new JSDOM('<section id="inbox"><header class="head"><h1>Real Chat</h1></header><button data-department="FOLDING"><b>Folding</b></button></section><section id="chat"><div id="messages"><button data-person="worker-a"><b>A</b></button><button data-person="worker-b"><b>B</b></button><article data-event-key="event-a"><h2>A</h2></article><article data-event-key="event-b"><h2>B</h2></article></div></section>',{url:'https://example.test/test70-cb-purchase-real-chat-pilot.html?rc_notice=a',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
 const read=[],posted=[];let context={kind:'department',id:'FOLDING',status:'OPEN',role},rows=['a','b'].map(id=>({id,event_key:'event-'+id,department_code:'FOLDING',worker_ids:['worker-'+id],route_url:'test70-cb-purchase-real-chat-pilot.html?rc_status=OPEN'}));
 w.setTimeout=w.setInterval=()=>0;w.RRAdminApprovalHost71={context:()=>context};w.RF853={rpc:async(name,args)=>{if(name==='rr_chat_notification_inbox_test71')return rows;if(name==='rr_chat_staff_unread_test71')return [];read.push(...args.p_ids);rows=rows.filter(n=>!args.p_ids.includes(n.id));return args.p_ids.length}};
 Object.defineProperty(w.navigator,'serviceWorker',{value:{controller:{postMessage:m=>posted.push(m)}}});
 try{w.eval(fs.readFileSync('real-chat-inbox-summary-test71.js','utf8'));await w.RRChatNotifications71.refresh();assert.equal(w.document.querySelector('[data-person="worker-a"] .rrMsgBubble71').textContent,'1');assert.equal(w.document.querySelector('[data-person="worker-b"] .rrMsgBubble71').textContent,'1');
 const chat=w.document.getElementById('chat');chat.getBoundingClientRect=()=>({top:0,bottom:500});for(const c of w.document.querySelectorAll('article')){c.getBoundingClientRect=()=>({top:100,bottom:200});c.scrollIntoView=()=>{};}
 context={kind:'person',id:'worker-a',parentDepartment:'FOLDING',status:'WORKING',role};await w.RRChatNotifications71.visible();assert.deepEqual(read,[]);
 context.status='OPEN';w.RRChatNotifications71.paint();assert.equal(w.document.querySelector('[data-event-key="event-a"] .rrMsgBubble71').textContent,'1');assert.equal(w.document.querySelector('[data-event-key="event-b"] .rrMsgBubble71'),null);
 await w.RRChatNotifications71.visible();assert.deepEqual(read,['a']);assert.equal(w.document.activeElement.dataset.eventKey,'event-a');assert.equal(posted[0].type,'RZ_NOTICE_READ71');await w.RRChatNotifications71.refresh();assert.equal(w.document.querySelector('h1 .rrMsgBubble71').textContent,'1');assert.equal(w.document.querySelector('[data-person="worker-b"] .rrMsgBubble71').textContent,'1');
 }finally{w.close()}
});

test('personal unread bubble navigates to exact worker, department, status and notice',async()=>{
 const dom=new JSDOM('<div id="messages"><button data-person="worker-a"><b>A</b></button></div>'),w=dom.window,location={href:'https://example.test/test70-cb-purchase-real-chat-pilot.html',search:''};w.RRAdminApprovalHost71={context:()=>({kind:'department',id:'FOLDING'})};w.RF853={rpc:async name=>name==='rr_chat_notification_inbox_test71'?[{id:'notice-a',worker_ids:['worker-a'],department_code:'FOLDING',route_url:'test70-cb-purchase-real-chat-pilot.html?rc_status=WORKING&rc_bridge=bridge-a'}]:[]};
 try{require('node:vm').runInNewContext(fs.readFileSync('real-chat-inbox-summary-test71.js','utf8'),{window:w,document:w.document,navigator:w.navigator,location,URL,URLSearchParams,setTimeout:()=>0,setInterval:()=>0,console});await w.RRChatNotifications71.refresh();w.document.querySelector('.rrMsgBubble71').click();const u=new URL(location.href);for(const [key,value]of Object.entries({rc_kind:'person',rc_id:'worker-a',rc_parent:'FOLDING',rc_status:'WORKING',rc_notice:'notice-a',rc_bridge:'bridge-a'}))assert.equal(u.searchParams.get(key),value);}finally{w.close()}
});
