const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('test70-real-chat-live-v70.js','utf8');
function fixture(role,worker='other'){const c={S:{actor:{role,worker_id:worker},active:{kind:'group',id:'QC'},status:'WORKING'},window:{},document:{querySelector:()=>null},arr:x=>Array.isArray(x)?x:[],safe:x=>String(x??''),nasimRateAccess:()=>false,INLINE_ACTIONS:new Set(),actionHref:a=>a.href||'#'};vm.createContext(c);vm.runInContext(source.split('\n').find(l=>l.startsWith('function actionButtons(')),c);return c;}
const card={event_key:'card',canonical_lot_id:'lot',lot_no:'2640',department_code:'QC',worker_id:'assigned',receipt_status:'CONFIRMED',resolved_work_state:'WORKING',actions:['SUBMIT','ALTER','RECTIFICATION']};
test('assigned worker, Manager, Admin and Super Admin get all three buttons with exact worker identity',()=>{for(const [role,worker] of [['WORKER','assigned'],['MANAGER','manager'],['ADMIN','admin'],['SUPER_ADMIN','owner']]){const html=fixture(role,worker).actionButtons(card);for(const key of ['data-chat-submit','data-chat-alter','data-chat-rectify'])assert.ok(html.includes(key),role+' '+key);assert.ok(decodeURIComponent(html).includes('"worker_id":"assigned"'));}});
test('unrelated worker cannot act; unaccepted assignment cannot Submit',()=>{assert.equal(fixture('WORKER').actionButtons(card),'');assert.ok(!fixture('MANAGER').actionButtons({...card,receipt_status:'PENDING'}).includes('data-chat-submit'));});
test('management Submit uses target-worker RPC; context never falls back to another worker',()=>{assert.ok(source.includes("rpc('rr_chat_submit_worker_test71',{p_worker_id:c.worker_id"));assert.ok(!source.includes('mine.length?mine:arr(context?.rows)'));assert.ok(source.includes("['CONFIRMED','CONFIRMED_SHORT','LEGACY_NO_RECEIPT']"));});
test('worker selection keeps overview; action counts open the separate cards page',()=>{const lane=source.slice(source.indexOf('function syncWorkLanes71('),source.indexOf('function syncLaneSummary71('));assert.ok(!lane.includes('openCardScreen71();'));assert.ok(lane.includes('S.cardScreen=false;'));});
test('Rectify uses actual cases and final accounting instead of normal Submit',async()=>{const c={S:{status:'WORKING',actor:{role:'MANAGER',worker_id:'manager'}},twoScreenContext71:()=>true,arr:x=>Array.isArray(x)?x:[],rpc:async()=>[{id:'case',status:'IN_PROGRESS',canonical_lot_id:'lot',lot_no:'2640',target_department_code:'QC',assigned_worker_id:'assigned',recalled_good_qty:8,colour_code:'RED'}]};vm.createContext(c);vm.runInContext(source.slice(source.indexOf('async function wireRectificationCards71('),source.indexOf('async function openChatRectify71(')),c);const out=await c.wireRectificationCards71([{canonical_lot_id:'lot',department_code:'QC',worker_id:'assigned',colour_code:'RED',actions:[{code:'SUBMIT'}]}],'group','QC');assert.equal(out.length,1);assert.equal(out[0].work_category,'RECTIFICATION');assert.equal(out[0].actions[0].code,'RECTIFICATION_CLOSE');assert.ok(out[0].actions[0].href.endsWith('case_id=case'));assert.equal(out[0].qty,8);});
