begin;
select public.rr_fg_assert_user_v787();
do $$
declare j jsonb;pid uuid;sid uuid;lot text:='RM-AUDIT-'||substr(gen_random_uuid()::text,1,8);base numeric;bal0 numeric;bal1 numeric;piid uuid;lineid uuid;ret jsonb;qty numeric;party text:='RM AUDIT CUSTOMER';rciid uuid;
begin
 j:=public.rr_rm_purchase_save_test71(null,'RM Audit Supplier','RM-AUDIT-'||lot,date '2030-01-15',jsonb_build_array(jsonb_build_object('lot_no',lot,'item_name','Readymade audit garment','qty',100,'purchase_rate',100,'markup_mode','ALTERNATE_16','final_image_url','https://example.com/audit.jpg')),true);
 pid:=(j->>'purchase_id')::uuid;
 select stock_id into sid from public.rr_rm_stock_v849_2c6 where source_purchase_id=pid;
 if (select markup_per_pc from public.rr_rm_stock_v849_2c6 where stock_id=sid)<>22 then raise exception 'Fixed owner margin failed';end if;
 if (select count(*) from public.rr_account_transactions_v805 where source_module='READYMADE_PURCHASE' and source_record_id=pid::text)<>1 then raise exception 'Purchase account missing';end if;
 perform public.rr_rm_purchase_post_v849_2c6(pid);
 if (select count(*) from public.rr_fg_stock_ledger_v787 where ref_id=sid and txn_type='READYMADE_PURCHASE_IN')<>1 then raise exception 'Purchase duplicate stock';end if;
 perform public.rr_rm_overhead_save_test71('ELECTRICITY_EXPENSE',date '2030-01-01',1000,'ALL');
 if (select sale_rate from public.rr_web_window_cards_v9329(lot,null,null,'TEST',10,0) where lot_no=lot) is not null then raise exception 'Market published unapproved rate';end if;
 if (select primary_image_url from public.rr_web_window_cards_v9329(lot,null,null,'TEST',10,0) where lot_no=lot) is distinct from 'https://example.com/audit.jpg' then raise exception 'Market thumbnail missing';end if;
 j:=public.rr_rm_costing_test71(lot,'TEST');
 if not (j->>'costing_complete')::boolean then raise exception 'Costing pending: %',j;end if;
 if (j->>'owner_margin_per_pc')::numeric<>22 then raise exception 'Owner private margin snapshot missing';end if;
 base:=(j->>'source_rate')::numeric;
 select coalesce(balance,0) into bal0 from public.rrq_balance_v9300 where data_mode='TEST';
 perform public.rr_rm_approve_rate_test71(lot,base+5,'Audit +5');
 select balance into bal1 from public.rrq_balance_v9300 where data_mode='TEST';
 if bal1-coalesce(bal0,0)<>500 then raise exception 'Approval +5 RRQ failed';end if;
 perform public.rr_rm_approve_rate_test71(lot,base+5,'Duplicate');
 if (select balance from public.rrq_balance_v9300 where data_mode='TEST')<>bal1 then raise exception 'Approval duplicate RRQ';end if;
 perform public.rr_rm_approve_rate_test71(lot,base+2,'Audit reduce 3');
 if (select balance from public.rrq_balance_v9300 where data_mode='TEST')-coalesce(bal0,0)<>200 then raise exception 'Approval decrease RRQ';end if;
 j:=public.rr_fg_save_pi_v787(null,party,'AUDIT',jsonb_build_array(jsonb_build_object('lot_no',lot,'stock_type','TRADED','qty',10,'rate',base+2)),0,0,false,'TEST');
 piid:=(j->>'pi_id')::uuid;
 if (select balance from public.rrq_balance_v9300 where data_mode='TEST')-coalesce(bal0,0)<>200 then raise exception 'Draft changed RRQ';end if;
 -- Party flag uses a real canonical customer and allows entered gross rate fluctuation.
 insert into public.rr_customers(customer_name,is_active,allowed_discount_per_piece) values(party,true,0);
 j:=public.rr_fg_save_pi_v787(piid,party,'AUDIT',jsonb_build_array(jsonb_build_object('lot_no',lot,'stock_type','TRADED','qty',10,'rate',base-1,'gross_rate',base-1,'party_discount_per_piece',0)),0,0,true,'TEST');
 if (select balance from public.rrq_balance_v9300 where data_mode='TEST')-coalesce(bal0,0)<>170 then raise exception 'CI rate fluctuation RRQ';end if;
 select id into lineid from public.rr_fg_pi_lines_v787 where pi_id=piid;
 j:=public.rr_fg_post_return_v787('KNOWN',lineid,null,null,2,'Audit return','TEST');
 if (select balance from public.rrq_balance_v9300 where data_mode='TEST')-coalesce(bal0,0)<>176 then raise exception 'Sales return RRQ reversal';end if;
 ret:=public.rr_rm_purchase_return_test71(sid,3,'Audit purchase return',date '2030-01-20',null,'AUDIT-RETURN');
 perform public.rr_rm_purchase_return_test71(sid,3,'Audit purchase return',date '2030-01-20',null,'AUDIT-RETURN');
 if (select available_qty from public.rr_rm_stock_v849_2c6 where stock_id=sid)<>89 then raise exception 'RM available stock failed';end if;
 if (select balance from public.rrq_balance_v9300 where data_mode='TEST')-coalesce(bal0,0)<>170 then raise exception 'Purchase return RRQ reversal';end if;
 if (select sum(qty_delta) from public.rr_fg_stock_ledger_v787 where lot_no=lot and data_mode='TEST')<>89 then raise exception 'Canonical stock mismatch';end if;
 j:=public.rr_rci_save_draft_v9740(null,piid,(select buyer_id from public.rr_fg_pi_v787 where id=piid),'COMBINED',jsonb_build_array(jsonb_build_object('return_type','KNOWN','source_ci_line_id',lineid,'rci_qty',1)),'Readymade RCI audit','RM-RCI-'||lot,'TEST');
 rciid:=(j->>'rci_id')::uuid;
 perform public.rr_rci_post_linked_final_v9741(rciid);
 if (select available_qty from public.rr_rm_stock_v849_2c6 where stock_id=sid)<>90 then raise exception 'RCI returned to wrong stock type';end if;
 if (select balance from public.rrq_balance_v9300 where data_mode='TEST')-coalesce(bal0,0)<>173 then raise exception 'RCI RRQ reversal failed';end if;
 perform public.rr_rm_approve_rate_test71(lot,base+1,'Reapproval remaining only');
 if (select balance from public.rrq_balance_v9300 where data_mode='TEST')-coalesce(bal0,0)<>83 then raise exception 'Reapproval touched sold or returned stock';end if;
 if has_function_privilege('anon','public.rr_rm_purchase_save_test71(uuid,text,text,date,jsonb,boolean)','execute') then raise exception 'Anonymous Purchase permission';end if;
 perform set_config('rm.audit.result','PASS: Purchase, fixed margin, Accounts, overhead, approval +/- RRQ, duplicate approval, PI draft, CI fluctuation, Sales Return, Purchase Return, repeat return, stock reconciliation',true);
end $$;
select current_setting('rm.audit.result') as readymade_e2e_result;
rollback;
