-- TEST71 substantive canonical cleanup V688-V721
-- This migration intentionally preserves legacy public RPC names as compatibility entrypoints
-- while routing active behavior through the canonical authorities established in TEST71.

create or replace function public.rr_upm_advance_completed_colour_v688(p_canonical_lot_id text,p_source_department text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare src text:=public.rr_upm_core_department_v9077(p_source_department);nxt text:=public.rr_upm_strict_next_department_v9106(src);n int:=0;
begin if nxt is null then return jsonb_build_object('ok',true,'source_department',src,'next_department',null,'advanced_colours',0,'terminal',true);end if;
update public.rr_upm_colour_state c set current_department_code=nxt,status='PENDING',updated_at=now() where c.canonical_lot_id=p_canonical_lot_id and public.rr_upm_core_department_v9077(c.current_department_code)=src and c.completed_qty>0 and not exists(select 1 from public.rr_upm_work_assignments_v8 a where a.canonical_lot_id=p_canonical_lot_id and upper(a.colour_code)=upper(c.colour_code) and public.rr_upm_core_department_v9077(a.department_code)=nxt and a.status in('ASSIGNED','IN_PROGRESS','COMPLETED'));get diagnostics n=row_count;perform public.rr_upm_sync_colour_queue_v741(p_canonical_lot_id);return jsonb_build_object('ok',true,'version','V688_CANONICAL_NEXT_AFTER_SUBMIT','source_department',src,'next_department',nxt,'advanced_colours',n,'idempotent',n=0);end $function$;

create or replace function public.rr_upm_finalize_submit_handover_v689(p_request_id uuid,p_count_rows jsonb,p_resolution text default 'EXACT_RECEIVER_COUNT')
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare q public.rr_upm_submit_requests_v794%rowtype;r jsonb;adv jsonb;nxt text;begin select * into q from public.rr_upm_submit_requests_v794 where id=p_request_id;if not found then raise exception 'Submit handover not found';end if;r:=public.rr_upm_finalize_submit_handover_v204(p_request_id,p_count_rows,p_resolution);nxt:=public.rr_upm_strict_next_department_v9106(q.department_code);if public.rr_upm_core_department_v9077(q.department_code)='PRESS' then adv:=jsonb_build_object('ok',true,'state','PRESS_CORE_CREATED_PACKING','advanced_colours',0);else adv:=public.rr_upm_advance_completed_colour_v688(q.canonical_lot_id,q.department_code);end if;update public.rr_upm_submit_requests_v794 set target_department_code=nxt,updated_at=now() where id=p_request_id and target_department_code is null;return r||jsonb_build_object('version','V689_CANONICAL_NEXT_HANDOFF','target_department_code',nxt,'next_projection',adv,'rule','V204 CORE FINALIZE + STRICT CANONICAL NEXT; PRESS PACKING SPECIAL CORE PRESERVED; NO RECURSION');end $function$;

create or replace function public.rr_upm_lm_count_submit_v690(p_request_id uuid,p_count_rows jsonb)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare q public.rr_upm_submit_requests_v794%rowtype;v_ctx jsonb:=public.rr_upm_effective_identity_v200();v_worker uuid:=public.rr_upm_current_worker_id_v9112();v_auth uuid:=nullif(v_ctx->>'effective_auth_user_id','')::uuid;c jsonb;sz jsonb;v_input jsonb;v_qty numeric;v_expected numeric;v_total numeric:=0;v_exact boolean:=true;v_normalized jsonb:='[]';v_sizes jsonb;
begin select * into q from public.rr_upm_submit_requests_v794 where id=p_request_id for update;if not found or q.status<>'LM_ACCEPTED' then raise exception 'Accepted receiver handover required.';end if;if q.selected_receiver_worker_id is distinct from v_worker and q.selected_receiver_auth_id is distinct from v_auth then raise exception 'Only claimed receiver can submit physical count.';end if;
for c in select value from jsonb_array_elements(q.colour_rows) loop v_sizes:='[]';for sz in select value from jsonb_array_elements(c->'sizes') loop select x into v_input from jsonb_array_elements(coalesce(p_count_rows,'[]')) x where upper(x->>'colour_code')=upper(c->>'colour_code') and upper(x->>'size_code')=upper(sz->>'size_code') limit 1;if v_input is null or nullif(v_input->>'qty','') is null then raise exception 'Count Qty required for % / %.',c->>'colour_code',sz->>'size_code';end if;v_qty:=(v_input->>'qty')::numeric;v_expected:=coalesce((sz->>'ready_qty')::numeric,(sz->>'assigned_qty')::numeric,0);v_total:=v_total+v_qty;v_exact:=v_exact and v_qty=v_expected;v_sizes:=v_sizes||jsonb_build_array(jsonb_build_object('size_code',upper(sz->>'size_code'),'assigned_qty',(sz->>'assigned_qty')::numeric,'ready_qty',v_expected,'qty',v_qty));end loop;v_normalized:=v_normalized||jsonb_build_array(jsonb_build_object('colour_id',c->>'colour_id','colour_code',c->>'colour_code','colour_name',c->>'colour_name','sizes',v_sizes));end loop;
if v_exact then return public.rr_upm_finalize_submit_handover_v689(q.id,v_normalized,'EXACT_RECEIVER_COUNT');end if;update public.rr_upm_submit_requests_v794 set status='DISPUTED',lm_count_rows=v_normalized,lm_counted_total=v_total,difference_qty=v_total-worker_ready_total,counted_at=now(),updated_at=now(),dispute_note='Receiver physical count differs from worker Ready Qty' where id=q.id;return jsonb_build_object('ok',true,'version','V690_CANONICAL_RECEIVER_COUNT','request_id',q.id,'status','DISPUTED','difference',v_total-q.worker_ready_total,'work_status','WORKING');end $function$;

create or replace function public.rr_upm_lm_count_submit_v327(p_request_id uuid,p_count_rows jsonb) returns jsonb language sql security definer set search_path to 'public' as $function$ select public.rr_upm_lm_count_submit_v690(p_request_id,p_count_rows)||jsonb_build_object('compatibility_alias','V327_TO_V690') $function$;
create or replace function public.rr_upm_lm_count_submit_v328(p_request_id uuid,p_count_rows jsonb) returns jsonb language sql security definer set search_path to 'public' as $function$ select public.rr_upm_lm_count_submit_v690(p_request_id,p_count_rows)||jsonb_build_object('compatibility_alias','V328_TO_V690') $function$;
create or replace function public.rr_upm_finalize_submit_handover_v327(p_request_id uuid,p_count_rows jsonb,p_resolution text default 'EXACT_RECEIVER_COUNT') returns jsonb language sql security definer set search_path to 'public' as $function$ select public.rr_upm_finalize_submit_handover_v689(p_request_id,p_count_rows,p_resolution)||jsonb_build_object('compatibility_alias','V327_TO_V689') $function$;

create or replace function public.rr_upm_product_cost_actual_v705(p_canonical_lot_id text,p_data_mode text default 'TEST') returns jsonb language sql stable security definer set search_path to 'public' as $function$ select public.rr_upm_product_cost_actual_v709(p_canonical_lot_id,p_data_mode)||jsonb_build_object('compatibility_alias','V705_TO_V709','thread_fixed_cost_authority','FOC_THREAD_1_50_ONLY') $function$;
create or replace function public.rr_upm_product_cost_actual_v687(p_canonical_lot_id text,p_data_mode text default 'TEST') returns jsonb language sql stable security definer set search_path to 'public' as $function$ select public.rr_upm_product_cost_actual_v709(p_canonical_lot_id,p_data_mode)||jsonb_build_object('compatibility_alias','V687_TO_V709') $function$;
create or replace function public.rr_thread_cone_costing_v704(p_pcs numeric,p_data_mode text default 'TEST') returns jsonb language sql stable security definer set search_path to 'public' as $function$ select jsonb_build_object('ok',true,'version','V704_THREAD_FOC_ALIAS','state','FOC_AUTHORITY','fixed_cost_per_pc',1.50,'lot_pcs',p_pcs,'lot_cost',round(p_pcs*1.5,2),'costing_head','FOC','inventory_reconciliation','SEPARATE_PURCHASE_STOCK_ANALYTICS','rule','THREAD PRODUCT COST IS INCLUDED ONCE INSIDE FOC; DO NOT ADD AS SEPARATE PRODUCT COMPONENT') $function$;
create or replace function public.rr_fg_pack_plan_box_cost_trigger_v259() returns trigger language plpgsql as $function$ begin raise exception 'RETIRED V721: automatic first-box trigger is disabled; packer-selected V686 binding required.';end $function$;
