-- Payroll decides payable salary. Costing only allocates earned salary between productive work and lapse.
create or replace function public.rr_costing_salary_reconciliation_v401(p_canonical_lot_id text,p_data_mode text default 'TEST')
returns jsonb language plpgsql stable security definer set search_path to 'public' as $function$
declare l record; ms date; me date; raw jsonb; payroll_total numeric:=0; productive_month numeric:=0; lot_productive numeric:=0; lapse_month numeric:=0; month_qty numeric:=0; lot_qty numeric:=0; lot_lapse numeric:=0; has_salaried boolean:=false; payroll_rows int:=0;
begin
 select * into l from public.rr_upm_lot_registry where canonical_lot_id=p_canonical_lot_id;if not found then raise exception 'Lot not found';end if;
 ms:=date_trunc('month',l.created_at)::date;me:=(date_trunc('month',l.created_at)+interval '1 month - 1 day')::date;raw:=public.rr_costing_salary_allocation_v400(p_canonical_lot_id,p_data_mode);
 select exists(select 1 from public.rr_salaried_profile_canonical_v294 p where upper(p.data_mode)=upper(p_data_mode) and p.effective_from<=me and(p.effective_to is null or p.effective_to>=ms)) into has_salaried;
 select count(*),coalesce(sum(coalesce(p.net_payable_salary,p.monthly_salary_amount,0)),0) into payroll_rows,payroll_total from public.rr_monthly_payroll_v779_1 p where date_trunc('month',p.payroll_month)=ms and upper(p.data_mode)=upper(p_data_mode) and upper(coalesce(p.worker_category,''))='SALARIED';
 if payroll_rows=0 then return raw||jsonb_build_object('version','V401_PAYROLL_RECONCILIATION','payroll_reconciliation_state',case when has_salaried then 'PENDING_MONTHLY_PAYROLL' else 'NOT_APPLICABLE' end,'payroll_period',ms,'payroll_net_payable_total',null,'final_actual_salary_cost',false,'rule','PAYROLL DECIDES PAYABLE SALARY; COSTING DOES NOT');end if;
 select coalesce(sum(salaried_labor_cost),0) into productive_month from public.rr_upm_department_labor_cost_v9160 c join public.rr_upm_lot_registry x on x.canonical_lot_id=c.canonical_lot_id where upper(c.data_mode)=upper(p_data_mode) and x.created_at::date between ms and me;
 select coalesce(sum(salaried_labor_cost),0) into lot_productive from public.rr_upm_department_labor_cost_v9160 where canonical_lot_id=p_canonical_lot_id and upper(data_mode)=upper(p_data_mode);lapse_month:=greatest(payroll_total-productive_month,0);
 select coalesce(sum(greatest(coalesce(r.confirmed_qty,0),0)),0) into month_qty from public.rr_upm_work_assignments_v8 a join public.rr_upm_assignment_receipts_v9112 r on r.assignment_id=a.id and upper(coalesce(r.status,''))='CONFIRMED' join public.rr_upm_lot_registry x on x.canonical_lot_id=a.canonical_lot_id where x.created_at::date between ms and me;
 select coalesce(sum(greatest(coalesce(r.confirmed_qty,0),0)),0) into lot_qty from public.rr_upm_work_assignments_v8 a join public.rr_upm_assignment_receipts_v9112 r on r.assignment_id=a.id and upper(coalesce(r.status,''))='CONFIRMED' where a.canonical_lot_id=p_canonical_lot_id;lot_lapse:=case when month_qty>0 then lapse_month*lot_qty/month_qty else 0 end;
 return raw||jsonb_build_object('version','V401_PAYROLL_RECONCILIATION','payroll_reconciliation_state','FINAL_PAYROLL','payroll_period',ms,'payroll_net_payable_total',round(payroll_total,2),'productive_salary_month',round(productive_month,2),'lapse_salary_month',round(lapse_month,2),'productive_salaried_lot',round(lot_productive,2),'department_lapse_lot',round(lot_lapse,2),'final_actual_salary_cost',true,'reconciled_salary_lot',round(lot_productive+lot_lapse,2),'rule','PAYROLL NET PAYABLE IS AUTHORITY; PRODUCTIVE + LAPSE ARE COST ALLOCATION ONLY');
end $function$;