-- TEST70 V140: Packing + Despatch direct-chat action contract.
-- Existing Finished Goods RPCs remain authoritative; Real Chat is an adapter.
begin;

insert into public.rr_real_chat_action_registry_v70(
  action_code, exact_button_label, source_module, source_page, rpc_name,
  allowed_roles, opens_exact_card, registry_status, notes,
  source_department_code, target_department_code, routing_mode, parent_type,
  source_state, success_state, next_action_code, receiver_rule, unit_label,
  message_template, rollback_rule
)
values
  ('PACKING_ASSIGN','ASSIGN PACKER','PACKING','test70-cb-purchase-real-chat-pilot.html','rr_fg_assign_packing_v788',
   array['OWNER','SUPER_ADMIN','ADMIN','MANAGER'],true,'ACTIVE',
   'Direct-chat adapter; selected active Packing worker becomes the exact receiver.',
   'PRESS','PACKING','HANDOVER','LOT','OPEN','WORKING','PACKING_ACCEPT','EXACT_ASSIGNED_WORKER','PCS',
   'Lot {lot_no} assigned to {worker_name} for Packing.','Existing Packing assignment cancellation/reassignment.'),
  ('PACKING_ACCEPT','ACCEPT PACKING WORK','PACKING','test70-cb-purchase-real-chat-pilot.html','rr_fg_accept_packing_v788',
   array['OWNER','SUPER_ADMIN','ADMIN','MANAGER','PACKING'],true,'ACTIVE',
   'Exact assigned Packer, or the existing authorized manager-on-behalf path.',
   'PACKING','PACKING','SOURCE_GROUP','LOT','WORKING','WORKING','PACKING_ALGORITHM','EXACT_ASSIGNED_WORKER','PCS',
   'Packing custody accepted for Lot {lot_no}.','Existing Packing assignment reset.'),
  ('PACKING_ALGORITHM','RUN / RESET PACKING ALGORITHM','PACKING','test70-cb-purchase-real-chat-pilot.html','rr_fg_generate_assigned_pack_v788',
   array['OWNER','SUPER_ADMIN','ADMIN','MANAGER','PACKING'],true,'ACTIVE',
   'Uses the V9365 backend algorithm; the browser only renders its authoritative result.',
   'PACKING','PACKING','SOURCE_GROUP','LOT','WORKING','WORKING','PACKING_FINAL_PHOTOS','EXACT_ASSIGNED_WORKER','BOX / PCS',
   'Packing table prepared for Lot {lot_no}.','Existing pre-submit plan reset.'),
  ('PACKING_FINAL_PHOTOS','ADD 3 FINAL PHOTOS','PACKING','test70-cb-purchase-real-chat-pilot.html','rr_pack_save_media_v9332',
   array['OWNER','SUPER_ADMIN','ADMIN','MANAGER','PACKING'],true,'ACTIVE',
   'Exactly three CAMERA/product-truth photos; AI images remain optional.',
   'PACKING','PACKING','SOURCE_GROUP','LOT','WORKING','WORKING','PACKING_RATE_REQUEST','EXACT_ASSIGNED_WORKER','PHOTO',
   'Three final product photos saved for Lot {lot_no}.','Specific final-photo delete/replace audit.'),
  ('PACKING_RATE_REQUEST','REQUEST FINAL RATE APPROVAL','PACKING_RATE','test70-cb-purchase-real-chat-pilot.html','rr_pack_request_rate_v9340',
   array['OWNER','SUPER_ADMIN','ADMIN','MANAGER','PACKING'],true,'ACTIVE',
   'Photo-first RRQ. Worker never receives or edits the final sale rate.',
   'PACKING','PACKING','HANDOVER','LOT','WORKING','WORKING','PACKING_RATE_APPROVE','EXACT_ADMIN_RRQ_QUEUE','RATE / PCS',
   'Final rate approval requested for Lot {lot_no}.','Existing RRQ resend/cancel rules.'),
  ('PACKING_RATE_APPROVE','APPROVE FINAL RATE','PACKING_RATE','test70-cb-purchase-real-chat-pilot.html','rr_pack_rate_approve_v9340',
   array['OWNER','SUPER_ADMIN','ADMIN'],true,'ACTIVE',
   'Financial action; server RPC remains the permission and audit authority.',
   'PACKING','PACKING','SOURCE_GROUP','LOT','WORKING','WORKING','PACKING_SUBMIT','EXACT_ADMIN_RRQ_QUEUE','RATE / PCS',
   'Final rate approved for Lot {lot_no}.','Existing final-rate revision audit.'),
  ('PACKING_SUBMIT','SUBMIT PACKING','PACKING','test70-cb-purchase-real-chat-pilot.html','rr_fg_submit_assigned_pack_v788',
   array['OWNER','SUPER_ADMIN','ADMIN','MANAGER','PACKING'],true,'ACTIVE',
   'Closes only Packing and atomically exposes submitted boxes to Despatch OPEN.',
   'PACKING','DESPATCH','HANDOVER','LOT','WORKING','CLOSE','DESPATCH_CREATE','DESPATCH_QUEUE','BOX / PCS',
   'Lot {lot_no} packed and ready for Despatch.','Existing pack-plan reversal.'),
  ('DESPATCH_CREATE','CREATE & LOCK CHALLAN','DESPATCH','test70-cb-purchase-real-chat-pilot.html','rr_fg_create_despatch_lot_v9361',
   array['OWNER','SUPER_ADMIN','ADMIN','MANAGER','DESPATCH'],true,'ACTIVE',
   'Full-lot compact action; detailed app remains available for partial box selection.',
   'DESPATCH','DESPATCH','HANDOVER','LOT','OPEN','WORKING','STORE_RECEIVE','EXACT_LINE_MAN','BOX / PCS',
   'Challan {challan_no} locked and sent to the selected Delivery Lineman.','Existing Despatch cancellation/reversal.'),
  ('STORE_RECEIVE','VERIFY & RECEIVE','DESPATCH','test70-cb-purchase-real-chat-pilot.html','rr_fg_receive_accept_v9361',
   array['OWNER','SUPER_ADMIN','ADMIN','STORE','DESPATCH'],true,'ACTIVE',
   'Exact source groups and custody; mismatch stays WORKING as Difference Hold.',
   'DESPATCH','STOCK','HANDOVER','LOT','WORKING','CLOSE','STOCK_POST','EXACT_STORE_RECEIVER','BOX / PCS',
   'Challan {challan_no} received and stock posted.','Difference Hold / authorized receive correction.')
on conflict(action_code) do update set
  exact_button_label=excluded.exact_button_label,
  source_module=excluded.source_module,
  source_page=excluded.source_page,
  rpc_name=excluded.rpc_name,
  allowed_roles=excluded.allowed_roles,
  opens_exact_card=excluded.opens_exact_card,
  registry_status=excluded.registry_status,
  notes=excluded.notes,
  source_department_code=excluded.source_department_code,
  target_department_code=excluded.target_department_code,
  routing_mode=excluded.routing_mode,
  parent_type=excluded.parent_type,
  source_state=excluded.source_state,
  success_state=excluded.success_state,
  next_action_code=excluded.next_action_code,
  receiver_rule=excluded.receiver_rule,
  unit_label=excluded.unit_label,
  message_template=excluded.message_template,
  rollback_rule=excluded.rollback_rule,
  updated_at=now();

commit;
