-- Operational classification fallback only: no salary or rate amount is invented.
create or replace function public.rr_department_compensation_choices_v667(p_department_code text,p_data_mode text default 'TEST')
returns jsonb language plpgsql stable security definer set search_path to 'public' as $function$
declare d text:=public.rr_costing_canonical_department_v760(p_department_code);s jsonb;p jsonb;u jsonb;
begin
 select coalesce(jsonb_agg(jsonb_build_object('worker_id',b.worker_id,'worker_name',b.worker_name,'monthly_salary',b.monthly_salary) order by b.worker_name),'[]'::jsonb) into s from public.rr_worker_payroll_board_v777_3 b where upper(coalesce(b.data_mode,'TEST'))=upper(coalesce(p_data_mode,'TEST')) and b.payroll_profile_status='ACTIVE' and public.rr_costing_canonical_department_v760(b.department_code)=d and upper(b.worker_category)='SALARIED';
 select coalesce(jsonb_agg(jsonb_build_object('worker_id',b.worker_id,'worker_name',b.worker_name) order by b.worker_name),'[]'::jsonb) into p from public.rr_worker_payroll_board_v777_3 b where upper(coalesce(b.data_mode,'TEST'))=upper(coalesce(p_data_mode,'TEST')) and b.payroll_profile_status='ACTIVE' and public.rr_costing_canonical_department_v760(b.department_code)=d and upper(b.worker_category)<>'SALARIED';
 select coalesce(jsonb_agg(jsonb_build_object('worker_id',b.worker_id,'worker_name',b.worker_name) order by b.worker_name),'[]'::jsonb) into u from public.rr_worker_payroll_board_v777_3 b where public.rr_costing_canonical_department_v760(b.department_code)=d and b.worker_category is null and b.payroll_profile_status is null;
 if jsonb_array_length(s)=0 and jsonb_array_length(p)=0 and jsonb_array_length(u)>0 and exists(select 1 from public.rr_upm_department_rates_v2 r where public.rr_costing_canonical_department_v760(r.department_code)=d and coalesce(r.actual_rate,0)>0) then p:=u; end if;
 return jsonb_build_object('department_code',d,'salaried_team',s,'piece_rate_workers',p,'unconfigured_workers',u,'has_salaried_team',jsonb_array_length(s)>0,'has_piece_rate',jsonb_array_length(p)>0,'auto_mode',case when jsonb_array_length(s)>0 and jsonb_array_length(p)=0 then 'SALARIED_TEAM' when jsonb_array_length(p)>0 and jsonb_array_length(s)=0 then 'PIECE_RATE' else null end,'mixed',jsonb_array_length(s)>0 and jsonb_array_length(p)>0,'financial_rate_source',case when jsonb_array_length(s)=0 and jsonb_array_length(p)>0 and jsonb_array_length(u)>0 then 'LOT_DEPARTMENT_ACTUAL_RATE_REQUIRED' else 'PAYROLL_PROFILE' end);
end $function$;