-- Split final payroll into production-team and staff/support pools before costing allocation.
create or replace function public.rr_costing_salary_reconciliation_v402(p_canonical_lot_id text,p_data_mode text default 'TEST')
returns jsonb language plpgsql stable security definer set search_path to 'public' as $function$
declare l record;ms date;me date;raw jsonb;prod_pay numeric:=0;staff_pay numeric:=0;prod_month numeric:=0;lot_prod numeric:=0;prod_lapse numeric:=0;month_qty numeric:=0;lot_qty numeric:=0;lot_lapse numeric:=0;staff_raw numeric:=0;staff_month_raw numeric:=0;staff_lot numeric:=0;payrows int:=0;
begin
 select * into l from public.rr_upm_lot_registry where canonical_lot_id=p_canonical_lot_id;if not found then raise exception 'Lot not found';end if;ms:=date_trunc('month',l.created_at)::date;me:=(date_trunc('month',l.created_at)+interval '1 month - 1 day')::date;raw:=public.rr_costing_salary_allocation_v400(p_canonical_lot_id,p_data_mode);
 with p as(select coalesce(m.net_payable_salary,m.monthly_salary_amount,0) pay,public.rr_costing_canonical_department_v760(w.department_code) dept,upper(coalesce(w.role_code,'')) role from public.rr_monthly_payroll_v779_1 m join public.rr_worker_directory_compat_v264 w on w.worker_id=public.rr_canonical_worker_id_v264(m.worker_id) where date_trunc('month',m.payroll_month)=ms and upper(m.data_mode)=upper(p_data_mode) and upper(coalesce(m.worker_category,''))='SALARIED')
 select count(*),coalesce(sum(pay) filter(where dept not in('FABRICATION','ADMIN','ACCOUNTS','SALES') and role not in('LINE MAN','LINE_MAN','MANAGER','ADMIN','ACCOUNT','ACCOUNTS','SALESMAN','SALES')),0),coalesce(sum(pay) filter(where dept in('FABRICATION','ADMIN','ACCOUNTS','SALES') or role in('LINE MAN','LINE_MAN','MANAGER','ADMIN','ACCOUNT','ACCOUNTS','SALESMAN','SALES')),0) into payrows,prod_pay,staff_pay from p;
 if payrows=0 then return raw||jsonb_build_object('version','V402_SPLIT_PAYROLL_RECONCILIATION','payroll_reconciliation_state','PENDING_MONTHLY_PAYROLL','final_actual_salary_cost',false,'payroll_period',ms,'rule','NO FINAL PAYROLL = PROVISIONAL COSTING ONLY');end if;
 select coalesce(sum(c.salaried_labor_cost),0) into prod_month from public.rr_upm_department_labor_cost_v9160 c join public.rr_upm_lot_registry x on x.canonical_lot_id=c.canonical_lot_id where upper(c.data_mode)=upper(p_data_mode) and x.created_at::date between ms and me and c.department_code not in('FABRICATION','ADMIN','ACCOUNTS','SALES');
 select coalesce(sum(c.salaried_labor_cost),0) into lot_prod from public.rr_upm_department_labor_cost_v9160 c where c.canonical_lot_id=p_canonical_lot_id and upper(c.data_mode)=upper(p_data_mode) and c.department_code not in('FABRICATION','ADMIN','ACCOUNTS','SALES');
 prod_month:=least(prod_month,prod_pay);lot_prod:=least(lot_prod,prod_pay);prod_lapse:=greatest(prod_pay-prod_month,0);
 select coalesce(sum(greatest(coalesce(r.confirmed_qty,0),0)),0) into month_qty from public.rr_upm_work_assignments_v8 a join public.rr_upm_assignment_receipts_v9112 r on r.assignment_id=a.id and upper(coalesce(r.status,''))='CONFIRMED' join public.rr_upm_lot_registry x on x.canonical_lot_id=a.canonical_lot_id where x.created_at::date between ms and me;
 select coalesce(sum(greatest(coalesce(r.confirmed_qty,0),0)),0) into lot_qty from public.rr_upm_work_assignments_v8 a join public.rr_upm_assignment_receipts_v9112 r on r.assignment_id=a.id and upper(coalesce(r.status,''))='CONFIRMED' where a.canonical_lot_id=p_canonical_lot_id;
 lot_lapse:=case when month_qty>0 then prod_lapse*lot_qty/month_qty else 0 end;staff_raw:=coalesce((raw->>'fabrication_staff_lot')::numeric,0);
 with lots as(select x.canonical_lot_id,public.rr_costing_salary_allocation_v400(x.canonical_lot_id,p_data_mode) j from public.rr_upm_lot_registry x where x.created_at::date between ms and me) select coalesce(sum((j->>'fabrication_staff_lot')::numeric),0) into staff_month_raw from lots;
 staff_lot:=case when staff_month_raw>0 then least(staff_raw,staff_pay*staff_raw/staff_month_raw) else 0 end;
 return raw||jsonb_build_object('version','V402_SPLIT_PAYROLL_RECONCILIATION','payroll_reconciliation_state','FINAL_PAYROLL','final_actual_salary_cost',true,'payroll_period',ms,'production_team_payroll',round(prod_pay,2),'staff_support_payroll',round(staff_pay,2),'productive_salary_month',round(prod_month,2),'production_lapse_month',round(prod_lapse,2),'productive_salaried_lot',round(lot_prod,2),'department_lapse_lot',round(lot_lapse,2),'fabrication_staff_lot',round(staff_lot,2),'reconciled_salary_lot',round(lot_prod+lot_lapse+staff_lot,2),'rule','PAYROLL AUTHORITY; PRODUCTION PRODUCTIVE+LAPSE SEPARATE FROM STAFF SUPPORT; EACH POOL CAPPED');
end $function$;