-- Preserve payroll authorization predicates; evaluate caller identity once per statement.
-- Fabrication WORKING queue reads this view for team classification across departments.
CREATE OR REPLACE VIEW public.rr_worker_payroll_board_v777_3 AS  SELECT worker_id,
    worker_code,
    worker_name,
    department_code,
    role_code,
    profile_id,
    worker_category,
    shift_id,
    shift_code,
    shift_name,
    duty_start,
    duty_end,
    normal_payable_minutes,
    lunch_is_paid,
    grace_in_minutes,
    minimum_presence_minutes,
    overtime_multiplier,
    holiday_multiplier,
    monthly_salary,
    attendance_required,
    late_deduction_applicable,
    overtime_applicable,
    holiday_extra_applicable,
    grace_offset_against_ot,
    exception_reason,
    piece_advance_percent,
    piece_advance_floor,
    salaried_advance_limit_type,
    salaried_advance_limit_value,
    advance_cycle,
    settlement_cycle,
    salary_advance_day,
    salary_due_day,
    claim_debit_timing,
    effective_from,
    effective_to,
    payroll_profile_status,
    data_mode,
    configured_at,
    configured_by,
    reason
   FROM ( WITH latest AS (
                 SELECT DISTINCT ON (p_1.worker_id, p_1.data_mode) p_1.profile_id,
                    p_1.worker_id,
                    p_1.worker_category,
                    p_1.shift_id,
                    p_1.monthly_salary,
                    p_1.weekly_holiday_isodow,
                    p_1.attendance_required,
                    p_1.late_deduction_applicable,
                    p_1.overtime_applicable,
                    p_1.holiday_extra_applicable,
                    p_1.grace_offset_against_ot,
                    p_1.exception_reason,
                    p_1.piece_advance_percent,
                    p_1.piece_advance_floor,
                    p_1.salaried_advance_limit_type,
                    p_1.salaried_advance_limit_value,
                    p_1.advance_cycle,
                    p_1.settlement_cycle,
                    p_1.salary_advance_day,
                    p_1.salary_due_day,
                    p_1.claim_debit_timing,
                    p_1.effective_from,
                    p_1.effective_to,
                    p_1.status,
                    p_1.data_mode,
                    p_1.configured_at,
                    p_1.configured_by,
                    p_1.reason
                   FROM rr_worker_payroll_profile_v777_2 p_1
                  ORDER BY p_1.worker_id, p_1.data_mode, (p_1.status = 'ACTIVE'::text) DESC, p_1.effective_from DESC, p_1.configured_at DESC
                )
         SELECT w.worker_id,
            w.worker_code,
            w.worker_name,
            w.department_code,
            w.role_code,
            p.profile_id,
            p.worker_category,
            p.shift_id,
            s.shift_code,
            s.shift_name,
            s.duty_start,
            s.duty_end,
            s.normal_payable_minutes,
            s.lunch_is_paid,
            s.grace_in_minutes,
            s.minimum_presence_minutes,
            s.overtime_multiplier,
            s.holiday_multiplier,
            p.monthly_salary,
            p.attendance_required,
            p.late_deduction_applicable,
            p.overtime_applicable,
            p.holiday_extra_applicable,
            p.grace_offset_against_ot,
            p.exception_reason,
            p.piece_advance_percent,
            p.piece_advance_floor,
            p.salaried_advance_limit_type,
            p.salaried_advance_limit_value,
            p.advance_cycle,
            p.settlement_cycle,
            p.salary_advance_day,
            p.salary_due_day,
            p.claim_debit_timing,
            p.effective_from,
            p.effective_to,
            p.status AS payroll_profile_status,
            p.data_mode,
            p.configured_at,
            p.configured_by,
            p.reason
           FROM rr_worker_directory_unified_v1 w
             LEFT JOIN latest p ON p.worker_id = w.worker_id
             LEFT JOIN rr_shift_master_v777_2 s ON s.shift_id = p.shift_id) protected_rows
  WHERE (SELECT auth.uid()) IS NOT NULL AND ((SELECT public.rr_worker_salary_can_view_v781()) OR worker_id::text = NULLIF((SELECT public.rr_upm_effective_identity_v200()) ->> 'worker_id'::text, ''::text));
